"""
This program holds custom pytorch data structures for use in this project.
"""
from torch.utils.data import Dataset
    
from joblib import dump, load, Parallel, delayed
import pandas as pd
import torch
import numpy as np

class FluxData(Dataset):
    """
    A class that inherits from torch.Dataset that returns both the data from
    the model evaluation and the parameters used to generate the model.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self,labels, scaler, scaler_name, scaling=False):
        super().__init__()
        self.labels = pd.read_csv(labels)
        self.pars_list = [1,13,2,3,4]
        self.scaling = scaling
        self.scaler_name = scaler_name
        if scaling == True:
            print(f"Creating scaler with name {scaler_name}")
            self.scaler = scaler
            self.scaler_create()
        else:
            self.scaler = load(f'scalers/{self.scaler_name}')
    
    def __len__(self):
        return len(self.labels)
    
    def __getitem__(self,idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[[3]] = -parameters.iloc[[3]]
        parameters.iloc[[1,2,3,4]] = np.log10(parameters.iloc[[1,2,3,4]])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        #scale spectra by energy bin to normalized space
        datum = self.standardize(datum)
        return datum, parameters
    
    def standardize(self,D):
        """
        Filters 0 flux and converts to smallest non-zero value. Then standard
        scales the energy bins.
        """
        D[D<=1e-38] = 1e-38
        D = np.log10(D)
        D = self.scale(D)
        D = torch.from_numpy(D)
        D = D.double()
        return D
    
    def scaler_create(self):
        """
        Creates and loads the scaler for the dataset.

        Returns
        -------
        None.

        """
        data = []
        for file in self.labels.iloc[:,-1]:
            data.append(np.loadtxt(file).reshape(1, -1))
        final_dataset = np.concatenate(data,axis=0)
        final_dataset[final_dataset<=1e-38] = 1e-38
        final_dataset = np.log10(final_dataset)
        data = self.scaler.fit(final_dataset)
        dump(self.scaler, f'scalers/{self.scaler_name}', compress=True)
        return
    
    def scale(self,data):
        """
        Standard scales the logarithm spaced data by energy bin and saves the
        standard scaler for future use.

        Parameters
        ----------
        data : np.ndarray
            Array of spectra in the logspace.

        Returns
        -------
        scaled_data : np.ndarray
            Scaled array of spectra in the logspace.

        """
        scaled_data = self.scaler.transform(data)
        return scaled_data

class LagsData(FluxData):
    
    def __init__(self,labels, scaler, scaler_name, scaling=False):
        super(FluxData, self).__init__()
        self.labels = pd.read_csv(labels)
        self.pars_list = [1,13,2,3,4]
        self.scaling = scaling
        self.scaler_name = scaler_name
        self.threshold = 1e-6
        if scaling == True:
            print(f"Creating scaler with name {scaler_name}")
            self.scaler = scaler
            self.scaler_create()
        else:
            self.scaler = load(f'scalers/{self.scaler_name}')
            self.minimums = (10**(self.scaler.min_))/0.9
            
    def standardize(self, D):
        ind = np.where(D >= 0, 1, 0)
        D = np.abs(D)
        #set all values lower than the threshold to threshold to avoid 0s
        #becoming infinities
        D[D<self.threshold] = self.threshold
        D = np.log10(D)
        D = self.scale(D)
        D = torch.from_numpy(D)
        D = D.double()
        ind = torch.from_numpy(ind)
        ind = ind.double()
        return D, ind
    
    def scaler_create(self):
        data = []
        for file in self.labels.iloc[:,-1]:
            data.append(np.loadtxt(file).reshape(1, -1))
        D = np.concatenate(data,axis=0)
        D = np.abs(D)
        D[D<self.threshold] = self.threshold
        D = np.log10(D)
        data = self.scaler.fit_transform(D)
        dump(self.scaler, f'scalers/{self.scaler_name}', compress=True)
        return
    
    def __getitem__(self,idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[[3]] = -parameters.iloc[[3]]
        parameters.iloc[[1,2,3,4]] = np.log10(parameters.iloc[[1,2,3,4]])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        #scale spectra by energy bin to normalized space
        datum, ind = self.standardize(datum)
        return datum, ind, parameters
 