"""
This program holds custom pytorch data structures for use in this project.
"""
from torch.utils.data import Dataset

from joblib import dump, load
import pandas as pd
import torch
import numpy as np

class FluxData(Dataset):
    """
    A class that inherits from torch.Dataset that returns both the data from
    the model evaluation and the parameters used to generate the model.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self, labels, scaler, scaler_name, pars_list, negatives = [], 
                 logged = [], scaling=False):
        super().__init__()
        self.labels = pd.read_csv(labels)
        self.pars_list = pars_list
        self.negatives = negatives
        self.logged = logged
        self.scaling = scaling
        self.scaler_name = scaler_name
        self.threshold = 1e-39
        if scaling == True:
            print(f"Creating scaler with name {scaler_name}")
            self.scaler = scaler
            self.scaler_create()
        else:
            self.scaler = load(f'scalers/{self.scaler_name}')
    
    def __len__(self):
        return len(self.labels)
    
    def __getitem__(self, idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[self.negatives] = -parameters.iloc[self.negatives]
        parameters.iloc[self.logged] = np.log10(parameters.iloc[self.logged])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        #scale spectra by energy bin to normalized space
        datum = self.standardize(datum)
        return datum, parameters
    
    def standardize(self, D):
        """
        Filters 0 flux and converts to smallest non-zero value. Then standard
        scales the energy bins.
        """
        D[D<=self.threshold] = self.threshold
        D = np.log10(D)
        D = self.scale(D)
        D = torch.from_numpy(D)
        D = D.double()
        return D
    
    def scaler_create(self):
        """
        Creates and loads the scaler for the dataset.

        Returns
        -------
        None.

        """
        data = []
        for file in self.labels.iloc[:,-1]:
            data.append(np.loadtxt(file).reshape(1, -1))
        final_dataset = np.concatenate(data,axis=0)
        final_dataset[final_dataset<=self.threshold] = self.threshold
        final_dataset = np.log10(final_dataset)
        data = self.scaler.fit(final_dataset)
        dump(self.scaler, f'scalers/{self.scaler_name}', compress=True)
        return
    
    def scale(self, data):
        """
        Standard scales the logarithm spaced data by energy bin and saves the
        standard scaler for future use.

        Parameters
        ----------
        data : np.ndarray
            Array of spectra in the logspace.

        Returns
        -------
        scaled_data : np.ndarray
            Scaled array of spectra in the logspace.

        """
        scaled_data = self.scaler.transform(data)
        return scaled_data

class LagsData(FluxData):
    """
    A class that inherits from FluxData that returns both the data from
    the model evaluation and the parameters used to generate the model.
    The major difference is that time lags are signed in nature and thus 
    must be normalized in a different manner. This class also returns the
    signed indices for each energy bin, so that the network may learn
    the signed nature of the time lags as well as the absolute magnitudes.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self, labels, scaler, scaler_name, pars_list, negatives = [], 
                 logged = [], scaling=False):
        super(FluxData, self).__init__()
        self.labels = pd.read_csv(labels)
        self.pars_list = pars_list
        self.negatives = negatives
        self.logged = logged
        self.scaling = scaling
        self.scaler_name = scaler_name
        self.threshold = 1e-7
        if scaling == True:
            print(f"Creating scaler with name {scaler_name}")
            self.scaler = scaler
            self.scaler_create()
        else:
            self.scaler = load(f'scalers/{self.scaler_name}')
            self.minimums = (10**(self.scaler.min_))/0.9
            
    def standardize(self, D):
        """
        Returns signed indices and normalized values of time lags. Lags are 
        normalized by taking the logarithm of the absolute value which is then
        normalized between 0 and 1.
        
        Parameters
        ----------
        D : np.ndarray
            Array of time lags
            
        Returns
        -------
        norm_D : torch.Tensor
            normalized data
        ind : torch.Tensor
            signed indices (0 indicates a negative value, 1 a positive value)
        """
        ind = np.where(D >= 0, 1, 0)
        D = np.abs(D)
        #set all values lower than the threshold to threshold to avoid 0s
        #becoming infinities
        D[D<self.threshold] = self.threshold
        D = np.log10(D)
        D = self.scale(D)
        D = torch.from_numpy(D)
        norm_D = D.double()
        ind = torch.from_numpy(ind)
        ind = ind.double()
        return norm_D, ind
    
    def scaler_create(self):
        """
        Loads all data from the list of time lags locations and then creates
        a scikitlearn scaler fitted on these data. Saves this scaler to disk 
        for further use.

        Returns
        -------
        None.

        """
        data = []
        for file in self.labels.iloc[:,-1]:
            data.append(np.loadtxt(file).reshape(1, -1))
        D = np.concatenate(data,axis=0)
        D = np.abs(D)
        D[D<self.threshold] = self.threshold
        D = np.log10(D)
        data = self.scaler.fit(D)
        dump(self.scaler, f'scalers/{self.scaler_name}', compress=True)
        return
    
    def __getitem__(self, idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[self.negatives] = -parameters.iloc[self.negatives]
        parameters.iloc[self.logged] = np.log10(parameters.iloc[self.logged])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        #scale spectra by energy bin to normalized space
        datum, ind = self.standardize(datum)
        return datum, ind, parameters
 
class LoadFluxData(FluxData):
    """
    A class that inherits from FluxData and instead loads in data in its pure
    form.
    """
    def __init__(self, labels, scaler, scaler_name, pars_list, negatives = [], 
                 logged = []):
        super().__init__(labels, scaler, scaler_name, pars_list, negatives = [], 
                     logged = [])
        
    def __getitem__(self,idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[self.negatives] = -parameters.iloc[self.negatives]
        parameters.iloc[self.logged] = np.log10(parameters.iloc[self.logged])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        return datum, parameters

class LoadLagsData(LagsData):
    """
    A class that inherits from LagsData and instead loads in data in its pure
    form.
    """
    def __init__(self, labels, scaler, scaler_name, pars_list, negatives = [], 
                 logged = []):
        super().__init__(labels, scaler, scaler_name, pars_list, negatives = [], 
                     logged = [])
        
    def __getitem__(self,idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,-1]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[self.negatives] = -parameters.iloc[self.negatives]
        parameters.iloc[self.logged] = np.log10(parameters.iloc[self.logged])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        return datum, parameters

class Residual():
    """
    Class that holds residuals in an object for manipulation
    """
    def __init__(self, residuals):
        self.data = residuals

class Losses():
    """
    Class that dynamically holds residuals in an object for manipulation
    """
    
    def set_loss(self, residuals, name):
        super().__setattr__(name, residuals)
        