"""
This program simulates a test case and attempts a simple MCMC fit using the
emcee package and the emulator.
"""

import emcee
import numpy as np
from generator import rtdist_flux
from reltrans import _models
import torch
import os
import matplotlib.pyplot as plt

def poisson_noise(data):
    """
    This function applies a poisson distribution to a photon spectra

    Parameters
    ----------
    data : np.ndarray
        spectra to randomly distribute.

    Returns
    -------
    new_data : np.ndarray
        new spectra drawn from poisson distributions.

    """
    rng = np.random.default_rng()
    #draws a single sample from a poisson distribution for each energy bin
    new_data = rng.poisson(lam = data,size = (1,data.shape[0])).squeeze()
    return new_data
    
def emulator(theta):
    """
    The function calls the emulator and returns the predicted spectra.

    Parameters
    ----------
    theta : np.ndarray
        model parameters.

    Returns
    -------
    model : np.ndarray
        Model spectra for the provided parameters.

    """

def log_prior(theta):
    a, inc, inner_r, outer_r, mass = theta
    if (0.0 < a < 0.998 and np.log10(1.) < inc < np.log10(80.0) 
        and np.log10(1) < inner_r < np.log10(400.0)
        and np.log10(400) < outer_r < np.log10(1e5) 
        and np.log10(1e4) < mass < np.log10(1e11)):
        return 0.0
    return -np.inf


def log_likelihood(theta, data):
    """
    

    Parameters
    ----------
    data : numpy array
        a series of float data points that should be a counts from a spectra 
        generated by XSPEC or actual data.
    theta : numpy array
        model parameters.

    Returns
    -------
    summation : float
        likelihood probability that the proposed model is correct based on the
        data inputted (x).

    """
    model = emulator(theta)
    x = data
    l = model
    l[l==0] += 1e-20 #model can't have 0 counts in poisson likelihoods
    #There are 3 terms in a log poisson likelihood: x*log(l) - l - sum{log(x!)}
    first = x*np.log(l) #first term
    thirds = np.zeros(x.shape) #third term
    for i,d in enumerate(x):
        fact = np.arange(1,d,step=1)
        thirds[i] = np.sum(np.log(fact))
    poissons = first - l - thirds #poisson likelihoods per data point
    summation = np.sum(poissons) #sum poisson likelihoods for whole spectra
    return summation

def log_probability(theta, x, y, yerr):
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + log_likelihood(theta, data)

def spectrum_to_data(data):
    """
    Applies instrument time of XMM-Newton to outputs

    Parameters
    ----------
    data : np.ndarray
        spectra in units of #/cm^2/s/keV.

    Returns
    -------
    data : np.ndarray
        spectra in units of #/cm^2/keV.

    """
    data = data*250e3
    return data

from scipy.optimize import minimize

dimensions = 5

a_true = 0.9
inc_true = np.log10(57)
inner_r_true = np.log10(-1*-1)
outer_r_true = np.log10(2e4)
mass_true = np.log10(3e6)

from sherpa.astro.data import DataPHA

from sherpa.astro.io import read_arf, read_rmf, read_pha
from sherpa.astro.ui import unpack_rmf, fake, fake_pha

data = DataPHA(name='any', channel=None, counts=None, exposure=250000.)

data.set_arf(read_arf(os.getcwd()+"/ResponseFiles/PN.arf"))

data.set_rmf(read_rmf(os.getcwd()+"/ResponseFiles/PN.rmf"))


rmf_name = wrk_dir = os.getcwd()+"/ResponseFiles/PN.rmf"
rmf = unpack_rmf(rmf_name)
egrid = rmf.e_min #energy grid used to evaluate the xspec model

pars = [6,0.9,57,-1,2e4,0.024917,2.45,1e5,1,17,50.,5,1,3e6,0.02,0,0,0,
             0,0,0,-0.8,0.3,2.2e-4,1,1.]

model = _models.tdrtdist()

fake_pha(data, model)
data.set_analysis('energy')
from sherpa.plot import DataPlot

dplot = DataPlot()

dplot.prepare(data)

dplot.plot(xlog=True, ylog=True)

np.random.seed(42)
nll = lambda *args: -log_likelihood(*args)
initial = np.array([a_true, inc_true, inner_r_true, outer_r_true,mass_true]) + 0.1 * np.random.randn(dimensions)
soln = minimize(nll, initial, args=(data))
a_sln, inc_sln, inner_r_sln, outer_r_sln, mass_sln = soln.x

print(f"Solved a: {a_sln}")
print(f"Solved inc: {inc_sln}")
print(f"Solved inner radius: {inner_r_sln}")
print(f"Solved outer radius: {outer_r_sln}")
print(f"Solved mass: {mass_sln}")

pos = soln.x + 1e-4 * np.random.randn(32, 5)
nwalkers, ndim = pos.shape

sampler = emcee.EnsembleSampler(
    nwalkers, ndim, log_probability, args=(data)
)
sampler.run_mcmc(pos, 5000, progress=True);

fig, axes = plt.subplots(dimensions, figsize=(10, 7), sharex=True)
samples = sampler.get_chain()
labels = ["a", "inc", "inner radius (ISCOs)", "outer radius (Rg)", r"Mass (M_{$\odot$}"]
for i in range(ndim):
    ax = axes[i]
    ax.plot(samples[:, :, i], "k", alpha=0.3)
    ax.set_xlim(0, len(samples))
    ax.set_ylabel(labels[i])
    ax.yaxis.set_label_coords(-0.1, 0.5)

axes[-1].set_xlabel("step number");
plt.savefig("test_case/chains.png")
plt.close()

tau = sampler.get_autocorr_time()
print(tau)

flat_samples = sampler.get_chain(discard=100, thin=15, flat=True)
print(flat_samples.shape)

import corner

fig = corner.corner(
    flat_samples, labels=labels, truths=[a_true, inc_true, inner_r_true, 
                                         outer_r_true, mass_true]
);