"""
This program simulates a test case and attempts a simple MCMC fit using the
emcee package and the emulator.
"""

import emcee
import numpy as np
from reltrans import _models

import torch

def emulator(theta):
    """
    The function calls the emulator and returns the predicted spectra.

    Parameters
    ----------
    theta : np.ndarray
        DESCRIPTION.

    Returns
    -------
    None.

    """
    
def log_likelihood(theta, data):
    """
    

    Parameters
    ----------
    data : numpy array
        a series of float data points that should be a counts from a spectra 
        generated by XSPEC or actual data.
    theta : numpy array
        model parameters.

    Returns
    -------
    summation : float
        likelihood probability that the proposed model is correct based on the
        data inputted (x).

    """
    model = emulator(theta)
    x = data
    l = model
    l[l==0] += 1e-20 #model can't have 0 counts in poisson likelihoods
    #There are 3 terms in a log poisson likelihood: x*log(l) - l - sum{log(x!)}
    first = x*np.log(l) #first term
    thirds = np.zeros(x.shape) #third term
    for i,d in enumerate(x):
        fact = np.arange(1,d,step=1)
        thirds[i] = np.sum(np.log(fact))
    poissons = first - l - thirds #poisson likelihoods per data point
    summation = np.sum(poissons) #sum poisson likelihoods for whole spectra
    return summation
