"""
This program fits a test spectrum generated by rtdist in xspec using RTFAST.
"""

import os
import copy

import numpy as np
import torch
from scipy.special import gammaln
from scipy.stats import norm
from astropy.io import fits

#plotting libraries
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault)
import corner
import matplotlib

#this is the only required import from rtdist-emulator - this serves as the baseline model
from network import RTFAST
#we also need to be able to model instruments in x-ray astronomy. This is courtesy of
#ndspec, developed by Matteo Lucchini at API. 
from ndspec import Response
#import the xillver table to approximate flux of the corona
#from reltrans._models import lmodxiller as xillver
from sherpa.astro import xspec

import dynesty
from dynesty import plotting as dyplot
from dynesty import utils as dyfunc

def poisson_func(x,l):
    """
    Calculates the poisson likelihood.

    Parameters
    ----------
    x : numpy array
        a series of float data points that should be a counts from a spectra 
        generated by XSPEC or actual data.
    l : numpy array
        the model of the spectra to be compared to the original data.

    Returns
    -------
    summation : float
        likelihood probability that the proposed model is correct based on the
        data inputted (x).

    """
    #There are 3 terms in a log poisson likelihood: x*log(l) - l - sum{log(x!)} (gamma function = last term)
    poissons = x*torch.log(l) - l - gammaln(x + 1.0) #poisson likelihoods per data point
    summation = torch.sum(poissons) #sum poisson likelihoods for whole spectra
    if torch.isnan(summation): #if something goes wrong, e.g. there's an infinify somewhere, return invalid
        return -1e100
    return summation.detach().numpy()

def gaussian_func(theta):
    """
    Calculates the gaussian likelihood.

    Parameters
    ----------
    x : numpy array
        a series of float data points that should be a counts from a spectra 
        generated by XSPEC or actual data.
    l : numpy array
        the model of the spectra to be compared to the original data.

    Returns
    -------
    summation : float
        likelihood probability that the proposed model is correct based on the
        data inputted (x).
    """
    x = torch.Tensor(data) #converts data to pytorch Tensor for gradient purposes
    l = torch.Tensor(convolve_sim(torch.Tensor(theta))) #evaluates model
    gaussians = -1*((l - x)**2)/((2*x)**2) #model emulator error as 3% scatter
    gaussians[x==0] = 0
    summation = torch.sum(gaussians)
    if torch.isnan(summation): #if something goes wrong, e.g. there's an infinify somewhere, return invalid
        return -1e100
    return summation.detach().numpy()

def poisson_gaussian_mixture(theta):
    """
    Combines the poissonian and gaussian likelihoods.

    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to calculate log likelihood of.
    
    Returns:
    --------
    log_likeli : float
        log likelihood of parameter set being the true model
    """
    x = torch.Tensor(data) #converts data to pytorch Tensor for gradient purposes
    l = torch.Tensor(convolve_sim(torch.Tensor(theta))) #evaluates model
    l[l==0] += 1e-20 #This offsets 0 counts by a slight amount (can't take the logarithm of 0)

    log_likeli = poisson_func(x,l) + gaussian_func(x,l)
    return log_likeli

def gaussian_scatter(theta, scatter=0.03):
    y_obs = data #converts data to pytorch Tensor for gradient purposes
    y_model = convolve_sim(torch.Tensor(theta)) #evaluates model
    y_model[y_model==0] += 1e-20 #This offsets 0 counts by a slight amount (can't take the logarithm of 0)
    
    # Calculate the total variance
    sigma_tot = np.sqrt((scatter * y_model) ** 2 + np.sqrt(y_obs) ** 2)
    
    # Calculate the log-likelihood
    log_likelihood = np.sum(norm.logpdf(y_obs, loc=y_model, scale=sigma_tot))
    
    if np.isnan(log_likelihood): #if something goes wrong, e.g. there's an infinify somewhere, return invalid
        return -1e100
        
    return log_likelihood

def priors(theta):
    """
    Imposes training priors as well as physically motivated priors.
    
    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to evaluate priors of.
    
    Returns:
    --------
    True:
        Parameter set is within priors
    False:
        Parameter set is outside of priors
    """
    #make sure all sampled parameters are within prior ranges
    for i,par in enumerate(theta):
        if par < limits[i,0] or par > limits[i,1]:
            print(f"Outside bounds. {labels[i]}: {par}")
            return False
    #following priors are training boundaries
    #check for highly comptonized thick disks with high iron abundances
    if (theta[6]>2.75)&(theta[8]>4)&(theta[9]>17):
        return False
    #unrealistic inferred hubble values
    hubble = theta[5]*3e5/(theta[7]*0.001) #currently incorrect by factor 10 - using to test inferred distances
    if hubble < 30 or hubble > 300:
        return False
    #coronal geometry invalid case
    height_min = 1+ np.sqrt(1-theta[1]**2)
    if 10**theta[0] < 1.5*height_min:
        return False
    """
    #uncomment this section to add accretion luminosity as a prior - you will need xillver installed for this
    #via Pyxspec or sherpa
    L = luminosity(theta)
    if L == False:
        return False
    """
    #to do: impose physical Anorm prior to restrict luminosities.
    return True

def log_likelihood(theta):
    """
    Calculates the log likelihood of a given set of parameters
    
    
    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to calculate log likelihood of.
    
    Returns:
    --------
    log_likeli : float
        log likelihood of parameter set being the true model
    """
    #checks for parameter set to be within priors - outside of priors returns large negative log likelihood
    if priors(theta) == False:
        log_likeli = -1e300
    else:
        log_likeli = gaussian_func(theta) #evaluate the likelihood of model based on data
    return log_likeli

def convolve_sim(theta):
    """
    Calls model and convolves with response matrix in pytorch compatible manner
    
    
    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to produce model of.
    
    Returns
    -------
    pred: torch.Tensor
        convolved model for poisson evaluation
    """
    pred = simulator(theta)
    pred = resp.convolve_response(pred,"xspec")
    return pred

def simulator(theta):
    """
    Calls emulator and rescales to actual data output
    
    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to calculate model of.
    
    Returns
    -------
    pred: torch.Tensor
        rtdist model result
    """
    trim_theta = torch.Tensor(theta[:-1]).double()
    tbabs = xspec.XSTBabs()
    tbabs.nH = theta[-1]
    abso = tbabs(egrid_lo,egrid_hi)
    pred = model(trim_theta).detach().numpy()[:-1]*abso
    return pred

wrk_dir = os.getcwd()
resp = Response.ResponseMatrix(wrk_dir+"/ResponseFiles/PN.rmf")
resp.load_arf(wrk_dir+"/ResponseFiles/PN.arf")

expo_time = 260000
resp.set_exposure_time(expo_time)

saved_grid = resp.energ_lo
#resp = resp.ignore_channels(high_energy=0.1,low_energy=0)
resp.resp_matrix = resp.resp_matrix[resp.energ_lo>0.1]
resp.energ_hi = resp.energ_hi[resp.energ_lo>0.1]
resp.energ_lo = resp.energ_lo[resp.energ_lo>0.1]
resp.n_energs = len(resp.energ_lo)
e_bin_width = resp.emax-resp.emin

hdul = fits.open("data/testing/rtdist.pha")
hdu = hdul[1]
sim_obs = []
for item in hdu.data:
    sim_obs.append(item[1])
sim_obs = np.array(sim_obs)*expo_time/e_bin_width
#xspec input parameters
xspec_pars = [6,0.9,57,-2,2e4,0.024917,2.5,1e5,1,17,50.,5e-2,1e-2,3e6,0.02,0,0,0,0,0,0,-0.8,0.3,2.2e-4,1]
#neural network input parameters
nn_pars = [6,0.9,57,2,2e4,0.024917,2.5,1e5,1,17,50,1e-2,3e6,0.02,0,0,2.2e-4,5e-2]
labels = ["Height","Spin","i",r"$r_{in}$",r"$r_{out}$","z",r"$\Gamma$","Distance",r"$A_{fe}$",
          "logNe","kTe","boost","Mass","h/r","b1","b2","Anorm","nH"]

height_range      = [1.5,100]
spin_range        = [0,0.998]
inclination_range = [1,80]
r_inner_range     = [1,400]
r_outer_range     = [400,1e5]
z_range           = [0,0.1]
Gamma_range       = [1.4,3.4]
distance_range    = [1e2,1e6]
Afe_range         = [0.5,10]
logNe_range       = [15,20]
kte_range         = [5,500]
nH_range          = [0,1e6]
boost_range       = [1e-2,10]
mass_range        = [1e4,1e11]
honr_range        = [0,0.176]
b1_range          = [0,2]
b2_range          = [-4,4]
anorm_range       = [1e-4,4]

range_all = [height_range,spin_range,inclination_range,r_inner_range,
             r_outer_range,z_range,Gamma_range,distance_range,Afe_range,
             logNe_range,kte_range,boost_range,mass_range,
             honr_range,b1_range,b2_range,anorm_range,nH_range]

limits = np.asarray(range_all)

#Let's also retrieve energy grids and bin widths for plotting purposes.
emid      = (resp.emin + resp.emax)/2
bin_width = resp.energ_hi-resp.energ_lo
egrid_lo  = resp.energ_lo
egrid_hi  = resp.energ_hi
egrid = (egrid_lo+egrid_hi)/2

pois_obs  = np.random.poisson(sim_obs)
data      = pois_obs

model = RTFAST(num_models=7)
tbabs = xspec.XSTBabs()
tbabs.nH = 5e-2

raw_sim = simulator(torch.Tensor(nn_pars).double()) #non-instrument convolved result
emulator = convolve_sim(torch.Tensor(nn_pars).double()) #fully convolved result

fig, axs = plt.subplots(2,figsize=(8,8))
axs[0].plot(emid,sim_obs,label="RTDIST")
axs[0].plot(emid,emulator,label = "RTFAST")
fig.supxlabel("Energy (keV)")
axs[0].set_ylabel("Energy flux (photons/s/keV)")
axs[0].legend()
axs[0].set_xscale("log")
axs[0].set_yscale("log")
axs[0].set_ylim(1)
axs[0].set_xlim(0.1)
resids = np.abs((emulator[sim_obs!=0]-sim_obs[sim_obs!=0])/sim_obs[sim_obs!=0])
axs[1].fill_between(emid[sim_obs!=0],-0.02,0.02,color="grey",alpha=0.1)
axs[1].plot(emid[sim_obs!=0],resids)
#axs[1].axhline(0.03,ls="--")
axs[1].set_ylabel("(emulator - truth)/truth")
#axs[1].set_ylim(0.001)
#axs[1].set_yscale("log")
axs[1].set_xlim(0.1)
axs[1].set_xscale("log")
plt.tight_layout()
plt.savefig("samples/rtfast_compare.pdf")
plt.close()

plt.plot(emid,pois_obs,label="Truth")
plt.plot(emid,emulator,label = "Emulator")
plt.xlabel("Energy (keV)")
plt.ylabel("Photons")
plt.legend()
plt.xscale("log")
plt.yscale("log")
plt.ylim(1e-1)
plt.tight_layout()
plt.savefig("samples/rtfast_pois_obs.pdf")
plt.close()

gma_range = np.linspace(1.4,3.4,20)
np_nn_pars = np.asarray(nn_pars)[np.newaxis,:]
nn_pars_range = np.repeat(np_nn_pars,20,axis=0)
nn_pars_range[:,0] = 3
nn_pars_range[:,6] = gma_range
nn_pars_range[:,7] = 1e5
nn_pars_range[:,9] = 17
nn_pars_range[:,12] = 3e10
nn_pars_range[:,13] = 0.02
nn_pars_range[:,-1] = 1e-3
segs = [np.column_stack([egrid_lo[1:], 
                         ((egrid_lo[1:])**2)*simulator(torch.Tensor(par_set).double())[1:]/bin_width[:-1]]) 
        for par_set in nn_pars_range]
fig, ax = plt.subplots()
lc = matplotlib.collections.LineCollection(segs, array = gma_range,
                                           alpha = 0.8)
ax.add_collection(lc)
axcb = fig.colorbar(lc)
axcb.set_label(r"$\Gamma$")
ax.set_title(r"Colored by $\Gamma$")
ax.set_ylabel(r"Flux (keV$^2$/cm$^2$/s/keV)")
ax.set_xlabel("Energy (keV)")
ax.set_xscale("log")
ax.set_yscale("log")
ax.set_ylim(1e-4,5e-2)
ax.set_xlim(1e-1,20)
plt.savefig("samples/rtfast_gamma_range.pdf")
plt.close()

anorm_ranges = np.logspace(-4,np.log10(4),20)
np_nn_pars = np.asarray(nn_pars)[np.newaxis,:]
nn_pars_range = np.repeat(np_nn_pars,20,axis=0)
nn_pars_range[:,-1] = anorm_ranges
segs = [np.column_stack([egrid_lo[1:], 
                         ((egrid_lo[1:])**2)*simulator(torch.Tensor(par_set).double())[1:]/bin_width[:-1]]) 
        for par_set in nn_pars_range]

fig, ax = plt.subplots()
lc = matplotlib.collections.LineCollection(segs, array = anorm_ranges,
                                           alpha = 0.3)
ax.add_collection(lc)
axcb = fig.colorbar(lc)
axcb.set_label(r"$log(A_{norm})$")
ax.set_title(r"Colored by log($A_{norm}$)")
ax.set_ylabel(r"keV$^2$/cm$^2$/s/keV")
ax.set_xlabel("Energy (keV)")
ax.set_xscale("log")
ax.set_yscale("log")
ax.set_ylim(1e-3)
ax.set_xlim(1e-1,20)
plt.savefig("samples/rtfast_anorm_range.pdf")
plt.close()

def ptform(u):
    """
    Reduced priors to realistic ranges.
    """
    height_range = [1.5,20]
    spin_range = [0.1,0.998]
    inclination_range = [30,80]
    r_inner_range = [1,50]
    r_outer_range = [400,1e5]
    z_range = [0.01,0.03]
    Gamma_range = [2,3]
    distance_range = [np.log10(1e4),np.log10(1e6)]
    Afe_range = [0.5,3]
    logNe_range = [15,17]
    kte_range = [5,100]
    boost_range = [1e-2,5]
    mass_range = [1e5,1e7]
    honr_range = [0,0.1]
    b1_range = [0,0.2]
    b2_range = [-1,1]
    anorm_range = [np.log10(1e-4),np.log10(1e-2)]
    nH_range = [np.log10(1e-2),np.log10(1)]

    range_all = [height_range,spin_range,inclination_range,r_inner_range,
                 Gamma_range,distance_range,Afe_range,
                 logNe_range,boost_range,
                 honr_range,b1_range,b2_range,anorm_range,nH_range]
    powers = [5,12,13]
    """
    range_all = [height_range,spin_range,inclination_range,r_inner_range,
                 r_outer_range,z_range,Gamma_range,distance_range,Afe_range,
                 logNe_range,kte_range,boost_range,mass_range,
                 honr_range,b1_range,b2_range,anorm_range,nH_range]
    powers = [7,16,17]
    """
    
    #range_all = [spin_range,Gamma_range,anorm_range]
    #powers = [2]
    
    for i,lims in enumerate(range_all):
        u[i] = u[i]*(lims[1]-lims[0]) + lims[0]
        if i in powers:
            u[i] = 10**u[i]
    return u
    
def insert_fixed_pars(theta):
    """
    If you are fixing certain parameters, insert them here.
    """
    #theta = np.insert(theta,0,nn_pars[0]) #fixed height
    #theta = np.insert(theta,1,nn_pars[1]) #fixed spin
    #theta = np.insert(theta,2,nn_pars[2]) #fixed inclination
    #theta = np.insert(theta,3,nn_pars[3]) #fixed inner radius
    theta = np.insert(theta,4,nn_pars[4]) #fixed outer radius
    theta = np.insert(theta,5,nn_pars[5]) #fixed z
    #theta = np.insert(theta,6,nn_pars[6]) #fixed gamma
    #theta = np.insert(theta,7,nn_pars[7]) #fixed distance
    #theta = np.insert(theta,8,nn_pars[8]) #fixed afe
    #theta = np.insert(theta,9,nn_pars[9]) #fixed logNe
    theta = np.insert(theta,10,nn_pars[10]) #fixed kte
    #theta = np.insert(theta,11,nn_pars[11]) #fixed boost
    theta = np.insert(theta,12,nn_pars[12]) #fixed mass
    #theta = np.insert(theta,13,nn_pars[13]) #fixed h/r
    #theta = np.insert(theta,14,nn_pars[14]) #fixed b1
    #theta = np.insert(theta,15,nn_pars[15]) #fixed b2
    #theta = np.insert(theta,19,nn_pars[16]) #fixed anorm
    #theta = np.insert(theta,20,nn_pars[17]) #fixed nH
    return theta

def log_likelihood_fixed(theta):
    """
    Calculates the log likelihood of a given set of parameters
    
    
    Parameters:
    -----------
    theta: np.ndarray
        Set of parameters to calculate log likelihood of.
    
    Returns:
    --------
    log_likeli : float
        log likelihood of parameter set being the true model
    """
    theta = insert_fixed_pars(theta)
    #checks for parameter set to be within priors - outside of priors returns large negative log likelihood
    if priors(theta) == False:
        log_likeli = -1e300
    else:
        log_likeli = gaussian_func(theta) #evaluate the poisson likelihood of model based on data
    return log_likeli

def convolve_sim_fixed(theta):
    """
    Convolves RTFAST's output with the response matrix
    """
    theta = insert_fixed_pars(theta)
    pred = simulator(theta)
    pred = resp.convolve_response(pred,"xspec")
    return pred

ndim=18
sampler = dynesty.NestedSampler(log_likelihood_fixed, ptform, ndim, nlive=500,bound="multi")
sampler.run_nested()
sresults = sampler.results

# Extract sampling results.
samples = sresults.samples  # samples
weights = sresults.importance_weights()

# Compute 10%-90% quantiles.
quantiles = [dyfunc.quantile(samps, [0.1, 0.9], weights=weights)
             for samps in samples.T]

# Compute weighted mean and covariance.
mean, cov = dyfunc.mean_and_cov(samples, weights)

# Resample weighted samples.
samples_equal = sresults.samples_equal()

# Generate a new set of results with sampling uncertainties.
results_sim = dyfunc.resample_run(sresults)

new_results = copy.deepcopy(sresults)
nn_pars_indices = [0,1,3,7,9,19]
nn_pars_indices_full = [1,6,16]
nn_pars_true = np.asarray(nn_pars)
labels_plots = np.delete(labels,[])

fig, axes = dyplot.runplot(sresults)
plt.savefig("fitting/run_plot.pdf")
plt.close()

cfig, caxes = dyplot.cornerplot(new_results,truths=nn_pars_true,labels=labels_plots,
                                show_titles=True,title_fmt = ".2e")
plt.savefig("fitting/corner_plot.pdf")
plt.close()

cfig, caxes = dyplot.cornerpoints(new_results,truths=nn_pars_true,labels=labels_plots)
plt.savefig("fitting/corner_points.pdf")
plt.close()

log_likelihoods = sresults.logl
sorted_indices = np.argsort(log_likelihoods)[::-1]  # Sort in descending order
sorted_samples = samples_equal[sorted_indices]
sorted_log_likelihoods = log_likelihoods[sorted_indices]

# Select the top n samples
n_top_samples = 20000  # For example, select the top 100 samples
top_samples = sorted_samples[:n_top_samples]
top_log_likelihoods = sorted_log_likelihoods[:n_top_samples]

height_range = [1.5,10]
spin_range = [0.1,0.998]
inclination_range = [1,40]
r_inner_range = [1,400]
r_outer_range = [400,1e5]
z_range = [0.01,0.03]
Gamma_range = [2,3]
distance_range = [np.log10(1e2),np.log10(1e6)]
Afe_range = [1,3]
logNe_range = [15,17]
kte_range = [5,200]
boost_range = [1e-2,5]
mass_range = [1e5,1e7]
honr_range = [0,0.1]
b1_range = [0,0.2]
b2_range = [-1,1]
anorm_range = [np.log10(1e-4),np.log10(1e-2)]
nH_range = [np.log10(1e-2),np.log10(1)]
ranges = np.array([height_range,spin_range,inclination_range,r_inner_range,
                 r_outer_range,z_range,Gamma_range,distance_range,Afe_range,
                 logNe_range,kte_range,boost_range,mass_range,
                 honr_range,b1_range,b2_range,anorm_range,nH_range])
new_samples = samples_equal
new_samples[:,[7,-1,-2]] = np.log10(new_samples[:,[7,-1,-2]])

nn_pars_true_logged = nn_pars_true
nn_pars_true_logged[[7,-1,-2]] = np.log10(nn_pars_true_logged[[7,-1,-2]])

fig = corner.corner(
    new_samples,
    labels=labels_plots,  # Parameter names
    truths=nn_pars_true,  # True values (if known)
    title_fmt=".2f"  # Format of the titles
)
plt.savefig("fitting/corner_manual.pdf")
plt.close()

fig, axs = plt.subplots(3,sharex=True,figsize=(10,10))
inds = np.random.randint(0,top_samples.shape[0],size=500)
model_draws = []
for ind in inds:
    sample = top_samples[ind]
    model_eval = convolve_sim_fixed(sample)
    model_draws.append(model_eval)
    axs[0].plot(emid, emid*model_eval, "C1", alpha=0.1,zorder=2)
    axs[1].plot(emid, model_eval, "C1", alpha=0.1,zorder=2)
model_draws = np.asarray(model_draws)
axs[0].plot(emid,emid*np.mean(model_draws,axis=0),"r",label="Mean model",zorder=3)
axs[0].errorbar(emid, emid*pois_obs,yerr=emid*np.sqrt(pois_obs), label="observation",color="black",lw=1,zorder=1)
axs[1].plot(emid,np.mean(model_draws,axis=0),"r",label="Mean model",zorder=3)
axs[1].errorbar(emid,pois_obs,yerr=np.sqrt(pois_obs), label="observation",color="black",lw=1,zorder=1)

axs[0].legend(fontsize=14)
fig.supxlabel("Energy/KeV")
axs[0].set_ylabel(r"Flux (KeV/cm$^2$/s")
axs[0].set_xscale("log")
axs[0].set_yscale("log")
axs[0].set_ylim(1)
axs[1].legend(fontsize=14)
axs[1].set_xscale("log")
axs[1].set_yscale("log")
axs[1].set_ylim(1)
axs[2].scatter(emid,(pois_obs-np.mean(model_draws,axis=0))/np.sqrt(pois_obs),s=1,marker="+")
axs[2].set_ylabel("(data-mean(model))/(error)")
#axs[2].set_yscale("symlog")
plt.tight_layout()
plt.savefig("fitting/realisations.pdf")
plt.close()