"""
This program simulates a test case and attempts a simple MCMC fit using the
emcee package and the emulator.
"""

import emcee
import numpy as np
from generator import rtdist_flux
from sherpa.astro.ui import unpack_rmf
import torch
import os

def emulator(theta):
    """
    The function calls the emulator and returns the predicted spectra.

    Parameters
    ----------
    theta : np.ndarray
        model parameters.

    Returns
    -------
    model : np.ndarray
        Model spectra for the provided parameters.

    """
    
def log_likelihood(theta, data):
    """
    

    Parameters
    ----------
    data : numpy array
        a series of float data points that should be a counts from a spectra 
        generated by XSPEC or actual data.
    theta : numpy array
        model parameters.

    Returns
    -------
    summation : float
        likelihood probability that the proposed model is correct based on the
        data inputted (x).

    """
    model = emulator(theta)
    x = data
    l = model
    l[l==0] += 1e-20 #model can't have 0 counts in poisson likelihoods
    #There are 3 terms in a log poisson likelihood: x*log(l) - l - sum{log(x!)}
    first = x*np.log(l) #first term
    thirds = np.zeros(x.shape) #third term
    for i,d in enumerate(x):
        fact = np.arange(1,d,step=1)
        thirds[i] = np.sum(np.log(fact))
    poissons = first - l - thirds #poisson likelihoods per data point
    summation = np.sum(poissons) #sum poisson likelihoods for whole spectra
    return summation

from scipy.optimize import minimize

a_true = 0.9
inc_true = np.log10(57)
inner_r_true = np.log10(-1*-1)
mass_true = np.log10(3e6)
distance_true = np.log10(1e5)

rmf_name = wrk_dir = os.getcwd()+"/ResponseFiles/PN.rmf"
rmf = unpack_rmf(rmf_name)
egrid = rmf.e_min #energy grid used to evaluate the xspec model

pars = [6,0.9,57,-1,2e4,0.024917,2.45,1e5,1,17,50.,5,1,3e6,0.02,0,0,0,
             0,0,0,-0.8,0.3,2.2e-4,1,1.]

data = rtdist_flux(pars, egrid)

np.random.seed(42)
nll = lambda *args: -log_likelihood(*args)
initial = np.array([a_true, inc_true, inner_r_true,distance_true,mass_true]) + 0.1 * np.random.randn(5)
soln = minimize(nll, initial, args=(data))
m_ml, b_ml, log_f_ml = soln.x