"""
This is the main program that trains the neural network.
"""
import numpy as np
import os, psutil
import sys
from tqdm import tqdm
import time

from sherpa.astro.ui import unpack_rmf
import torch
from torch import nn
from torch.utils.data import DataLoader,Dataset
from torch.optim import Adam
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from joblib import dump, load, Parallel, delayed
import scipy.stats

import generator
import network
    
class CustomData(Dataset):
    """
    A class that inherits from torch.Dataset that returns both the data from
    the model evaluation and the parameters used to generate the model.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self,pars,data,scaler,scaling=True, scaler_name = "active_scaler"):
        super().__init__()
        self.par_list = torch.Tensor(pars)
        self.data = torch.Tensor(data)
        self.scaler = scaler
        self.scaling = scaling
        self.scaler_name = scaler_name
        self.standardize()
    
    def __len__(self):
        return self.data.size()[0]
    
    def __getitem__(self,idx):
        datum = self.data[idx]
        parameters = self.par_list[idx]
        if self.mask is not None:
            mask = self.mask[idx]
            return datum, parameters, mask
        else:
            return datum, parameters
    
    def standardize(self):
        """
        Filters 0 flux and converts to smallest non-zero value. Then standard
        scales the energy bins.
        """
        D = self.data
        self.mask = np.where(self.data <= 1e-38, 0, 1)
        D[D<=1e-38] = 1e-38
        D = torch.log10(D)
        #Change NaNs to minimum non flux (essentially neglible)
        D_np = D.numpy()
        D_np = self.scale(D_np)
        D = torch.from_numpy(D_np)
        D = D.double()
        self.data = D
        
    def scale(self,data):
        """
        Standard scales the logarithm spaced data by energy bin and saves the
        standard scaler for future use.

        Parameters
        ----------
        data : np.ndarray
            Array of spectra in the logspace.

        Returns
        -------
        scaled_data : np.ndarray
            Scaled array of spectra in the logspace.

        """
        scaler = self.scaler
        if self.scaling == True:
            scaled_data = scaler.fit_transform(data)
            dump(scaler, f'scalers/{self.scaler_name}.bin', compress=True)
        else:
            scaler = load(f'scalers/{self.scaler_name}.bin')
            scaled_data = scaler.transform(data)
        return scaled_data

def saveData(data,pars,fname = ""):
    """
    Saves the data and parameters to disk.

    Parameters
    ----------
    data : np.ndarray
        An array of all data generated by the model to save.
    pars : np.ndarray
        An array of all parameters used to generate the data to save.

    Returns
    -------
    None.

    """
    if fname == "":
        data = np.asarray(data)
        pars = np.asarray(pars)
        with open("data/data.txt","w") as f:
            np.savetxt(f,data)
        f.close()
        with open("data/pars.txt","w") as f:
            np.savetxt(f,pars)
        f.close()
        return
    else:
        data = np.asarray(data)
        pars = np.asarray(pars)
        with open(f"data/{fname}data.txt","w") as f:
            np.savetxt(f,data)
        f.close()
        with open(f"data/{fname}pars.txt","w") as f:
            np.savetxt(f,pars)
        f.close()
        return

def saveLoop(model,data,pars,te_loss,tr_loss,num,epochs):
    print("Saving loop")
    saveData(data, generator.pars_conversion(pars),
              fname = f"loop_{num}_")
    print("Saved data")
    torch.save(model.state_dict(), f"models/{num}_model.pth")
    print("Saved model")
    np.savetxt(f"loss/{num}_te_loss.txt",te_loss)
    np.savetxt(f"loss/{num}_tr_loss.txt",tr_loss)
    np.savetxt(f"loss/{num}_epochs.txt",epochs)
    print("Saved losses")
    return
    
def train(dataloader,model,optimizer,loss_fn,device):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the training dataset.
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : torch.optim
        optimizer used for training the network.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : Ttorch.optim
        optimizer used for training the network.
    avg_loss : float
        used as to record and determine how many iterations should be trained.

    """
    
    model.train()
    
    size = len(dataloader.dataset)
    batch_size = 1024
    loss_arr = 0
    big_loss = 0
    for batch, (D,P,M) in enumerate(dataloader):
        pred = model(P.to(device))
        loss = loss_fn(pred,D.to(device),M.to(device))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss_b, current = loss.detach().item(), (batch*batch_size + 1)
        if batch % 5 == 0:
            print(f"loss: {loss_b:>7f}  [{current:>5d}/{size:>5d}]")
        if loss_b > 100:
            print(f"Extremely large batch loss of {loss_b:.2E}")
            big_loss += 1
        loss_arr += loss_b
    
    avg_loss = loss_arr/len(dataloader)
    print(f"Average training loss: {avg_loss:>8f}")
    if big_loss != 0:
        print(f"There were {big_loss} batches with very large loss.")
    return model, optimizer , avg_loss

def test(dataloader,model,loss_fn,device,improvement_set = []):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the testing dataset.
    model : network.NeuralNetwork
        the neural network model to be tested.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    test_loss : float
        used as to record and determine how many iterations should be trained.

    """
    model.eval()
    test_loss = 0
    batches = len(dataloader)
    
    with torch.no_grad():
        for batch, (D,P,M) in enumerate(dataloader):
            pred = model(P.to(device))
            test_loss += loss_fn(pred, D.to(device), M.to(device)).detach().item()
    test_loss /= batches
    
    if improvement_set != []:
        improvement_loss = 0
        imp_batches = len(improvement_set)
        with torch.no_grad():
            for batch, (D, P, M) in enumerate(improvement_set):
                pred = model(P.to(device))
                improvement_loss += loss_fn(pred, D.to(device), M.to(device)).detach().item()
        improvement_loss /= imp_batches
        print(f"Average testing loss: {test_loss:>8f}")
        print(f"Average improvement loss: {improvement_loss:>8f}")
        return test_loss, improvement_loss
    else:
        print(f"Average testing loss: {test_loss:>8f}")
        return test_loss

def nanChecker(data,pars):
    index = []
    for i,spec in enumerate(data):
        if np.any(np.isnan(spec)) == True:
            index.append(i)
    if index != []:
        print("Found bad models, printing parameters...")
        for indice in index:
            print(f"{indice}: {pars[indice]}")
        data = np.delete(data,index, axis=0)
        pars = np.delete(pars,index, axis=0)
    return data, pars

def maskedMSELoss(pred,data,mask):
    data = torch.mul(data,mask)
    pred = torch.mul(pred,mask)
    loss = nn.MSELoss()
    result = loss(pred,data)
    return result

def queryByDropout(wrk_dir, device = None):
    print("Training using query by dropout committee")
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    
    active_loops = 20
    range_all = np.asarray(generator.lhs_trimmed_gen())
    n_samples = 1000
    n_samples_large = 10000 # number of parameter sets to draw 
    divider = 10
    n_samples_small = int(n_samples_large/divider)
    
    #pre generate Latin Hypercube samples.
    sampler = scipy.stats.qmc.LatinHypercube(d=len(range_all))
    sample = sampler.random(n=1000000)
    theta_lhs = scipy.stats.qmc.scale(sample, range_all[:,0], range_all[:,1])
    
    #if the first time running this code or you want to refresh the dataset, 
    #make this true
    first = True
    
    model = network.NeuralNetwork(5,len(egrid))
    model.to(device)
    best_model = network.NeuralNetwork(5,len(egrid))
    best_model.to(device)
    optimizer = Adam(model.parameters(),lr = 0.001)
    loss_fn = maskedMSELoss
    scaler = MinMaxScaler()
    
    if first == True: 
        print("Generating first time dataset")
        init_data_size = 5000
        #generating a random set of parameters and corresponding data
        theta_init = np.random.uniform(range_all[:,0],range_all[:,1],
                                       size = (init_data_size,range_all.shape[0]))
        pars_init = generator.pars_conversion(theta_init)
        print("Parallelized model generation")
        data_init =  Parallel(n_jobs=8)(delayed(generator.rtdist_flux)(pars, egrid)
                                        for pars in pars_init)
        data_init = np.array(data_init)
        data_init, theta_init = nanChecker(data_init, theta_init)
        pars_init = generator.pars_conversion(theta_init)
        #save data for the first time in text files
        np.savetxt("data/data.txt",data_init)
        np.savetxt("data/pars.txt",pars_init)
        
        last_sig_best_tr = 1e7 #last significant best training loss (set large initially)
        last_sig_best_te = 1e7 #last significant best testing loss (set large initially)
        last_sig_best_imp = 1e7 #last significant best large test set loss (set large initially)
        tr_loss_arr = []
        te_loss_arr = []
        loop_epochs = []
        
        active_loop_num = 0
        
        #create initial dataset object to create scaler (and then delete object)
        data_init_dataset = CustomData(theta_init, data_init, scaler)
        del data_init_dataset
        
    else: #load previously generated data as initial data and parameter set
        print("Loading previous data")
        with open(f"data/data.txt","r") as f1:
            data = np.loadtxt(f1)
        f1.close()
        
        with open(f"data/pars.txt","r") as f2:
            pars = np.loadtxt(f2)
        f2.close()
        
        #make mass log spaced to improve numeric stability in training
        pars[:,13] = np.log10(pars[:,13]) 
        pars[:,2] = pars[:,2]
        pars[:,3] = pars[:,3]
        pars[:,4] = np.log10(pars[:,4])
        pars = pars[:,[1,13,2,3,4]] #retrieve spin and mass
        
        data_init = data
        theta_init = pars
        data_init, theta_init = nanChecker(data_init, theta_init)
        del data
        del pars
        
        last_sig_best_tr = 1e7 #last significant best training loss (set large initially)
        last_sig_best_te = 1e7 #last significant best testing loss (set large initially)
        last_sig_best_imp = 1e7 #last significant best large test set loss (set large initially)
        tr_loss_arr = []
        te_loss_arr = []
        loop_epochs = []
        
        active_loop_num = 0
        
        #create initial dataset object to create scaler (and then delete object)
        data_init_dataset = CustomData(theta_init, data_init, scaler)
        del data_init_dataset
        
    batch_size = 1024
    num_workers = 4
    
    lhs_idx = theta_init.shape[0]
    
    with open(f"data/test_data.txt","r") as f1:
        test_data = np.loadtxt(f1)
    f1.close()
    
    with open(f"data/test_pars.txt","r") as f1:
        test_pars = np.loadtxt(f1)
    f1.close()
    
    test_pars[:,13] = np.log10(test_pars[:,13]) 
    test_pars[:,2] = test_pars[:,2]
    test_pars[:,3] = test_pars[:,3]
    test_pars[:,4] = np.log10(test_pars[:,4])
    test_pars = test_pars[:,[1,13,2,3,4]] #retrieve parameters
    
    test_set = CustomData(test_pars, test_data, scaler, 
                        scaling=False)
    print("Query data set created")
    improvement_dataloader = DataLoader(test_set, batch_size=batch_size, 
                                        num_workers = num_workers, shuffle=True)
    
    print("Beginning training")
    
    while active_loop_num < active_loops:
        #set improvements counters to 0
        imp_te = 0
        imp_tr = 0
        print(f"I am in active learning loop {active_loop_num+1}")
        # randomly generate points in parameter space
        print("Generating random samples of theta")
        theta_query_large = theta_lhs[lhs_idx : lhs_idx+n_samples_large]
        
        print("computing neural network predictions with dropout for each theta")
        # compute 100 neural network predictions with dropout
        pred_query_all = np.zeros((100,n_samples_small,len(egrid)))
        model.train()
        query_idx = []
        
        for j in tqdm(range(divider),desc="Sample dropout loops"):
            theta_query_small = theta_query_large[j*n_samples_small:(j+1)*n_samples_small]
            for i in range(100):
                pred_query = model(torch.DoubleTensor(theta_query_small).to(device))
                pred_query_all[i] = pred_query.detach().cpu().numpy()
            # find uncertainty (as measured by relative variance)
            dvar = pred_query_all / np.array([np.var(pred_query_all, axis=-1).T, ]).T
            var_query = np.var(dvar, axis=0)
            mean_var_query = np.mean(var_query, axis=1)
            # add to uncertainties per theta to list
            query_idx.append(mean_var_query.tolist())
        
        #Performing manual memory cleanup
        del pred_query, pred_query_all, dvar, var_query, mean_var_query
        del theta_query_small
        print("Successfully finished generating thetas")
        
        print("Finding top uncertain thetas")
        # sort these thetas from largest uncertainty (as measured by 
        # relative variance) to smallest
        query_idx = np.asarray(query_idx).flatten()
        query_idx = np.argsort(query_idx)[::-1]
        
        print("Generating data for these samples")
        # get out the top `nsamples` values of theta_query
        theta_query = theta_query_large[query_idx[:n_samples]]
        
        # compute the physical model for these thetas
        data_query = np.zeros((theta_query.shape[0],len(egrid)))
        theta_query_iterate = generator.pars_conversion(theta_query)
        print("Parallelized model generation")
        data_query =  Parallel(n_jobs=8)(delayed(generator.rtdist_flux)(pars, egrid)
                                        for pars in theta_query_iterate)
        data_query = np.asarray(data_query)
        del theta_query_iterate
        # shuffle indices for neural network training
        idx_shuffle = np.arange(0, len(theta_query), dtype=int)
        np.random.shuffle(idx_shuffle)
    
        idx_query = idx_shuffle[:len(idx_shuffle)-500]
        idx_test = idx_shuffle[-500:]
        
        #Split data and thetas into test and training data
        data_test = data_query[idx_test]
        theta_test  = theta_query[idx_test]
        
        data_query = data_query[idx_query]
        theta_query = theta_query[idx_query]
        
        # add corresponding models to the rest of the training data
        data_init = np.vstack([data_init, data_query])
        # add thetas to the rest of the training data
        theta_init = np.vstack([theta_init, theta_query])
        
        del data_query, theta_query
        
        #Eliminate any broken models
        data_init, theta_init = nanChecker(data_init, theta_init)
        data_test, theta_test = nanChecker(data_test, theta_test)
        
        # add rejected parameter sets back to original array for potential 
        # future use:
        theta_lhs = np.vstack([theta_lhs, theta_query_large[query_idx[n_samples:]]])
    
        print(f"size of theta_init: {theta_init.shape}")
        print(f"size of data_init: {data_init.shape}")
        
        # increment the index for reading parameters from theta_lhs
        lhs_idx += (n_samples_large)

        print("Setting up modeling")
        Xquery = CustomData(theta_init, data_init, scaler, 
                            scaling=False)
        print("Query data set created")
        query_dataloader = DataLoader(Xquery, batch_size=batch_size, 
                                      num_workers = num_workers, shuffle=True)
        print("Query data loader created")
    
        Xtest = CustomData(theta_test, data_test, scaler,
                           scaling=False)
        print("Test data set created")
        test_dataloader = DataLoader(Xtest, batch_size=batch_size,
                                     num_workers = num_workers, shuffle=True)
        print("Test data loader created")
        
        # add test models to the rest of the training data for use in training
        #in the future
        data_init = np.vstack([data_init, data_test])
        # add corresponding thetas thetas to the rest of the training data
        theta_init = np.vstack([theta_init, theta_test])
        
        print("Saving new data to disk")
        # save new data and parameters to disk
        saveData(data_init, generator.pars_conversion(theta_init))
        
        epoch = 0
        while (imp_te < 5 or imp_tr < 5):
            print(f"Epoch {epoch+1} \n -----------------------")
            model, optimizer, train_loss = train(query_dataloader,model,
                                                 optimizer,loss_fn,device)
            loss,improv_loss = test(test_dataloader,model,loss_fn,device,
                                    improvement_dataloader)
            te_loss_arr.append(loss)
            tr_loss_arr.append(train_loss)
            tr_bet = (0.9*last_sig_best_tr) - train_loss
            te_bet = (0.9*last_sig_best_te) - loss
            imp_bet = (0.9*last_sig_best_imp) - improv_loss
            if tr_bet > 0 and te_bet > 0:
                last_sig_best_tr = train_loss
                last_sig_best_te = loss
                imp_te = 0
                imp_tr = 0
                print(f"New best training loss: {train_loss}")
                print(f"New best testing loss: {loss}")
            elif tr_bet > 0:
                imp_tr = 0
                imp_te += 1
                last_sig_best_tr = train_loss
                print(f"New best training loss: {train_loss}")
            elif te_bet > 0:
                imp_tr += 1
                imp_te = 0
                last_sig_best_te = loss
                print(f"New best testing loss: {loss}")
            else:
                imp_te += 1
                imp_tr += 1
            if imp_bet > 0:
                last_sig_best_imp = improv_loss
                print("Current best performer on true test set, saving...")
                torch.save(model.state_dict(), "models/active_best.pth")
            epoch += 1
        if active_loop_num != 0:
            loop_epochs.append(loop_epochs[active_loop_num-1]+epoch)
        else:
            loop_epochs.append(epoch)
        
        #save state of models and data if loop is a multiple of 5, first 5
        #loops or the final loop.
        if ((active_loop_num % 5) == 0 or active_loop_num < 5 
            or active_loop_num == (active_loops - 1)):
            temp_te = np.asarray(te_loss_arr)
            temp_tr = np.asarray(tr_loss_arr)
            temp_epochs = np.asarray(loop_epochs)
            try:
                best_model.load_state_dict(torch.load("models/active_best.pth"))
            except:
                best_model.load_state_dict(model.state_dict())
            saveLoop(best_model, data_init, theta_init, temp_te, temp_tr, 
                     active_loop_num, temp_epochs)
        #iterate loop number by 1
        active_loop_num += 1
        
    print("Completed training")
    print("Final best training loss:", last_sig_best_tr)
    print("Final best testing loss:", last_sig_best_te)
    torch.save(model.state_dict(), "models/active_final.pth")
    print("Saved PyTorch Model State to models/active_final.pth")
    
    tr_loss_arr = np.asarray(tr_loss_arr)
    te_loss_arr = np.asarray(te_loss_arr)
    
    np.savetxt("loss/active_te_loss.txt",te_loss_arr)
    np.savetxt("loss/active_tr_loss.txt",tr_loss_arr)
    np.savetxt("loss/active_epochs.txt",loop_epochs)

def grid_data_gen(size,fname,egrid):
    
    spin = np.linspace(0.1,1.0,size)
    mass = np.linspace(np.log10(3.3),np.log10(1e11),size)
    inc = np.linspace(1,80,size)
    r_in = np.linspace(-400,-1,size)
    r_out = np.linspace(np.log10(400),np.log10(1e5),size)
    
    #create parameter grid
    theta_init = []
    for a in spin:
        for m in mass:
            for i in inc:
                for r_i in r_in:
                    for r_o in r_out:
                        theta_init.append([a,m,i,r_i,r_o])
    theta_init = np.asarray(theta_init)
    #convert to rtdist model compatible parameters
    pars_init = generator.pars_conversion(theta_init)
    
    #generate rtdist models for the correlated grid
    data_init = np.zeros((theta_init.shape[0],len(egrid)))
    for i,pars in enumerate(tqdm(pars_init,desc="Generating models")):
        data_init[i] = generator.rtdist_flux(pars, egrid)
    data_init = np.array(data_init)
    data_init, pars_init = nanChecker(data_init, pars_init)
    
    print("Saving to disk")
    #save data for the first time in text files
    np.savetxt(f"data/grid_{fname}_data.txt",data_init)
    np.savetxt(f"data/grid_{fname}_pars.txt",pars_init)
    return data_init, theta_init

def grid(wrk_dir):
    print("Training using grid")
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    
    grid_sizes = [70,100,120,140,225,275,320,400,450]
    
    for i, size in enumerate(grid_sizes):
    
        fname = str(size)
        print(f"Starting {size} x {size} grid loop")
        
        data_init, theta_init = grid_data_gen(size, fname, egrid)
        print("Grid generated")
            
        scaler = MinMaxScaler()
        if i == 0:
            #create initial dataset object to create scaler (and then delete object)
            data_init_dataset = CustomData(theta_init, data_init, scaler, 
                                           scaling = True, 
                                           scaler_name="grid_scaler")
            del data_init_dataset
        
        batch_size = 12
        
        #split dataset indexes randomly into 90% training, 10% test
        idxs = np.arange(0,data_init.shape[0])
        np.random.shuffle(idxs)
        tra_idx = idxs[:int(len(idxs)-0.1*len(idxs))]
        tes_idx = idxs[int(-0.1*len(idxs)):]
        
        #Splitting data and parameters into training and testing datasets
        train_data = data_init[tra_idx]
        train_pars = theta_init[tra_idx]
        test_data = data_init[tes_idx]
        test_pars = theta_init[tes_idx]
        
        
        training_dataset = CustomData(train_pars, train_data, scaler, 
                                      scaling = False, scaler_name="grid_scaler")
        testing_dataset = CustomData(test_pars, test_data, scaler, 
                                     scaling = False, scaler_name="grid_scaler")
        print("Datasets created")
        training_dataloader = DataLoader(training_dataset, batch_size=batch_size, 
                                         shuffle=True)
        test_dataloader = DataLoader(testing_dataset, batch_size=batch_size, 
                                     shuffle=True)
        print("Dataloaders created")
        
        model = network.NeuralNetwork(5,len(egrid))
        optimizer = Adam(model.parameters(),lr = 0.001)
        loss_fn = nn.MSELoss()
        
        last_sig_best_tr = 1e7 #last significant best training loss (set large initially)
        last_sig_best_te = 1e7 #last significant best testing loss (set large initially)
        tr_loss_arr = []
        te_loss_arr = []
        
        epoch = 0
        imp_te = 0
        imp_tr = 0
        
        print("Beginning training")
        while (imp_te < 5 or imp_tr < 5):
            print(f"Epoch {epoch+1} \n -----------------------")
            model, optimizer, train_loss = train(training_dataloader,model,
                                                 optimizer,loss_fn)
            loss = test(test_dataloader,model,loss_fn)
            te_loss_arr.append(loss)
            tr_loss_arr.append(train_loss)
            tr_bet = (0.9*last_sig_best_tr) - train_loss
            te_bet = (0.9*last_sig_best_te) - loss
            if tr_bet > 0 and te_bet > 0:
                last_sig_best_tr = train_loss
                last_sig_best_te = loss
                imp_te = 0
                imp_tr = 0
                print(f"New best training loss: {train_loss}")
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), f"models/grid_{fname}.pth")
            elif tr_bet > 0:
                imp_tr = 0
                imp_te += 1
                last_sig_best_tr = train_loss
                print(f"New best training loss: {train_loss}")
            elif te_bet > 0:
                imp_tr += 1
                imp_te = 0
                last_sig_best_te = loss
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), f"models/grid_{fname}.pth")
            else:
                imp_te += 1
                imp_tr += 1
            epoch += 1
        
        print("Completed training")
        print("Final best training loss:", last_sig_best_tr)
        print("Final best testing loss:", last_sig_best_te)
        torch.save(model.state_dict(), f"models/grid_{fname}_final.pth")
        print(f"Saved PyTorch Model State to grid_{fname}_final.pth")
        
        tr_loss_arr = np.asarray(tr_loss_arr)
        te_loss_arr = np.asarray(te_loss_arr)
        
        np.savetxt(f"loss/grid_{fname}_te_loss.txt",te_loss_arr)
        np.savetxt(f"loss/grid_{fname}_tr_loss.txt",tr_loss_arr)
        
def main():
    torch.set_default_dtype(torch.double)
    
    wrk_dir = os.getcwd()
    
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}
    
    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")
    
    print(torch.cuda.is_available())
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    
    queryByDropout(wrk_dir,device)
    #grid(wrk_dir)

if __name__ == "__main__":
    main()