"""
This is the main program that trains the neural network.
"""
import numpy as np
import os
from tqdm import tqdm
import pandas as pd
from math import ceil
import matplotlib.pyplot as plt

from sherpa.astro.ui import unpack_rmf
import torch
from torch import nn
from torch.utils.data import DataLoader,Dataset
from torch.optim import Adam
from sklearn.preprocessing import MinMaxScaler
from joblib import dump, load, Parallel, delayed
import scipy.stats

from processing import nanChecker, saveLoop, saveData, mergeSaveData,renameData
import generator
import network
    
class CustomData(Dataset):
    """
    A class that inherits from torch.Dataset that returns both the data from
    the model evaluation and the parameters used to generate the model.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self,labels, scaler, scaler_name, scaling=False):
        super().__init__()
        self.labels = pd.read_csv(labels)
        self.pars_list = [2,14,3,4,5]
        self.scaling = scaling
        self.scaler_name = scaler_name
        if scaling == True:
            print(f"Creating scaler with name {scaler_name}")
            self.scaler = scaler
            self.scaler_create()
        else:
            self.scaler = load(f'scalers/{self.scaler_name}')
    
    def __len__(self):
        return len(self.labels)
    
    def __getitem__(self,idx):
        #retrieve location of the spectra to load
        location = self.labels.iloc[idx,27]
        #retrieve parameters used to generate the spectra that we want to train on
        parameters = self.labels.iloc[idx,self.pars_list].astype(float)
        #convert parameters to log space
        parameters.iloc[[1,4]] = np.log10(parameters.iloc[[1,4]])
        parameters = torch.tensor(parameters)
        #load spectra
        datum = np.loadtxt(location).reshape(1, -1)
        #create a mask for loss calculation later
        try:
            mask = np.where(datum <= 1e-38, 0, 1)
        except:
            mask = None
        #scale spectra by energy bin to normalized space
        datum = self.standardize(datum)
        if mask is not None:
            return datum, parameters, mask
        else:
            return datum, parameters
    
    def standardize(self,D):
        """
        Filters 0 flux and converts to smallest non-zero value. Then standard
        scales the energy bins.
        """
        D[D<=1e-38] = 1e-38
        D = np.log10(D)
        D = self.scale(D)
        D = torch.from_numpy(D)
        D = D.double()
        return D
    
    def scaler_create(self):
        """
        Creates and loads the scaler for the dataset.

        Returns
        -------
        None.

        """
        data = []
        for file in self.labels.iloc[:,27]:
            data.append(np.loadtxt(file).reshape(1, -1))
        final_dataset = np.concatenate(data,axis=0)
        final_dataset[final_dataset<=1e-38] = 1e-38
        final_dataset = np.log10(final_dataset)
        data = self.scaler.fit_transform(final_dataset)
        dump(self.scaler, f'scalers/{self.scaler_name}', compress=True)
        return
    
    def scale(self,data):
        """
        Standard scales the logarithm spaced data by energy bin and saves the
        standard scaler for future use.

        Parameters
        ----------
        data : np.ndarray
            Array of spectra in the logspace.

        Returns
        -------
        scaled_data : np.ndarray
            Scaled array of spectra in the logspace.

        """
        scaled_data = self.scaler.transform(data)
        return scaled_data

def distributions(data,labels,fname):
    for i,column in enumerate(data.T):
        plt.hist(column, bins=100, density = True)
        plt.xlabel(labels[i])
        plt.savefig(fname+labels[i]+".png")
        plt.close()

def train(dataloader,model,optimizer,loss_fn,device):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the training dataset.
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : torch.optim
        optimizer used for training the network.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : Ttorch.optim
        optimizer used for training the network.
    avg_loss : float
        used as to record and determine how many iterations should be trained.

    """
    
    model.train()
    
    size = len(dataloader.dataset)
    loss_arr = 0
    for batch, (D,P,M) in enumerate(dataloader):
        pred = model(P.to(device))[:,None,:]
        loss = loss_fn(pred,D.to(device),M.to(device))
        optimizer.zero_grad()
        loss.backward()
        
        threshold = 0
        vanishing_grads = 0
        for p in model.parameters():
            if p.grad.norm() == threshold:
                vanishing_grads += 1
        
        if vanishing_grads != 0:
            print(f"{vanishing_grads} gradients are approaching 0")
        
        optimizer.step()
        loss_b = loss.detach().item()
        if batch % 5 == 0:
            current = (batch*P.shape[0] + 1)
            print(f"loss: {loss_b:>7f}  [{current:>5d}/{size:>5d}]")
        loss_arr += loss_b
    
    avg_loss = loss_arr/len(dataloader)
    print(f"Average training loss: {avg_loss:>8f}")
    return model, optimizer , avg_loss

def test(dataloader,model,loss_fn,device,improvement_set = []):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the testing dataset.
    model : network.NeuralNetwork
        the neural network model to be tested.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    test_loss : float
        used as to record and determine how many iterations should be trained.

    """
    model.eval()
    test_loss = 0
    batches = len(dataloader)
    
    with torch.no_grad():
        for batch, (D,P,M) in enumerate(dataloader):
            pred = model(P.to(device))[:,None,:]
            test_loss += loss_fn(pred, D.to(device), M.to(device)).detach().item()
    test_loss /= batches
    
    if improvement_set != []:
        improvement_loss = 0
        imp_batches = len(improvement_set)
        with torch.no_grad():
            for batch, (D, P, M) in enumerate(improvement_set):
                pred = model(P.to(device))[:,None,:]
                improvement_loss += loss_fn(pred, D.to(device), M.to(device)).detach().item()
        improvement_loss /= imp_batches
        print(f"Average testing loss: {test_loss:>8f}")
        print(f"Average improvement loss: {improvement_loss:>8f}")
        return test_loss, improvement_loss
    else:
        print(f"Average testing loss: {test_loss:>8f}")
        return test_loss

def maskedMSELoss(pred,data,mask):
    data = torch.mul(data,mask)
    pred = torch.mul(pred,mask)
    loss = nn.MSELoss()
    result = loss(pred,data)
    return result

class barredMSELoss(nn.Module):
    def __init__(self,scaler,device):
        super(barredMSELoss, self).__init__()
        self.scaler = load(f'scalers/{scaler}')
        self.device = device
        self.set_scale()
        
    def set_scale(self):
        self.min = torch.tensor(self.scaler.data_min_)
        self.max = torch.tensor(self.scaler.data_max_)
        self.scale = self.max - self.min
        
    def scaling(self,a):
        result = (a * self.scale.to(self.device)) + self.min.to(self.device)
        result = 10**result
        return result
        
    def forward(self, output, target, mask):
        #scale to real space
        scaled_tar = self.scaling(target)
        scaled_out = self.scaling(output)
        #find desired boundaries of the original data
        data_low = 0.999*scaled_tar
        data_high = 1.001*scaled_tar
        #create mask where prediction is within boundaries
        loss_mask = torch.where((data_low < scaled_out)&(data_high>scaled_out),0,1)
        #multiply with low data mask to obtain mask of where network needs to learn
        mask = torch.mul(loss_mask,mask)
        #multiply with mask to only consider where network is out of bounds or
        #too small to care
        pred = torch.mul(output,mask)
        data = torch.mul(target,mask)
        #calculate loss
        criterion = nn.MSELoss()
        loss = criterion(pred,data)
        return loss 

class multiplierMSEmaxLoss(nn.Module):
    def __init__(self,scaler,device):
        super(barredMSELoss, self).__init__()
        self.scaler = load(f'scalers/{scaler}')
        self.device = device
        self.set_scale()
        
    def set_scale(self):
        self.min = torch.tensor(self.scaler.data_min_)
        self.max = torch.tensor(self.scaler.data_max_)
        self.scale = self.max - self.min
        
    def scaling(self,a):
        result = (a * self.scale.to(self.device)) + self.min.to(self.device)
        result = 10**result
        return result
    
    def scaled_MSE_loss(self,output,target,mask):
        loss = (target-output)**2
        adjusted_loss = loss*mask
        mean_loss = torch.mean(adjusted_loss)
        max_loss = torch.max(adjusted_loss)
        total_loss = mean_loss + max_loss
        return total_loss
        
    def forward(self, output, target, mask):
        #scale to real space
        scaled_tar = self.scaling(target)
        scaled_out = self.scaling(output)
        #find desired boundaries of the original data
        multiplier_mask = torch.abs(1-scaled_out/scaled_tar)*100
        #multiply with mask to only consider where data is large enough to be
        #important
        pred = torch.mul(output,mask)
        data = torch.mul(target,mask)
        #calculate loss
        loss = self.scaled_MSE_loss(pred,data,multiplier_mask)
        #add the worst outlying points to loss to encourage tighter constraints
        return loss

def queryByDropout(wrk_dir, device = None):
    print("Training using query by dropout committee")
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    
    active_loops = 50
    range_all = np.asarray(generator.lhs_trimmed_gen())
    
    labels = ["a","mass","inc","rin","rout"]
    
    #pre generate Latin Hypercube samples.
    sampler = scipy.stats.qmc.LatinHypercube(d=len(range_all))
    sample = sampler.random(n=1000000)
    theta_lhs = scipy.stats.qmc.scale(sample, range_all[:,0], range_all[:,1])
    
    #if the first time running this code or you want to refresh the dataset, 
    #make this true
    first = False
    
    model = network.NeuralNetwork(5,len(egrid))
    model.to(device)
    best_model = network.NeuralNetwork(5,len(egrid))
    best_model.to(device)
    optimizer = Adam(model.parameters(),lr = 0.001)
    scaler = MinMaxScaler()
    loss_fn = maskedMSELoss
    start_num = 0
    
    if first == True: 
        print("Generating first time dataset")
        init_data_size = 5000
        #generating a random set of parameters and corresponding data
        theta_init = np.random.uniform(range_all[:,0],range_all[:,1],
                                       size = (init_data_size,range_all.shape[0]))
        pars_init = generator.pars_conversion(theta_init)
        print("Parallelized model generation")
        data_init =  Parallel(n_jobs=10,verbose=5)(delayed(generator.rtdist_flux)(pars, egrid)
                                        for pars in pars_init)
        data_init = np.array(data_init)
        data_init, theta_init = nanChecker(data_init, theta_init)
        pars_init = generator.pars_conversion(theta_init)
        #save data for the first time in text files
        saveData(data_init, pars_init, 
                 "data/locations/","active_locs.csv")
        
        last_sig_best_tr = 1e7 #last significant best training loss (set large initially)
        last_sig_best_te = 1e7 #last significant best testing loss (set large initially)
        tr_loss_arr = []
        te_loss_arr = []
        loop_epochs = []
        
        active_loop_num = 0
        
        #create initial dataset object to create scaler (and then delete object)
        query_dataloader = CustomData("data/locations/active_locs.csv", 
                                       scaler,"active_scaler.bin",
                                       scaling=True)
        
        loss_fn = barredMSELoss("active_scaler.bin",device)
        
    else: #load previously generated data as initial data and parameter set
        start_num = 29
        active_loop_num = start_num
        print("Loading previous data")
        renameData(f"data/locations/loc_{active_loop_num}_bar.csv", "data/locations/", "active_locs.csv")
        
        with open(f"loss/{active_loop_num}_bar_tr_loss.txt","r") as f1:
            tr_loss_arr = np.loadtxt(f1)
        f1.close()
        
        with open(f"loss/{active_loop_num}_bar_te_loss.txt","r") as f1:
            te_loss_arr = np.loadtxt(f1)
        f1.close()
        
        with open(f"loss/{active_loop_num}_bar_epochs.txt","r") as f1:
            loop_epochs = np.loadtxt(f1)
        f1.close()
        
        last_sig_best_tr = tr_loss_arr.min()
        last_sig_best_te = te_loss_arr.min()
        
        tr_loss_arr = tr_loss_arr.tolist()
        te_loss_arr = te_loss_arr.tolist()
        loop_epochs = loop_epochs.tolist()
        
        model.load_state_dict(torch.load(f"models/{active_loop_num}_bar_model.pth"))
        optimizer.load_state_dict(torch.load(f"models/{active_loop_num}_bar_optimizer.pth"))
        #use different loss function
        loss_fn = barredMSELoss("active_bar_scaler.bin",device)
        
    batch_size = 1024
    num_workers = 4
    
    lhs_idx = 0
    
    print("Beginning training")
    with Parallel(n_jobs=10,verbose=5) as parallel:
        while active_loop_num < active_loops:
            #increase size of added data dependent on current dataset size
            data_size = len(pd.read_csv("data/locations/active_locs.csv"))
            if data_size > 100000:
                multiplier = ceil(data_size/100000)
            else:
                multiplier = 1
            
            n_samples = 5000*multiplier
            n_samples_large = 10000*multiplier # number of parameter sets to draw 
            divider = 1000
            n_samples_small = int(n_samples_large/divider)
            print(f"I am in active learning loop {active_loop_num+1}")
            # randomly generate points in parameter space
            print("Generating random samples of theta")
            theta_query_large = theta_lhs[lhs_idx : lhs_idx+n_samples_large]
            
            print("computing neural network predictions with dropout for each theta")
            # compute 100 neural network predictions with dropout
            sample_dropout = 100*multiplier
            pred_query_all = np.zeros((sample_dropout,n_samples_small,len(egrid)))
            model.train()
            query_idx = []
            
            distributions(theta_query_large, labels, f"dists/loop_{active_loop_num}_bs_")
            
            for j in tqdm(range(divider),desc="Sample dropout loops"):
                theta_query_small = theta_query_large[j*n_samples_small:(j+1)*n_samples_small]
                for i in range(sample_dropout):
                    pred_query = model(torch.DoubleTensor(theta_query_small).to(device))
                    pred_query_all[i] = pred_query.detach().cpu().numpy()
                # find uncertainty (as measured by relative variance)
                dvar = pred_query_all / np.array([np.var(pred_query_all, axis=-1).T, ]).T
                var_query = np.var(dvar, axis=0)
                mean_var_query = np.mean(var_query, axis=1)
                # add to uncertainties per theta to list
                query_idx.append(mean_var_query.tolist())
            
            #Performing manual memory cleanup
            del pred_query, pred_query_all, dvar, var_query, mean_var_query
            del theta_query_small
            print("Successfully finished generating thetas")
            
            print("Finding top uncertain thetas")
            # sort these thetas from largest uncertainty (as measured by 
            # relative variance) to smallest
            query_idx = np.asarray(query_idx).flatten()
            query_idx = np.argsort(query_idx)[::-1]
            
            print("Generating data for these samples")
            # get out the top `nsamples` values of theta_query
            theta_query = theta_query_large[query_idx[:n_samples]]
            
            distributions(theta_query, labels, f"dists/loop_{active_loop_num}_as_")
            
            # compute the physical model for these thetas
            data_query = np.zeros((theta_query.shape[0],len(egrid)))
            theta_query_iterate = generator.pars_conversion(theta_query)
            print("Parallelized model generation")
            data_query =  parallel(delayed(generator.rtdist_flux)(pars, egrid)
                                            for pars in theta_query_iterate)
            data_query = np.asarray(data_query)
            del theta_query_iterate
            # shuffle indices for neural network training
            idx_shuffle = np.arange(0, len(theta_query), dtype=int)
            np.random.shuffle(idx_shuffle)
        
            idx_query = idx_shuffle[:len(idx_shuffle)-500]
            idx_test = idx_shuffle[-500:]
            
            #Split data and thetas into test and training data
            data_test = data_query[idx_test]
            theta_test  = theta_query[idx_test]
            
            data_query = data_query[idx_query]
            theta_query = theta_query[idx_query]
            
            #Eliminate any broken models
            data_query, theta_query = nanChecker(data_query, theta_query)
            data_test, theta_test = nanChecker(data_test, theta_test)
            
            saveData(data_query, generator.pars_conversion(theta_query), 
                     "data/locations/","active_locs.csv", 
                     current_locs = pd.read_csv("data/locations/active_locs.csv"))
            
            saveData(data_test, generator.pars_conversion(theta_test), 
                     "data/locations/",
                     "active_test_locs.csv")
            
            del data_query, data_test, theta_query, theta_test
            
            # add rejected parameter sets back to original array for potential 
            # future use:
            theta_lhs = np.vstack([theta_lhs, theta_query_large[query_idx[n_samples:]]])
            
            # increment the index for reading parameters from theta_lhs
            lhs_idx += (n_samples_large)
    
            print("Setting up modeling")
            Xquery = CustomData("data/locations/active_locs.csv", scaler, 
                                "active_bar_scaler.bin")
            print("Query data set created")
            query_dataloader = DataLoader(Xquery, batch_size=batch_size, 
                                          num_workers = num_workers, shuffle=True)
            print("Query data loader created")
        
            Xtest = CustomData("data/locations/active_test_locs.csv", scaler, 
                               "active_bar_scaler.bin")
            print("Test data set created")
            test_dataloader = DataLoader(Xtest, batch_size=batch_size,
                                         num_workers = num_workers, shuffle=True)
            print("Test data loader created")
            
            epoch = 0
            #set improvements counters to 0
            imp_te = 0
            imp_tr = 0
            
            while (imp_te < 15 or imp_tr < 15):
                print(f"Epoch {epoch+1} \n -----------------------")
                model, optimizer, train_loss = train(query_dataloader,model,
                                                     optimizer,loss_fn,device)
                loss = test(test_dataloader,model,loss_fn,device)
                te_loss_arr.append(loss)
                tr_loss_arr.append(train_loss)
                tr_bet = (0.9*last_sig_best_tr) - train_loss
                te_bet = (0.9*last_sig_best_te) - loss
                if tr_bet > 0 and te_bet > 0:
                    last_sig_best_tr = train_loss
                    last_sig_best_te = loss
                    imp_te = 0
                    imp_tr = 0
                    print(f"New sig best training loss: {train_loss}")
                    print(f"New sig best testing loss: {loss}")
                elif tr_bet > 0:
                    imp_tr = 0
                    imp_te += 1
                    last_sig_best_tr = train_loss
                    print(f"New sig best training loss: {train_loss}")
                elif te_bet > 0:
                    imp_tr += 1
                    imp_te = 0
                    last_sig_best_te = loss
                    print(f"New sig best testing loss: {loss}")
                else:
                    imp_te += 1
                    imp_tr += 1
                if loss == min(te_loss_arr):
                    torch.save(model.state_dict(), "models/active_best.pth")
                    
                epoch += 1
            if active_loop_num != 0:
                loop_epochs.append(loop_epochs[active_loop_num-1]+epoch)
            else:
                loop_epochs.append(epoch)
            
            #merge test models into training dataset
            mergeSaveData(pd.read_csv("data/locations/active_test_locs.csv"), 
                          pd.read_csv("data/locations/active_locs.csv"), 
                          "data/locations/","active_locs.csv")
            
            #save state of models and data if loop is a multiple of 5, first 5
            #loops or the final loop.
            if ((active_loop_num % 5) == 0 or active_loop_num < 5 
                or active_loop_num == (active_loops - 1)):
                temp_te = np.asarray(te_loss_arr)
                temp_tr = np.asarray(tr_loss_arr)
                temp_epochs = np.asarray(loop_epochs)
                try:
                    best_model.load_state_dict(torch.load("models/active_best.pth"))
                except:
                    best_model.load_state_dict(model.state_dict())
                saveLoop(best_model, "data/locations/active_locs.csv", 
                         optimizer,
                         temp_te, temp_tr, 
                         active_loop_num, temp_epochs)
            #iterate loop number by 1
            active_loop_num += 1
            
        print("Completed training")
        print("Final best training loss:", last_sig_best_tr)
        print("Final best testing loss:", last_sig_best_te)
        torch.save(model.state_dict(), "models/active_final.pth")
        print("Saved PyTorch Model State to models/active_final.pth")
        
        tr_loss_arr = np.asarray(tr_loss_arr)
        te_loss_arr = np.asarray(te_loss_arr)
        
        np.savetxt("loss/active_te_loss.txt",te_loss_arr)
        np.savetxt("loss/active_tr_loss.txt",tr_loss_arr)
        np.savetxt("loss/active_epochs.txt",loop_epochs)

def grid_data_gen(size,fname,egrid):
    
    spin = np.linspace(0.1,1.0,size)
    mass = np.linspace(np.log10(3.3),np.log10(1e11),size)
    inc = np.linspace(1,80,size)
    r_in = np.linspace(-400,-1,size)
    r_out = np.linspace(np.log10(400),np.log10(1e5),size)
    
    #create parameter grid
    theta_init = []
    for a in spin:
        for m in mass:
            for i in inc:
                for r_i in r_in:
                    for r_o in r_out:
                        theta_init.append([a,m,i,r_i,r_o])
    theta_init = np.asarray(theta_init)
    #convert to rtdist model compatible parameters
    pars_init = generator.pars_conversion(theta_init)
    with Parallel(n_jobs=10,verbose=5) as parallel:
        #generate rtdist models for the correlated grid
        data_init = parallel(delayed(generator.rtdist_flux)(pars, egrid)
                                        for pars in pars_init)
    data_init = np.array(data_init)
    data_init, pars_init = nanChecker(data_init, pars_init)
    
    scaler = MinMaxScaler()
    scaler = scaler.fit(data_init)
    dump(scaler, f'scalers/{fname}_scaler.bin', compress=True)
    
    idxs = np.arange(0,data_init.shape[0])
    np.random.shuffle(idxs)
    tra_idx = idxs[:int(len(idxs)-0.1*len(idxs))]
    tes_idx = idxs[int(-0.1*len(idxs)):]
    
    #Splitting data and parameters into training and testing datasets
    train_data = data_init[tra_idx]
    train_pars = pars_init[tra_idx]
    test_data = data_init[tes_idx]
    test_pars = pars_init[tes_idx]
    
    print("Saving to disk")
    #save data for the first time in text files
    saveData(train_data, train_pars, 
             "data/locations/","loc_"+fname+".csv")
    saveData(test_data, test_pars, 
             "data/locations/","loc_"+fname+"_test.csv")
    return

def grid(wrk_dir,device):
    print("Training using grid")
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    
    locations = "data/locations/"
    
    grid_sizes = [5,6,7,8,9,10]
    grid_names = []
    for size in grid_sizes:
        grid_names.append(f"grid_{size}")
    print(grid_names)
        
    batch_size = 128
    num_workers = 4
    
    for (size,fname) in zip(grid_sizes,grid_names):
        print(f"Starting {size} x {size} grid loop")
        
        scaler = MinMaxScaler()
        #create initial dataset object to create scaler (and then delete object)
        training_data = CustomData(locations+"loc_"+fname+".csv", scaler, 
                             scaler_name=f"{fname}_scaler.bin", scaling=True)
        
        training_dataloader = DataLoader(training_data,batch_size=batch_size,
                                      num_workers = num_workers, shuffle=True)
        
        testing_data = CustomData(locations+"loc_"+fname+"_test.csv", scaler, 
                             scaler_name=f"{fname}_scaler.bin")
        
        test_dataloader = DataLoader(testing_data,batch_size=batch_size,
                                      num_workers = num_workers, shuffle=True)
        
        print("Dataloaders created")
        
        model = network.NeuralNetwork(5,len(egrid))
        model.to(device)
        optimizer = Adam(model.parameters(),lr = 0.001)
        loss_fn = maskedMSELoss
        
        last_sig_best_tr = 1e7 #last significant best training loss (set large initially)
        last_sig_best_te = 1e7 #last significant best testing loss (set large initially)
        tr_loss_arr = []
        te_loss_arr = []
        
        epoch = 0
        imp_te = 0
        imp_tr = 0
        
        print("Beginning training")
        while (imp_te < 15 or imp_tr < 15):
            print(f"Epoch {epoch+1} \n -----------------------")
            model, optimizer, train_loss = train(training_dataloader,model,
                                                 optimizer,loss_fn,device)
            loss = test(test_dataloader,model,loss_fn,device)
            te_loss_arr.append(loss)
            tr_loss_arr.append(train_loss)
            tr_bet = (0.9*last_sig_best_tr) - train_loss
            te_bet = (0.9*last_sig_best_te) - loss
            if tr_bet > 0 and te_bet > 0:
                last_sig_best_tr = train_loss
                last_sig_best_te = loss
                imp_te = 0
                imp_tr = 0
                print(f"New best training loss: {train_loss}")
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), f"models/grid_{size}.pth")
            elif tr_bet > 0:
                imp_tr = 0
                imp_te += 1
                last_sig_best_tr = train_loss
                print(f"New best training loss: {train_loss}")
            elif te_bet > 0:
                imp_tr += 1
                imp_te = 0
                last_sig_best_te = loss
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), f"models/grid_{size}.pth")
            else:
                imp_te += 1
                imp_tr += 1
            epoch += 1
        
        print("Completed training")
        print("Final best training loss:", last_sig_best_tr)
        print("Final best testing loss:", last_sig_best_te)
        torch.save(model.state_dict(), f"models/grid_{size}_final.pth")
        print(f"Saved PyTorch Model State to grid_{size}_final.pth")
        
        tr_loss_arr = np.asarray(tr_loss_arr)
        te_loss_arr = np.asarray(te_loss_arr)
        
        np.savetxt(f"loss/grid_{size}_te_loss.txt",te_loss_arr)
        np.savetxt(f"loss/grid_{size}_tr_loss.txt",tr_loss_arr)
        
def main():
    torch.set_default_dtype(torch.double)
    
    wrk_dir = os.getcwd()
    
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}
    
    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")
    
    print(torch.cuda.is_available())
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    
    queryByDropout(wrk_dir,device)
    #grid(wrk_dir,device)

if __name__ == "__main__":
    main()