"""
This is the main program that trains the neural network.
"""
import numpy as np
import os
import sys

from sherpa.astro.ui import unpack_rmf
import torch
from torch import nn
from torch.utils.data import DataLoader,Dataset
from torch.optim import Adam
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from joblib import dump, load
import scipy.stats

import generator
import network
    
class CustomData(Dataset):
    """
    A class that inherits from torch.Dataset that returns both the data from
    the model evaluation and the parameters used to generate the model.
    
    Attributes
    ----------
    par_list : np.ndarray
        Contains the list of parameters used to generate the model.
    data : np.ndarray
        Contains the data generated by the model
    """
    
    def __init__(self,pars,data,scaler,scaling=True):
        super().__init__()
        self.par_list = torch.Tensor(pars)
        self.data = torch.Tensor(data)
        self.scaler = scaler
        self.scaling = scaling
        self.standardize()
    
    def __len__(self):
        return self.par_list.shape[0]
    
    def __getitem__(self,idx):
        datum = self.data[idx]
        parameters = self.par_list[idx]
        return datum,parameters
    
    def standardize(self):
        """
        Filters 0 flux and converts to smallest non-zero value. Then standard
        scales the energy bins.
        """
        D = self.data
        D[D<=1e-30] = 1e-30
        D = torch.log10(D)
        #Change NaNs to minimum non flux (essentially neglible)
        D_np = D.numpy()
        D_np = self.scale(D_np)
        D = torch.from_numpy(D_np)
        D = D.double()
        self.data = D
        
    def scale(self,data):
        """
        Standard scales the logarithm spaced data by energy bin and saves the
        standard scaler for future use.

        Parameters
        ----------
        data : np.ndarray
            Array of spectra in the logspace.

        Returns
        -------
        scaled_data : np.ndarray
            Scaled array of spectra in the logspace.

        """
        scaler = self.scaler
        if self.scaling == True:
            scaled_data = scaler.fit_transform(data)
            dump(scaler, 'std_scaler.bin', compress=True)
        else:
            scaler = load('std_scaler.bin')
            scaled_data = scaler.transform(data)
        return scaled_data
        
def pregenerate_models(n,egrid):
    """
    This function serves to produce test data for validation. It also saves
    the new data onto the disk for training in the future.

    Parameters
    ----------
    n : int
        How many models should be generated as a test set and added to the 
        overall dataset for the future.
    egrid : np.ndarray
        Supplies the energy grid for the model to be evaluated upon.

    Returns
    -------
    all_data : np.ndarray
        An array of all data generated by the model for testing.
    all_pars : TYPE
        An array of all parameters used to generate the data for testing.

    """
    all_data = []
    all_pars = []
    
    for i in range(n):
        print(f"Generating model {i+1}")
        pars = generator.pregen()
        data = generator.rtdist_flux(pars, egrid)
        all_data.append(data)
        all_pars.append(pars)
    
    all_data = np.asarray(all_data)
    all_pars = np.asarray(all_pars)
    
    save_data(all_data,all_pars)
    
    return all_data,all_pars

def save_data(data,pars):
    """
    Saves the data and parameters to disk.

    Parameters
    ----------
    data : np.ndarray
        An array of all data generated by the model to save.
    pars : np.ndarray
        An array of all parameters used to generate the data to save.

    Returns
    -------
    None.

    """
    data = np.asarray(data)
    pars = np.asarray(pars)
    with open("data.txt","w") as f:
        np.savetxt(f,data)
    f.close()
    with open("pars.txt","w") as f:
        np.savetxt(f,pars)
    f.close()
    return
    
def train(dataloader,model,optimizer,loss_fn):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the training dataset.
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : torch.optim
        optimizer used for training the network.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    model : network.NeuralNetwork
        the neural network model to be trained.
    optimizer : Ttorch.optim
        optimizer used for training the network.
    avg_loss : float
        used as to record and determine how many iterations should be trained.

    """
    
    model.train()
    
    size = len(dataloader.dataset)
    batch_size = 12
    loss_arr = 0
    big_loss = 0
    for batch, (D,P) in enumerate(dataloader):
        pred = model(P)
        loss = loss_fn(pred,D)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss_b, current = loss.detach().item(), (batch*batch_size + 1)
        if batch % 100 == 0:
            print(f"loss: {loss_b:>7f}  [{current:>5d}/{size:>5d}]")
        if loss_b > 100:
            print(f"Extremely large batch loss of {loss_b:.2E}")
            big_loss += 1
        loss_arr += loss_b
    
    avg_loss = loss_arr/len(dataloader)
    print(f"Average training loss: {avg_loss:>8f}")
    if big_loss != 0:
        print(f"There were {big_loss} batches with very large loss.")
    return model, optimizer , avg_loss

def test(dataloader,model,loss_fn):
    """
    

    Parameters
    ----------
    dataloader : torch.nn.utils.data.DataLoader
        provides iterable shuffled form of the testing dataset.
    model : network.NeuralNetwork
        the neural network model to be tested.
    loss_fn : torch.nn loss function
        loss function used to train the network.

    Returns
    -------
    test_loss : float
        used as to record and determine how many iterations should be trained.

    """
    model.eval()
    test_loss = 0
    batches = len(dataloader)
    
    with torch.no_grad():
        for batch, (D,P) in enumerate(dataloader):
            pred = model(P)
            test_loss += loss_fn(pred, D).detach().item()
    test_loss /= batches
    print(f"Average testing loss: {test_loss:>8f}")
    return test_loss

def main():
    torch.set_default_dtype(torch.double)
    
    wrk_dir = os.getcwd()
    
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}
    
    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")
    
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    
    active_loops = 20
    epochs = 100
    range_all = np.asarray(generator.lhs_trimmed_gen())
    n_samples = 500
    n_samples_large = 2000 # number of parameter sets to draw 
    
    #pre generate Latin Hypercube samples.
    sampler = scipy.stats.qmc.LatinHypercube(d=len(range_all))
    sample = sampler.random(n=1000000)
    theta_lhs = scipy.stats.qmc.scale(sample, range_all[:,0], range_all[:,1])
    
    first = False #if the first time running this code, make this true
    
    if first == True: 
        #generating a random set of parameters and corresponding data
        theta_init = np.random.uniform(range_all[:,0],range_all[:,1],size = (500,range_all.shape[0]))
        pars_init = generator.pars_conversion(theta_init)
        data_init = []
        for i,pars in enumerate(pars_init):
            print(f"Generating model {i+1}/{500}")
            data_init.append(generator.rtdist_flux(pars, egrid))
        data_init = np.array(data_init)
        #save data for the first time in text files
        np.savetxt("data.txt",data_init)
        np.savetxt("pars.txt",pars_init)
    else: #load previously generated data as initial data and parameter set
        with open("data.txt","r") as f1:
            data = np.loadtxt(f1)
        
        with open("pars.txt","r") as f2:
            pars = np.loadtxt(f2)
        
        #make mass log spaced to improve numeric stability in training
        pars[:,13] = np.log10(pars[:,13]) 
        pars = pars[:,[1,13]] #retrieve spin and mass
        
        bad_spec = []
        for i,spec in enumerate(data):
            if np.any(np.isnan(spec)) == True:
                print(i)
        data = np.delete(data,bad_spec,0)
        pars = np.delete(pars,bad_spec,0)
        data_init = data
        theta_init = pars
    
    scaler = MinMaxScaler()
    #create initial dataset object to create scaler (and then delete object)
    data_init_dataset = CustomData(theta_init, data_init, scaler)
    del data_init_dataset
    
    batch_size = 12
    
    lhs_idx = theta_init.shape[0]
    
    model = network.NeuralNetwork(len(egrid))
    optimizer = Adam(model.parameters(),lr = 0.001)
    loss_fn = nn.MSELoss()
    
    last_sig_best_tr = 1e7 #last significant best training loss
    last_sig_best_te = 1e7 #last significant best testing loss
    tr_loss_arr = []
    te_loss_arr = []
    
    print("Beginning training")
    
    for j in range(active_loops):
        print(f"I am in active learning loop {j+1}")
        # randomly generate points in parameter space
        print("Generating random samples of theta")
        theta_query_large = theta_lhs[lhs_idx : lhs_idx+n_samples_large]
        
        print("computing neural network predictions with dropout for each theta")
        # compute 100 neural network predictions with dropout
        pred_query_all = []
        for i in range(100):
            if i % 10 == 0:
                print(f"Computing theta {i+1}")
            pred_query = model(torch.DoubleTensor(theta_query_large))
            pred_query_all.append(pred_query.detach().numpy())

        pred_query_all = np.array(pred_query_all)
        
        print("Finding top uncertain thetas")
        # sort these data sets from largest uncertainty (as measured by 
        # relative variance) to smallest
        dvar = pred_query_all / np.array([np.var(pred_query_all, axis=-1).T, ]).T
        var_query = np.var(dvar, axis=0)
        mean_var_query = np.mean(var_query, axis=1)
        query_idx = np.argsort(mean_var_query)[::-1]
        
        print("Generating data for these samples")
        # get out the top `nsamples` values of theta_query
        theta_query = theta_query_large[query_idx[:n_samples]]
        # add thetas to the rest of the training data
        theta_init = np.vstack([theta_init, theta_query])
        
        # compute the physical model for these thetas
        data_query = []
        theta_query_iterate = generator.pars_conversion(theta_query)
        for i,pars in enumerate(theta_query_iterate):
            if i % 100 == 0:
                print(f"Generating model {i+1}/{500}")
            data_query.append(generator.rtdist_flux(pars, egrid))
        data_query = np.asarray(data_query)
        # add corresponding models to the rest of the training data
        data_init = np.vstack([data_init, data_query])
        
        print("Saving new data to disk")
        # save new data and parameters to disk
        save_data(data_init, generator.pars_conversion(theta_init))
        
        # add rejected parameter sets back to original array for potential 
        # future use:
        theta_lhs = np.vstack([theta_lhs, theta_query[n_samples:]])
    
        print(f"size of theta_init: {theta_init.shape}")
        print(f"size of data_init: {data_init.shape}")
        
        # increment the index for reading parameters from theta_lhs
        lhs_idx += (n_samples_large)
        
        # shuffle indices for neural network training
        idx_shuffle = np.arange(0, len(theta_init), dtype=int)
        np.random.shuffle(idx_shuffle)
    
        idx_query = idx_shuffle[:len(idx_shuffle)-1000]
        idx_test = idx_shuffle[-1000:]

        print("Setting up modeling")
        Xquery = CustomData(theta_init[idx_query], data_init[idx_query],scaler, 
                            scaling=False)
        query_dataloader = DataLoader(Xquery, batch_size=batch_size, shuffle=True)
    
        Xtest = CustomData(theta_init[idx_test], data_init[idx_test],scaler,
                           scaling=False)
        test_dataloader = DataLoader(Xtest, batch_size=batch_size, shuffle=True)
        
        for i in range(epochs):
            print(f"Epoch {i+1} \n -----------------------")
            model, optimizer, train_loss = train(query_dataloader,model,
                                                 optimizer,loss_fn)
            loss = test(test_dataloader,model,loss_fn)
            te_loss_arr.append(loss)
            tr_loss_arr.append(train_loss)
            tr_bet = (last_sig_best_tr - 0.05*last_sig_best_tr) - train_loss
            te_bet = (last_sig_best_te - 0.05*last_sig_best_te) - loss
            if tr_bet > 0 and te_bet > 0:
                last_sig_best_tr = train_loss
                last_sig_best_te = loss
                print(f"New best training loss: {train_loss}")
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), "best_model.pth")
            elif tr_bet > 0:
                last_sig_best_tr = train_loss
                print(f"New best training loss: {train_loss}")
            elif te_bet > 0:
                last_sig_best_te = loss
                print(f"New best testing loss: {loss}")
                torch.save(model.state_dict(), "best_model.pth")
        
    print("Completed training")
    print("Final best training loss:", last_sig_best_tr)
    print("Final best testing loss:", last_sig_best_te)
    torch.save(model.state_dict(), "final_model.pth")
    print("Saved PyTorch Model State to model.pth")
    
    tr_loss_arr = np.asarray(tr_loss_arr)
    te_loss_arr = np.asarray(te_loss_arr)
    
    np.savetxt("te_loss.txt",te_loss_arr)
    np.savetxt("tr_loss.txt",tr_loss_arr)

if __name__ == "__main__":
    main()