"""
This program serves to visualise a neural network's outputs vs the true values.
"""
from sherpa.astro.io import read_arf

import torch
import os

import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap
from matplotlib.cm import ScalarMappable
import matplotlib.colors as colors
import matplotlib

import numpy as np
import corner

import pandas as pd
from tqdm import tqdm

import network
from dataStructures import Residual, PCADataset
from training import PCALoss
            
def inverse(scaler,data):
    """
    Transforms normalized data back to original form

    Parameters
    ----------
    scaler : scipy scaler
        scaler object that has been previously fitted on data.
    data : ndarray or other list-like object
        normalized data to transform.

    Returns
    -------
    scaled_data : ndarray
        rescaled data.

    """
    scaled_data = scaler.inverse_transform(data)
    return scaled_data

def returnContinuous(df):
    return df.data

def variances(query_samples, active_loop_num):
    #Plot distribution of variances
    plt.hist(query_samples,bins=100)
    plt.savefig(f"dists/loop_{active_loop_num}_variances.png")
    plt.close()

def distributions(data,labels,fname):
    """
    Plots distributions of parameters generated by active learning

    Parameters
    ----------
    data : ndarray or list-like object
        parameter set distribution.
    labels : ndarray or list-like object
        list of label for given parameters.
    fname : string
        save location.

    """
    for i,column in enumerate(data.T):
        plt.hist(column, bins=100, density = True)
        plt.xlabel(labels[i])
        plt.savefig(f"{fname}{labels[i]}.png")
        plt.close()

def residual_plots(egrid, pred, da, fname, title, mname, log = False, 
                   norm = False, mode = "flux"):
    """
    Plots comparison between NN model output and rtdist output with a 
    percentage residual subplot underneath.

    Parameters
    ----------
    egrid : ndarray
        energy grid to plot points on (x-axis).
    pred : ndarray
        NN model output to be plotted.
    da : ndarray
        rtdist model output to be plotted.
    fname : string
        file save location.
    title : string
        title of plot.
    mname : string
        model name.
    log : bool, optional
        If True, change y-label to be log(mode). The default is False.
    norm : bool, optional
        If True, enforce maximum range on residuals. The default is False.
    mode : string, optional
        the type of model output to be compared. Is placed as the x-label.
        The default is "flux".

    """
    pred = np.squeeze(pred)
    da = np.squeeze(da)
    fig, axs = plt.subplots(2,1,sharex=True)
    axs[0].plot(egrid,pred,c="blue",label="NN model")
    axs[0].plot(egrid,da,c="r",label="Truth",lw=1.)
    axs[0].legend()
    axs[0].set_title(title)
    if log == True:
        axs[0].set_ylabel(f"Log({mode})")
        axs[0].set_yscale("log")
    else:
        axs[0].set_ylabel(f"{mode}")
    axs[1].scatter(egrid,(da-pred)/da,s=0.5)
    axs[1].set_ylabel("Residuals")
    axs[1].set_xlabel("Energy (keV)")
    axs[1].axhline(y=0.01,ls="--",color="orange")
    axs[1].axhline(y=-0.01,ls="--",color="orange")
    axs[1].set_yscale("symlog")
    max_res = np.absolute((da-pred)/da).max()
    if max_res > 1 and norm == True:
        axs[1].set_ylim(-1,1)
    plt.tight_layout()
    plt.savefig(f"samples/{mname}_{fname}.png")
    plt.close()
    
def heatmap_plots(df, indexes, ticks, ticklabels, fname, mode):
    """
    Iterates through parameters and plots heatmaps for each parameter.

    Parameters
    ----------
    df : pandas dataframe
        residuals dataframe.
    indexes : ndarray or list-like object
        list of names of parameters.
    ticks : ndarray or list-like object
        y-tick locations to use.
    ticklabels : ndarray or list-like object
        y-tick labels for y-ticks. Must be the same length as ticks.
    fname : string
        filename to save to.
    mode : string
        signifies type of output being used.

    """
    for i,index in enumerate(indexes):
        df.sort_values(by=index,inplace=True,ignore_index=True)
        heatmap(df, index, ticks[i], ticklabels[i], fname, mode)

def set_envir_vars(wrk_dir):
    """
    Sets environment variables for rtdist plotting

    Parameters
    ----------
    wrk_dir : string
        location of working directory.
    """
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}
    
    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")
    
def residual_sorting(df,indexing):
    """
    Sorts residual dataframe by the given index and returns the 0.01, 0.25, 
    0.5, 0.75 percentile values as tick labels

    Parameters
    ----------
    df : pandas dataframe
        dataframe containing residuals and their corresponding parameters.
    indexing : string
        name of the column to sort dataframe by.

    Returns
    -------
    tick : list
        list of tick values index.
    ticklabel : list
        list of tick values.

    """
    df.sort_values(by=indexing,inplace=True,ignore_index=True)
    percents = [0,0.25,0.5,0.75]
    tick = []
    ticklabel = []
    for p in percents:
        tick.append(int(len(df)*p))
        ticklabel.append(f"{df[indexing][int(len(df)*p)]:.2f}")
    return tick,ticklabel

def residual_computation(dataloader, model, scaler, mode):
    """
    Computes and records residual differences between neural network outputs
    and rtdist outputs. Records them with the parameters. For data and model
    outputs below a threshold, we consider the residual difference to be 0.

    Parameters
    ----------
    dataloader : pytorch dataloader
        contains test data and parameters.
    model : pytorch model
        neural network model to compare results to.
    scaler : scikitlearn MinMaxScaler
        scaler to change network output back to real output.
    mode : string
        signifies if using a time lags or flux model.

    Returns
    -------
    dataframe : pandas dataframe
        contains residuals and parameters.
    ticks : list
        list of lists of tick indexes for each parameter.
    ticklabels : list
        list of lists of tick values for each parameter.

    """
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    logged = [1,2,3,4]
    pars_list = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    pars_list = ["a","inc","rin","rout","mass"]
    pars = [[] for i in range(len(pars_list))]
    residuals = []
    for batch, (D,P) in enumerate(tqdm(dataloader)):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-10] = 1e-10
            D = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-5)] = -1e-5
            D[(D>=0)&(np.abs(D)<1e-5)] = 1e-5
            D = np.squeeze(D)
        for i in range(len(pars)):
            if i in logged:
                pars[i].append(10**P[0][i].item())
            else:
                pars[i].append(P[0][i].item())
        if mode == "flux":
            pred = model(P).detach().numpy()
            pred = 10**(inverse(scaler,pred))
        else:
            pred, I_pred = model(P)
            pred = 10**(inverse(scaler,pred.detach().numpy()))
        if mode != "flux":
            pred = pred*np.where(I_pred.detach().numpy() > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.numpy()
        if mode == "flux":
            resid = np.where((np.abs(D)<=1e-10)&(np.abs(pred)<=1e-10),0,resid)
            resid = np.where((np.abs(D)==0),0,resid)
        else:
            resid = np.where((np.abs(D)<=1e-5)&(np.abs(pred)<=1e-5),0,resid)
        resid = np.absolute(np.asarray(resid))
        residuals.append(resid)
        
    residuals = np.squeeze(np.asarray(residuals))
    obj_residuals = []
    for res in residuals:
        obj_residuals.append(Residual(res))
    
    data = {}
    for i,label in enumerate(pars_list):
        data[label] = pars[i]
    data["residuals"] = obj_residuals
    
    dataframe = pd.DataFrame.from_dict(data)
    ticks = []
    ticklabels = []
    for label in pars_list:
        tick, ticklabel = residual_sorting(dataframe, label)
        ticks.append(tick)
        ticklabels.append(ticklabel)
    
    return (dataframe, ticks, ticklabels)

def calculate_loss(testing_dataloader, model, scaler, mode = "flux"):
    """
    

    Parameters
    ----------
    testing_dataloader : TYPE
        DESCRIPTION.
    model : TYPE
        DESCRIPTION.
    scaler : TYPE
        DESCRIPTION.
    mode : TYPE, optional
        DESCRIPTION. The default is "flux".

    Returns
    -------
    residuals : TYPE
        DESCRIPTION.

    """
    residuals = []
    for batch, (D,P) in enumerate(tqdm(testing_dataloader)):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-11] = 1e-11
            D = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-6)] = -1e-6
            D[(D>=0)&(np.abs(D)<1e-6)] = 1e-6
            D = np.squeeze(D)
        if mode == "flux":
            pred = model(P)
        else:
            pred, I_pred = model(P)
            I_pred = I_pred.detach().numpy()
        pred = pred.detach().numpy()
        pred = 10**(inverse(scaler,pred))
        if mode != "flux":
            pred = pred*np.where(I_pred > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.detach().numpy()
        if mode == "flux":
            resid = np.where((np.abs(D)<=1e-10)&(np.abs(pred)<=1e-10),
                             0,resid)
        else:
            resid = np.where((np.abs(D)<=1e-5)&(np.abs(pred)<=1e-5),
                             0,resid)
        residuals.append(np.absolute(np.asarray(resid)))
    residuals = np.asarray(residuals)
    return residuals

def residuals_dataframe(residuals,names):
    d = {"Residuals":[],"Sample Size":[]}
    for i,name in enumerate(names):
        print(name)
        for point in residuals[i].flatten():
            d["Residuals"].append(point)
            d["Sample Size"].append(name) 
    print("# of residuals:"+str(len(d["Residuals"])))
    print("# of labels:"+str(len(d["Sample Size"])))
    df = pd.DataFrame(data = d)
    return df

def model_samples(testing_dataloader,scaler,model,egrid,mname,mode,no_brk=5):
    for batch, (D,P) in enumerate(testing_dataloader):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-11] = 1e-11
            da = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-6)] = -1e-6
            D[(D>=0)&(np.abs(D)<1e-6)] = 1e-6
            da = np.squeeze(D)
        
        da_log = np.log10(np.abs(da))
        da_log_scal = scaler.transform(da_log.reshape(1, -1)).flatten()
        if mode == "flux":
            pred = model(P)
        else:
            pred, I_pred = model(P)
        log_pred = inverse(scaler,pred.detach().numpy())
        pred = pred.detach().numpy()
        sca_pred = np.squeeze(10**(log_pred))
        #generate neural network prediction and rescale to linear space
        if mode == "flux":
            sca_pred[sca_pred<=1e-11] = 1e-11
        else:
            sca_pred[sca_pred<1e-6] = 1e-6
            sca_pred = np.squeeze(sca_pred*np.where(I_pred > 0.5, 1, -1))
        
        fname = f"{batch}"
        title = "Direct comparison"
        
        residual_plots(egrid, sca_pred, da, fname, title, mname, norm = True, mode = mode)
        
        fname = f"{batch}_log"
        title = "Log scaled output"
        residual_plots(egrid, log_pred, da_log, fname, title, mname, 
                       mode = mode)
        fname = f"{batch}_scal"
        title = "Neural network normalised output"
        residual_plots(egrid, pred, da_log_scal, fname, title, mname, 
                       mode = mode)
            
        if batch > no_brk:
            break

def heatmap(df, index, ticks, ticklabels, fname, mode):
    zlabel = "Fractional difference between NN model and rtdist"
    Z_center = -2.5
    #colormap
    top = cm.get_cmap('autumn', 128)
    bottom = cm.get_cmap('winter', 128)
    middle = cm.get_cmap('summer',128)

    newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                           middle(np.linspace(0, 1/2, 128)),
                        top(np.linspace(2/3, 1, 128))))
    newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
    
    residuals = df["residuals"].apply(returnContinuous)
    resids = []
    for item in residuals:
        resids.append(item)
    resids = np.asarray(resids)
    
    fig = plt.figure(figsize=(10,10))
    norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
    ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
    c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
    cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm)
    plt.yticks(ticks,labels=ticklabels)
    if mode == "flux":
        plt.xticks(np.arange(0,4096,4096/4), labels=np.arange(0,20,5))
    else:
        egrid = np.logspace(np.log10(0.5),np.log10(11),num=26)[:-1]
        tick_index = np.arange(0,25,24/4).astype(int)
        plt.xticks(tick_index, labels=np.round(egrid[tick_index],2))
    plt.xlabel("Energy in keV")
    plt.ylabel(index)
    
    cbar.set_label(zlabel, rotation=270, labelpad=15)
    fig.tight_layout()
    matplotlib.rcParams.update({'font.size': 16})
    plt.savefig(f"heatmaps/{fname}_{index}.png")
    plt.close()
    return

def plot_loss_vs_sample_size(grid_sample_nums=[], grid=[], 
                             active_sample_nums=[], active=[],
                             mode="flux",single=False):
    if single == False:
        fig , axs = plt.subplots(1,2,sharey=True, sharex=True, figsize=(12,9))
        
        for (x,y,z) in zip(grid_sample_nums,grid.low,grid.high):
            axs[0].scatter([x]*len(y),y, s=1, color="orange", zorder = 1, marker = "x",
                           alpha = 0.5)
            axs[0].scatter([x]*len(z),z, s=1, color="orange", zorder = 1, marker = "x",
                           alpha = 0.5)
            
        axs[0].fill_between(grid_sample_nums, grid.q_95, 
                         grid.q_5, alpha = 0.25,color = "orange",
                         zorder=3)
        axs[0].fill_between(grid_sample_nums, grid.q_75, 
                         grid.q_25, alpha = 0.5,color = "orange",
                         zorder=4)
        axs[0].fill_between(grid_sample_nums, grid.q_99, 
                         grid.q_1, alpha = 0.5,color = "orange",
                         zorder=2)
        axs[0].plot(grid_sample_nums,grid.median,label="Grid",color = "orange",
                 zorder=5)
        
        for (x,y,z) in zip(active_sample_nums,active.low,active.high):
            axs[1].scatter([x]*len(y),y, s=1, color="blue", zorder = 2, marker = "x",
                           alpha = 0.5)
            axs[1].scatter([x]*len(z),z, s=1, color="blue", zorder = 2, marker = "x",
                           alpha = 0.5)
            
        axs[1].fill_between(active_sample_nums, active.q_95, 
                         active.q_5, alpha = 0.25,color = "blue",
                         zorder=3)
        axs[1].fill_between(active_sample_nums, active.q_75, 
                         active.q_25, alpha = 0.5,color = "blue",
                         zorder=4)
        axs[1].fill_between(active_sample_nums, active.q_99, 
                         active.q_1, alpha = 0.5,color = "blue",
                         zorder=2)
        axs[1].plot(active_sample_nums,active.median,label="Active learning",
                 color = "blue",zorder=5)
        
        axs[0].axhline(y=1e-2, ls = "--",label="1% error",zorder=6,color="green")
        axs[1].axhline(y=1e-2, ls = "--",zorder=6,color="green")
        axs[0].axhline(y=1e-3, ls = "dashdot",label="0.1% error",zorder=7,color="red")
        axs[1].axhline(y=1e-3, ls = "dashdot",zorder=7,color="red")
        
        plt.yscale("log")
        
        plt.yticks([1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1e0,1e1])
        fig.suptitle(f"Loss by sample size for {mode}")
        
        fig.supxlabel("Number of samples used in training")
        fig.supylabel("Residuals")
        lines = []
        labels = []
          
        for ax in fig.axes:
            Line, Label = ax.get_legend_handles_labels()
            # print(Label)
            lines.extend(Line)
            labels.extend(Label)
            
        fig.legend(lines, labels, loc='upper right')
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"loss/loss_size_{mode}.png")
        plt.close()
    else:
        if grid_sample_nums != []:
            pass
        elif active_sample_nums != []:
            for (x,y,z) in zip(active_sample_nums,active.low,active.high):
                plt.scatter([x]*len(y),y, s=1, color="blue", zorder = 2, marker = "x",
                               alpha = 0.5)
                plt.scatter([x]*len(z),z, s=1, color="blue", zorder = 2, marker = "x",
                               alpha = 0.5)
                
            plt.fill_between(active_sample_nums, active.q_95, 
                             active.q_5, alpha = 0.25,color = "blue",
                             zorder=3)
            plt.fill_between(active_sample_nums, active.q_75, 
                             active.q_25, alpha = 0.5,color = "blue",
                             zorder=4)
            plt.fill_between(active_sample_nums, active.q_99, 
                             active.q_1, alpha = 0.5,color = "blue",
                             zorder=2)
            plt.plot(active_sample_nums,active.median,label="Active learning",
                     color = "blue",zorder=5)
            
            plt.axhline(y=1e-2, ls = "--",label="1% error",zorder=6,color="green")
            plt.axhline(y=1e-3, ls = "dashdot",label="0.1% error",zorder=7,color="red")
            
            plt.yscale("log")
            
            plt.yticks([1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1e0,1e1])
            plt.title(f"Loss by sample size for {mode}")
            
            plt.xlabel("Number of samples used in training")
            plt.ylabel("Residuals")
            lines = []
            labels = []
                
            plt.legend(lines, labels, loc='upper right')
            plt.savefig(f"loss/loss_size_{mode}.png")
            plt.close()

def loss_epochs_plot(loss_base_loc,mode):
    
    train_names = [loss_base_loc+f"grid_{i}_{mode}_tr_loss.txt" for i in range(5,11)]
    test_names = [loss_base_loc+f"grid_{i}_{mode}_te_loss.txt" for i in range(5,11)]
    
    active_loss = np.loadtxt(loss_base_loc+f"36_{mode}_tr_loss.txt")
    active_test = np.loadtxt(loss_base_loc+f"36_{mode}_te_loss.txt")
    
    plt.plot(np.loadtxt(train_names[-1]), label="Training loss: 10x10 grid", 
             c = "red", ls = "-")
    plt.plot(np.loadtxt(test_names[-1]), label = "Validation loss: 10x10 grid", 
             c = "red", ls = "--")
    
    plt.plot(active_loss,label = "Training loss: active learning", c = "blue",
             ls = "-")
    plt.plot(active_test,label = "Validation loss: active learning", c = "blue",
             ls = "--")
    
    plt.yscale("log")
    plt.xlabel("Training epochs")
    plt.ylabel("Loss")
    plt.title(f"Comparison of loss by strategy for {mode}")
    plt.legend()
    plt.savefig(f"loss/loss_time_{mode}.png")
    plt.close()

def plot_spec_dist(egrid,flux,pars):
    labels = ["height","a","inc","rin","rout","z","Gamma","Dkpc","Afe",
              "logNe","kte","nH","boost","mass","honr","b1","b2","fmin","fmax",
              "ReIM","phiA","phiAB","g","Anorm","RESP","Xnorm"]
    
    labels = ["a","inc","rin","distance","mass"]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    
    pars[:,3] = -pars[:,3]
    
    e_mid = (egrid[1:] + egrid[:-1])/2
    e_mid = e_mid * 1.60218e-9 #convert to erg
    hist_F = []
    bad_pars = []
    for i,fl in enumerate(flux):
        fl_int = fl[:-1]*e_mid
        fl_int = fl_int.sum()
        if fl_int < 0:
            pars_print = pars[i]
            pars_print[3] = -pars_print[3]
            print(pars_print)
            print(fl)
            print(fl[:-1]*e_mid)
            bad_pars.append(pars[i])
        hist_F.append(fl_int)
    
    bad_pars = np.asarray(bad_pars)
    for i in range(bad_pars.shape[1]):
        if i in logged:
            hist, bins, _ = plt.hist(bad_pars[:,i],bins=20)
            plt.close()
            logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
            plt.hist(bad_pars[:,i], bins=logbins)
            plt.xlabel(f"log({labels[i]})")
            plt.xscale("log")
        else:
            plt.hist(bad_pars[:,i])
            plt.xlabel(f"{labels[i]}")
        plt.ylabel("Occurences")
        plt.title(f"Parameters yielding negative fluxs for {labels[i]}")
        plt.savefig(f"verify/bad_{labels[i]}.png")
        plt.close()
    
    hist_F = np.asarray(hist_F)
    hist_F = hist_F[hist_F > 0]
    hist, bins, _ = plt.hist(hist_F,bins=100)
    plt.close()
    logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
    plt.hist(hist_F, bins=logbins)
    plt.xlabel("Flux (erg/cm^2/s)")
    plt.ylabel("Occurences")
    plt.xscale("log")
    plt.title("Histogram of total fluxes generated in test set")
    plt.savefig("verify/hist.png")
    plt.close()
    
    segs = [np.column_stack([egrid[:-1], fl[:-1]*e_mid]) for fl in flux]
    
    for par in range(pars.shape[1]):
        fig, ax = plt.subplots()
        lc = matplotlib.collections.LineCollection(segs, array = pars[:,par],
                                                   alpha = 0.3)
        ax.add_collection(lc)
        axcb = fig.colorbar(lc)
        axcb.set_label(f"{labels[par]}")
        ax.set_title(f"Colored by {labels[par]}")
        ax.set_ylabel("erg/cm^2/s")
        ax.set_xlabel("Energy (keV)")
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlim(5e-2)
        ax.set_ylim(1e-20)
        plt.savefig(f"verify/specs_{labels[par]}.png")
        plt.close()
    
def check_uniques(array1,array2):
    combo = pd.concat([array1,array2])
    combo.drop_duplicates(keep=False)
    return combo

def aggregate_dists(files):
    nbins = 100
    
    labels = ["0th loop", "10th loop", "20th loop", "30th loop", "40th loop"]
    pars_list = ["h","a","inc","rin","rout","z","Gamma","Dkpc","Afe","logNe",
                    "kTe","nH","boost","Mass","honr","b1","b2","phiAB","g",
                    "Anorm"]
    
    pars_list = ["a","inc","rin","rout","mass"]
    
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    negatives = [3]
    
    full_pars = [[] for i in range(len(pars_list))]
    
    last_pars = pd.DataFrame()
    for file in files:
        print(file)
        df = pd.read_csv(file)
        pars = df.loc[:, df.columns!="Location"]
        new_pars = check_uniques(pars,last_pars)
        last_pars = pars
        for item in range(len(pars_list)):
            new_pars_list = new_pars.loc[:,pars_list[item]]
            if item in negatives:
                new_pars_list = -1*new_pars_list
            if item in logged:
                new_pars_list = np.log10(new_pars_list)
            full_pars[item].append(new_pars_list)
    cmap = cm.get_cmap("Wistia")(np.linspace(0, 1, len(labels)))
    
    pars_bins = []
    
    for i, item in enumerate(pars_list):
        hist, bins, _ = plt.hist(full_pars[i], nbins, histtype="bar", 
                                 stacked=True)
        logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
        pars_bins.append(logbins)
        plt.close()
    
    fig, axs = plt.subplots(4,5,sharey=True,figsize=(12,9))
    matplotlib.rcParams.update({'font.size': 16})
    
    for i, item in enumerate(pars_list):
        x = np.floor(i/5)
        y = i%5
        axs[x,y].hist(full_pars[i], pars_bins[i], 
                      histtype="bar", stacked=True, color = cmap, label=labels)
        if i in logged:
            axs[x,y].set_xscale("log")
        axs[x,y].set_xlabel(pars_list[i])
    plt.yscale("log")
    plt.savefig("dists/stacked.png")
    plt.close()
    
def PCA_plotting(wrk_dir,name):
    """
    Function dedicated to plotting PCA neural network model outputs. Only plots
    things necessary for PCA model diagnosis

    Parameters
    ----------
    wrk_dir : string
        current working directory location.

    Returns
    -------
    None.

    """
    plot_loss = False
    
    if plot_loss == True:
        #plotting of training and validation loss over time
        PCA_train_loss = np.loadtxt(f"loss/{name}_tr_loss.txt")
        PCA_train_loss_med = np.loadtxt(f"loss/{name}_med_tr_loss.txt")
        PCA_train_loss_std = np.loadtxt(f"loss/{name}_std_tr_loss.txt")
        PCA_val_loss = np.loadtxt(f"loss/{name}_te_loss.txt")
        
        epochs = np.arange(1,len(PCA_train_loss)+1)
        """
        plt.fill_between(epochs, PCA_train_loss+PCA_train_loss_std,
                         PCA_train_loss-PCA_train_loss_std,color="b",alpha=0.5)
        """
        plt.plot(epochs,PCA_train_loss,label = "Training loss", c = "blue",
                 ls = "-")
        plt.plot(epochs,PCA_val_loss,label = "Validation loss", c = "orange",
                 ls = "--")
        """
        plt.plot(epochs,PCA_train_loss_med,label = "Median training loss", c = "green",
                 ls = "-.")
        """
        plt.yscale("log")
        plt.xscale("log")
        plt.xlabel("Training epochs")
        plt.ylabel("Loss")
        #plt.title(f"Loss by epoch for {name}")
        plt.legend()
        plt.tight_layout()
        plt.ylim(top = 1e1)
        plt.savefig(f"loss/loss_{name}.png")
        plt.close()
        
        plt.plot(PCA_train_loss/PCA_val_loss,c="b",ls="-")
        plt.axhline(1,c="orange",ls="--")
        plt.xlabel("Epoch")
        plt.ylabel("Ratio between training loss and validation loss")
        plt.savefig("loss/loss_ratio.png")
        plt.close()
    
    #plotting of emulator vs test data performance
    
    pars_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,21,22,23]
    negatives = [3]
    logged = [0,2,3,4,7,8,10,11,12,13,23]
    
    labels = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    
    test_data = PCADataset("data/locations/loc_flux_test.csv",
                               pars_list,negatives,logged,scale_bool = False,
                               PCA_loc="scalers/PCA_20_spec.bin",
                               comp_loc="scalers/comp_20_spec.bin",
                               spec_scal_loc="scalers/spec_20_spec.bin")
    calib_data = PCADataset("data/locations/loc_flux_cal.csv",
                               pars_list,negatives,logged,scale_bool = False,
                               PCA_loc="scalers/PCA_20_spec.bin",
                               comp_loc="scalers/comp_20_spec.bin",
                               spec_scal_loc="scalers/spec_20_spec.bin")
    
    arf_name = wrk_dir+"/ResponseFiles/PN.arf"
    arf = read_arf(arf_name)
    egrid_lo,egrid_hi = arf.energ_lo[arf.energ_lo>0.1],arf.energ_hi[arf.energ_lo>0.1]
    
    emid = (egrid_lo+egrid_hi)/2
    
    bin_width = egrid_hi-egrid_lo
    
    percents = np.array([0,0.25,0.5,0.75,0.99])
    e_ticks = np.round(emid[(len(emid)*percents).astype(int)],1).astype(str)
    
    data = []
    for file in tqdm(test_data.locations):
        data.append(np.loadtxt(file).reshape(1, -1))
    D = np.concatenate(data,axis=0)
    D[D<1e-11] = 1e-11
    
    if "active" in name:
        model = network.DynamicDropoutNetwork(20,40,8,256,"GELU")
    else:
        model = network.RtdistSpec_ensemble()
        #model = network.RtdistSpec()
        
    """
    print(f"models/{name}.pth")
    model.load_state_dict(torch.load(f"models/{name}.pth"))
    model.eval()
    """
    
    
    plot_pca = False
    
    if plot_pca == True:
        nn_comps = model(test_data.pars).detach().numpy()
        train_comps = np.asarray(test_data.data)
        pars = np.asarray(test_data.pars)
        pca = test_data.pca
        spectra_scaler = test_data.spec_scaler
        comp_scaler = test_data.PCA_scaler
        
        scaled = spectra_scaler.transform(np.log10(D))
        pca_comps = pca.transform(scaled)
        scaled_pca_comps = comp_scaler.fit_transform(pca_comps)
        recon_D = 10**spectra_scaler.inverse_transform(pca.inverse_transform(pca.transform(scaled)))
        
        recon_resid = np.abs((D-recon_D))
        recon_perc = np.abs((D-recon_D)/D)
        recon_perc[D==1e-11] = np.nan
        
        print(f"Maximum PCA residual is {recon_perc[~np.isnan(recon_perc)].max()*100}%")
        print(f"Average PCA residual is {recon_perc[~np.isnan(recon_perc)].mean()*100}%")
        percent = (recon_perc[(recon_perc<0.01)&~np.isnan(recon_perc)].size/recon_perc[~np.isnan(recon_perc)].size)*100
        print(f"{percent}% of PCA residuals are below 1%")
        
        plt.plot(np.mean(recon_resid,axis=0))
        plt.xlabel("Energy channel")
        plt.ylabel("Mean absolute error")
        plt.title("Absolute error of PCA reconstruction error")
        plt.yscale("log")
        plt.savefig(f"samples/{name}_PCA_mean_error.png")
        plt.close()
        plt.plot(np.mean(recon_perc,axis=0))
        plt.xlabel("Energy channel")
        plt.ylabel("Mean fractional error")
        plt.title("Fractional error of PCA reconstruction error")
        plt.yscale("log")
        plt.savefig(f"samples/{name}_PCA_mean_perc.png")
        plt.close()
        
        for i in range(len(pars_list)):
            print(f"Creating plot for {labels[i]}")
            sort_ind = np.argsort(test_data.pars[:,i])
            sort_par = test_data.pars[sort_ind,i]
            percents = np.array([0,0.25,0.5,0.75,0.99])
            ticks = (len(sort_par)*percents).astype(int)
            tick_labels = np.asarray(np.round(sort_par[(len(sort_par)*percents).astype(int)],1)).astype(str)
            resids = recon_perc[sort_ind]
            zlabel = "Fractional difference between RTFAST and RTDIST"
            Z_center = -2.5
            #colormap
            top = cm.get_cmap('autumn', 128)
            bottom = cm.get_cmap('winter', 128)
            middle = cm.get_cmap('summer',128)
    
            newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                                   middle(np.linspace(0, 1/2, 128)),
                                top(np.linspace(2/3, 1, 128))))
            newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
            newcmp.set_over('black')
    
            fig = plt.figure(figsize=(10,10))
            norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
            ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
            c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                        10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
            cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm, extend='max')
            plt.yticks(ticks,labels=tick_labels)
            plt.xticks(np.arange(0,recon_resid.shape[1],recon_resid.shape[1]/5), 
                       labels=e_ticks)
            plt.xlabel("Energy in keV")
            plt.ylabel(labels[i])
            
            cbar.set_label(zlabel, rotation=270, labelpad=15)
            fig.tight_layout()
            matplotlib.rcParams.update({'font.size': 16})
            plt.savefig(f"heatmaps/PCA_recon_err_{labels[i]}.png")
            plt.close()
        
        for i in range(pars.shape[1]):
            fig, axs = plt.subplots(5,5,
                                    sharex=True,
                                    sharey=True,
                                    figsize=(20,20))
            norm = colors.Normalize(vmin=np.min(pars[:,i]),vmax=np.max(pars[:,i]))
            cmap = plt.get_cmap("plasma")
            for j in range(5):
                axs[4,j].set_xlabel(f"PCA {j}")
                for k in range(5):
                    axs[j,k].scatter(scaled_pca_comps[:,j],scaled_pca_comps[:,k],
                                     c=pars[:,i],cmap=cmap,norm=norm)
                    if j == 0:
                        axs[k,0].set_ylabel(f"PCA {k}")
                    if k > j:
                        fig.delaxes(axs[j,k])
            
            sm =  ScalarMappable(norm=norm, cmap=cmap)
            sm.set_array([])
            cbar = fig.colorbar(sm, ax=axs[:,4],format='%.2e')
            fig.suptitle(labels[i])
            matplotlib.rcParams.update({'font.size': 16})
            plt.savefig(f"samples/corner/{labels[i]}_corner.png")
            plt.close()
    
    test_pred = model(test_data.pars).detach().numpy()
    
    test_loss = loss_calc(test_data.data, test_pred,
                          test_data.pca.explained_variance_ratio_)
    
    loss_fn = PCALoss(test_data.pca.explained_variance_ratio_, "cpu")
    print(f"PCA loss reports: {loss_fn(model(test_data.pars),test_data.data)}")
    
    print(test_loss.shape)
    print(f"Highest test loss is {test_loss.max()}")
    print(f"Average test loss is {test_loss.mean()}")
    plt.hist(test_loss,bins=50)
    plt.xlabel("Loss")
    plt.savefig(f"loss/test_dists_{name}.png")
    plt.close()
    
    for j in range(test_data.pars.shape[1]):
        plt.scatter(test_data.pars[:,j],test_loss)
        plt.xlabel(labels[j])
        plt.ylabel("Loss")
        plt.savefig(f"loss/loss_by_{labels[j]}_{name}.png")
        plt.close()
    
    test_pred = reconstruct_emulator(test_data, model)
    residuals_signed = (test_pred-D)/D
    calib_pred = reconstruct_emulator(calib_data, model)
    
    data = []
    for file in tqdm(calib_data.locations):
        data.append(np.loadtxt(file).reshape(1, -1))
    calib_D = np.concatenate(data,axis=0)
    calib_D[calib_D<1e-11] = 1e-11
    
    residuals_calib = (calib_pred-calib_D)/calib_D
    calibration_factor = np.mean(residuals_calib,axis=0)+1
    np.savetxt(f"scalers/calib_factor_{name}.txt",calibration_factor)
    
    residuals_signed_uncal = ((test_pred)-D)/D
    residuals_signed_uncal[(D==1e-11)] = np.nan
    
    plt.hist(residuals_signed_uncal[np.abs(residuals_signed_uncal)<0.2]*100,bins=80,density=True)
    plt.xlabel("Percentage residual")
    plt.ylabel("Probability density")
    plt.xlim(-20,20)
    plt.axvline(0,ls="--",c="black")
    plt.axvline(-1,ls="--",c="red")
    plt.axvline(1,ls="--",c="red")
    plt.savefig(f"loss/resids_dist_uncal_{name}.png")
    plt.close()
    
    residuals_signed = ((test_pred/calibration_factor)-D)/D
    residuals_signed[(D==1e-11)] = np.nan
    
    plt.hist(residuals_signed[np.abs(residuals_signed)<0.2]*100,bins=80,density=True)
    plt.xlabel("Percentage residual")
    plt.ylabel("Probability density")
    plt.xlim(-20,20)
    plt.axvline(0,ls="--",c="black")
    plt.axvline(-1,ls="--",c="red")
    plt.axvline(1,ls="--",c="red")
    plt.savefig(f"loss/resids_dist_cal_{name}.png")
    plt.close()
    
    fig, axs = plt.subplots(1,2,sharey=True,figsize=(10,5))
    axs[0].hist(residuals_signed_uncal[np.abs(residuals_signed_uncal)<0.2]*100,bins=80,density=True)
    fig.supxlabel("Percentage residual")
    fig.supylabel("Probability density")
    axs[0].set_xlim(-20,20)
    axs[0].axvline(0,ls="--",c="black")
    axs[0].axvline(-1,ls="--",c="red")
    axs[0].axvline(1,ls="--",c="red")
    axs[0].set_title("Uncalibrated")
    axs[1].hist(residuals_signed[np.abs(residuals_signed)<0.2]*100,bins=80,density=True)
    axs[1].set_xlim(-20,20)
    axs[1].axvline(0,ls="--",c="black")
    axs[1].axvline(-1,ls="--",c="red")
    axs[1].axvline(1,ls="--",c="red")
    axs[1].set_title("Calibrated")
    plt.savefig("loss/resids_cal_com.png")
    plt.close()
    
    np.savetxt(f"data/testing/calib_resids_{name}.txt",residuals_signed)
    
    perc_resids = np.sort(residuals_signed[np.abs(residuals_signed)<0.2]*100,axis=None)
    chance = np.arange(len(perc_resids))/len(perc_resids)
    
    plt.plot(perc_resids,chance)
    plt.xlabel("Percentage residual")
    plt.ylabel("Cumulative probability")
    plt.savefig(f"loss/resids_cum_sum_{name}.png")
    plt.close()
    
    mean_res = np.mean(residuals_signed,axis=0)*100
    res_25 = np.quantile(residuals_signed,0.25,axis=0)*100
    res_75 = np.quantile(residuals_signed,0.75,axis=0)*100
    res_95 = np.quantile(residuals_signed,0.95,axis=0)*100
    res_05 = np.quantile(residuals_signed,0.05,axis=0)*100
    res_99 = np.quantile(residuals_signed,0.99,axis=0)*100
    res_01 = np.quantile(residuals_signed,0.01,axis=0)*100
    
    plt.fill_between(emid, res_01, res_99,color="b",alpha=0.2,label="99%")
    plt.fill_between(emid, res_05, res_95,color="b",alpha=0.25,label="95%")
    plt.fill_between(emid, res_25, res_75,color="b",alpha=0.5,label="50%")
    plt.plot(emid,mean_res,c="b")
    plt.xlabel("Energy (keV)")
    plt.ylabel("Percentage residuals")
    plt.xscale("log")
    plt.legend()
    plt.savefig(f"loss/energ_resid_{name}.png")
    plt.close()
    
    sign_res = ((test_pred/calibration_factor)-D)/D
    mean_signed_res = np.median(sign_res,axis=1)
    print(np.min(np.abs(mean_signed_res)))
    ind_low = np.argmin(np.abs(mean_signed_res))
    print(test_data.pars[ind_low])
    sign_res[(D==1e-11)] = np.nan
    
    mean_sign_res = np.mean(sign_res,axis=1)
    
    
    pars_test = np.asarray(test_data.pars)
    fig, axs = plt.subplots(len(pars_list),len(pars_list),figsize=(40,40))
    top = cm.get_cmap('autumn', 128)
    bottom = cm.get_cmap('winter', 128)
    middle = cm.get_cmap('summer',128)

    newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                           middle(np.linspace(0, 1/2, 128)),
                        top(np.linspace(2/3, 1, 128))))
    newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
    newcmp.set_over('black')
    norm = colors.SymLogNorm(vmin = 0.1, 
                             vmax = -0.1,base=10,
                             linthresh=0.01)
    for i in range(len(pars_list)):
        for j in range(len(pars_list)):
            ax = axs[j,i].scatter(pars_test[:,j],pars_test[:,i],
                                  c=mean_sign_res,s=10,cmap = newcmp,
                                  norm=norm)
            if i == 0:
                axs[j,0].set_ylabel(labels[j])
        axs[-1,i].set_xlabel(labels[i])
    
    fig.colorbar(ax, ax=axs,format='%.0e', norm=norm, extend='max')
    plt.savefig("heatmaps/posneg_pars_dist.png")
    plt.close()
    
    residuals = np.abs(((test_pred/calibration_factor)-D)/D)
    residuals[(D==1e-11)] = np.nan
    print(f"Maximum residual is {residuals[~np.isnan(residuals)].max()*100}%")
    print(f"Average residual is {residuals[~np.isnan(residuals)].mean()*100}%")
    print(f"Median residual is {np.median(residuals[~np.isnan(residuals)])*100}%")
    percent = (residuals[(residuals<0.01)&~np.isnan(residuals)].size/residuals[~np.isnan(residuals)].size)*100
    print(f"{percent}% of residuals are below 1%")
    
    plt.plot(np.mean(residuals,axis=0))
    plt.xlabel("Energy channel")
    plt.ylabel("Mean percentage residual")
    plt.title("Mean fractional error of emulator reconstruction")
    plt.yscale("log")
    plt.tight_layout()
    plt.savefig(f"samples/{name}_mean_errors.png")
    plt.close()
    
    for i in range(len(pars_list)):
        print(f"Creating plot for {labels[i]}")
        sort_ind = np.argsort(test_data.pars[:,i])
        sort_par = test_data.pars[sort_ind,i]
        percents = np.array([0,0.25,0.5,0.75,0.99])
        ticks = (len(sort_par)*percents).astype(int)
        tick_labels = np.asarray(np.round(sort_par[(len(sort_par)*percents).astype(int)],1)).astype(str)
        resids = residuals[sort_ind]
        zlabel = "Fractional difference between RTFAST and RTDIST"
        Z_center = -2.5
        #colormap
        top = cm.get_cmap('autumn', 128)
        bottom = cm.get_cmap('winter', 128)
        middle = cm.get_cmap('summer',128)

        newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                               middle(np.linspace(0, 1/2, 128)),
                            top(np.linspace(2/3, 1, 128))))
        newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
        newcmp.set_over('black')
        
        fig = plt.figure(figsize=(10,10))
        norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
        ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
        c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                    10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
        cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm, extend='max')
        plt.yticks(ticks,labels=tick_labels)
        plt.xticks(np.arange(0,residuals.shape[1],residuals.shape[1]/5), 
                   labels=e_ticks)
        plt.xlabel("Energy in keV")
        plt.ylabel(labels[i])
        
        cbar.set_label(zlabel, rotation=270, labelpad=15)
        fig.tight_layout()
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"heatmaps/{name}_{labels[i]}.png")
        plt.close()
    
    for i in range(len(pars_list)):
        print(f"Creating unsigned plot for {labels[i]}")
        sort_ind = np.argsort(test_data.pars[:,i])
        sort_par = test_data.pars[sort_ind,i]
        percents = np.array([0,0.25,0.5,0.75,0.99])
        ticks = (len(sort_par)*percents).astype(int)
        tick_labels = np.asarray(np.round(sort_par[(len(sort_par)*percents).astype(int)],2)).astype(str)
        resids = sign_res[sort_ind]
        zlabel = "Fractional difference between RTFAST and RTDIST"
        #colormap
        cmap = cm.get_cmap('autumn', 128)
        bottom = cm.get_cmap('winter', 128)
        middle = cm.get_cmap('summer',128)

        newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                               middle(np.linspace(0, 1/2, 128)),
                            top(np.linspace(2/3, 1, 128))))
        newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
        newcmp.set_over('black')
        
        fig = plt.figure(figsize=(10,10))
        norm = colors.SymLogNorm(vmin = 0.1, 
                                 vmax = -0.1,base=10,
                                 linthresh=0.01)
        ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
        cbar = plt.colorbar(format='%.0e', norm=norm, extend='max')
        plt.yticks(ticks,labels=tick_labels)
        plt.xticks(np.arange(0,residuals.shape[1],residuals.shape[1]/5), 
                   labels=e_ticks)
        plt.xlabel("Energy in keV")
        plt.ylabel(labels[i])
        
        cbar.set_label(zlabel, rotation=270, labelpad=15)
        fig.tight_layout()
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"heatmaps/{name}_{labels[i]}_posneg.png")
        plt.close()
    
    plot_samples = False
    
    if plot_samples == True:
        print("Plotting samples")
        data = []
        for file in test_data.locations:
            data.append(np.loadtxt(file).reshape(1, -1))
        data = np.concatenate(data,axis=0)
        data[data<test_data.threshold] = test_data.threshold
        
        i = 0
        for pred, D in zip(test_pred/calibration_factor, data):
            fig, axs = plt.subplots(2,sharex=True,figsize=(10,10))
            axs[0].plot(emid,pred/bin_width,label="RTFAST")
            axs[0].plot(emid,D/bin_width,label="RTDIST", ls = "--")
            axs[0].set_ylabel("Flux (photons/cm^2/s/keV)")
            axs[0].legend()
            axs[0].set_yscale("log")
            axs[0].set_xscale("log")
            axs[1].plot(emid,(pred-D)/D)
            axs[1].set_ylabel("(RTFAST-RTDIST)/RTDIST")
            fig.supxlabel("Energy (keV)")
            #fig.suptitle("Comparison of PCA emulator output vs expected")
            plt.savefig(f"samples/{name}_PCA_compare_{i}.png")
            plt.close()
            i += 1
            if i > 6:
                break
        diff_comps = np.abs((train_comps[:,i]-nn_comps[:,i])/((train_comps[:,i]+nn_comps[:,i])/2))
        
        for j in tqdm(range(pars.shape[1])):
            for i in range(nn_comps.shape[1]):
                fig, axs = plt.subplots(2,sharex=True,figsize=(10,10))
                axs[0].scatter(pars[:,j],train_comps[:,i],label="Training set",marker="o")
                axs[0].scatter(pars[:,j],nn_comps[:,i],label="Emulator",marker="x")
                axs[0].legend()
                axs[0].set_ylabel(f"PCA component {i+1}")
                axs[1].scatter(pars[:,j],diff_comps,marker="x")
                axs[1].set_ylabel("Percentage difference")
                axs[1].set_yscale("log")
                fig.supxlabel(labels[j])
                plt.savefig(f"samples/{i+1}/{name}_PCA{i+1}_{labels[j]}.png")
                plt.close()

def reconstruct_emulator(dataset,model):
    pred = model(dataset.pars).detach().numpy()
    pred = dataset.PCA_scaler.inverse_transform(pred)
    pred = dataset.pca.inverse_transform(pred)
    pred = dataset.spec_scaler.inverse_transform(pred)
    pred = 10**pred
    return pred

def loss_calc(data,model,variances):
    log_vars_ratios = np.log10(variances/np.min(variances))+1
    loss = np.mean(((model-np.asarray(data))**2)*log_vars_ratios,axis=1)
    return loss

def main():
    wrk_dir = os.getcwd()
    set_envir_vars(wrk_dir)
    
    PCA_plotting(wrk_dir,"ensemble")
    
if __name__ == "__main__":
    main()