"""
This program serves to visualise a neural network's outputs vs the true values.
"""
from sherpa.astro.ui import unpack_rmf
import torch
import os

import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap
import matplotlib.colors as colors
import matplotlib
import imageio

import numpy as np
from torch.utils.data import DataLoader
from joblib import load
from joblib import Parallel, delayed

import pandas as pd
from tqdm import tqdm

import network
from dataStructures import LoadFluxData, LoadLagsData, Losses, Residual, PCADataset
from generator import generate_test_set, readAndRemoveNans, rtdist_erg_flux, lhc_AGN, lhc_BH
import generator
from processing import saveData, nanChecker, spectraChecker
            
def inverse(scaler,data):
    """
    Transforms normalized data back to original form

    Parameters
    ----------
    scaler : scipy scaler
        scaler object that has been previously fitted on data.
    data : ndarray or other list-like object
        normalized data to transform.

    Returns
    -------
    scaled_data : ndarray
        rescaled data.

    """
    scaled_data = scaler.inverse_transform(data)
    return scaled_data

def returnContinuous(df):
    return df.data

def variances(query_samples, active_loop_num):
    #Plot distribution of variances
    plt.hist(query_samples,bins=100)
    plt.savefig(f"dists/loop_{active_loop_num}_variances.png")
    plt.close()

def distributions(data,labels,fname):
    """
    Plots distributions of parameters generated by active learning

    Parameters
    ----------
    data : ndarray or list-like object
        parameter set distribution.
    labels : ndarray or list-like object
        list of label for given parameters.
    fname : string
        save location.

    """
    for i,column in enumerate(data.T):
        plt.hist(column, bins=100, density = True)
        plt.xlabel(labels[i])
        plt.savefig(f"{fname}{labels[i]}.png")
        plt.close()

def residual_plots(egrid, pred, da, fname, title, mname, log = False, 
                   norm = False, mode = "flux"):
    """
    Plots comparison between NN model output and rtdist output with a 
    percentage residual subplot underneath.

    Parameters
    ----------
    egrid : ndarray
        energy grid to plot points on (x-axis).
    pred : ndarray
        NN model output to be plotted.
    da : ndarray
        rtdist model output to be plotted.
    fname : string
        file save location.
    title : string
        title of plot.
    mname : string
        model name.
    log : bool, optional
        If True, change y-label to be log(mode). The default is False.
    norm : bool, optional
        If True, enforce maximum range on residuals. The default is False.
    mode : string, optional
        the type of model output to be compared. Is placed as the x-label.
        The default is "flux".

    """
    pred = np.squeeze(pred)
    da = np.squeeze(da)
    fig, axs = plt.subplots(2,1,sharex=True)
    axs[0].plot(egrid,pred,c="blue",label="NN model")
    axs[0].plot(egrid,da,c="r",label="Truth",lw=1.)
    axs[0].legend()
    axs[0].set_title(title)
    if log == True:
        axs[0].set_ylabel(f"Log({mode})")
        axs[0].set_yscale("log")
    else:
        axs[0].set_ylabel(f"{mode}")
    axs[1].scatter(egrid,(da-pred)/da,s=0.5)
    axs[1].set_ylabel("Residuals")
    axs[1].set_xlabel("Energy (keV)")
    axs[1].axhline(y=0.01,ls="--",color="orange")
    axs[1].axhline(y=-0.01,ls="--",color="orange")
    axs[1].set_yscale("symlog")
    max_res = np.absolute((da-pred)/da).max()
    if max_res > 1 and norm == True:
        axs[1].set_ylim(-1,1)
    plt.tight_layout()
    plt.savefig(f"samples/{mname}_{fname}.png")
    plt.close()
    
def heatmap_plots(df, indexes, ticks, ticklabels, fname, mode):
    """
    Iterates through parameters and plots heatmaps for each parameter.

    Parameters
    ----------
    df : pandas dataframe
        residuals dataframe.
    indexes : ndarray or list-like object
        list of names of parameters.
    ticks : ndarray or list-like object
        y-tick locations to use.
    ticklabels : ndarray or list-like object
        y-tick labels for y-ticks. Must be the same length as ticks.
    fname : string
        filename to save to.
    mode : string
        signifies type of output being used.

    """
    for i,index in enumerate(indexes):
        print(index)
        df.sort_values(by=index,inplace=True,ignore_index=True)
        heatmap(df, index, ticks[i], ticklabels[i], fname, mode)

def set_envir_vars(wrk_dir):
    """
    Sets environment variables for rtdist plotting

    Parameters
    ----------
    wrk_dir : string
        location of working directory.
    """
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}

    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")

def retrieve_egrid(wrk_dir):
    """
    Find the energy grid for plotting of spectra

    Parameters
    ----------
    wrk_dir : string
        location of working directory.

    Returns
    -------
    egrid : ndarray
        energy grid values.

    """
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min
    
    return egrid

def plot_flux_corner():
    """
    Generates corner plot of all parameters vs other parameters and colours if
    the parameter set is above or below threshold (red and blue respectively)

    Returns
    -------
    None.

    """
    matplotlib.rcParams['figure.dpi'] = 100
    labels = ["height","a","inc","rin","rout","z","Gamma","Dkpc","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    
    AGN_name = "restricted_AGN"
    #generator.generate_flux_dists(AGN_name)
    
    AGN = pd.read_csv(f"data/flux/{AGN_name}.csv")
    AGN["flux"] = np.log10(AGN["flux"])
    print("Spectra over threshold:",len(AGN[AGN["flux"]>-6]))
    print("Spectra under threshold:",len(AGN[AGN["flux"]<-11]))
    
    fig, axs = plt.subplots(len(labels),len(labels), figsize=(50,50))
    for i, label_i in enumerate(labels):
        for j, label_j in enumerate(labels):
            x_bad = AGN[label_j][AGN["flux"]>-6]
            y_bad = AGN[label_i][AGN["flux"]>-6]
            x_good = AGN[label_j][(AGN["flux"]<-6)&(AGN["flux"]>-15)]
            y_good = AGN[label_i][(AGN["flux"]<-6)&(AGN["flux"]>-15)]
            x_bad_2 = AGN[label_j][AGN["flux"]<-15]
            y_bad_2 = AGN[label_i][AGN["flux"]<-15]
            axs[i,j].scatter(x_good,y_good,c = "b")
            axs[i,j].scatter(x_bad_2,y_bad_2,c = "yellow")
            axs[i,j].scatter(x_bad,y_bad,c = "r")
    
    for i in range(len(labels)):
        plt.setp(axs[-1, i], xlabel=labels[i])
        plt.setp(axs[i, 0], ylabel=labels[i])
    
    for i in range(len(labels)):
        for j in range(len(labels)):
            if j>=i:
                fig.delaxes(axs[i,j])
    plt.suptitle("Corner plot of parameters colored by flux")
    plt.tight_layout()
    plt.savefig("data/flux/pngs/corner.png")
    
def plot_flux_dists():
    labels = ["height","a","inc","rin","rout","z","Gamma","Dkpc","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    
    AGN_name = "restricted_AGN"
    #generator.generate_flux_dists(AGN_name)
    
    AGN = pd.read_csv(f"data/flux/{AGN_name}.csv")
    AGN["flux"] = np.log10(AGN["flux"])
    
    label_1 = "Afe"
    label_2 = "Gamma"
    label_3 = "z"
    
    def create_frame(angle,elev,label_1,label_2,label_3):
        """
        Plots individual frames of a gif of 3D scatter plots of two parameters
        and flux coloured by the value of another parameter.

        Parameters
        ----------
        angle : int
            angle of viewing camera.
        elev : int
            elevation of viewing camera.
        label_1 : string
            Dataframe column name of parameter to plot on x-axis.
        label_2 : string
            Dataframe column name of parameter to plot on y-axis.
        label_3 : string
            Dataframe column name of parameter to plot scatter by colour.
        """
        
        fig = plt.figure()
        ax = fig.add_subplot(projection="3d")
        
        p = ax.scatter(AGN[label_1],AGN[label_2],AGN[label_3], c = AGN["flux"],
                   cmap = "plasma")
        
        ax.set_xlabel(label_1)
        ax.set_ylabel(label_2)
        ax.set_zlabel(label_3)
        """
        #plot thresholds
        x_0 = np.linspace(AGN[label_1].min(),AGN[label_1].max(),50)
        x_1 = np.ones(50)*AGN[label_1].min()
        x_2 = np.ones(50)*AGN[label_1].max()
        y_0 = np.linspace(AGN[label_2].min(),AGN[label_2].max(),50)
        y_1 = np.ones(50)*AGN[label_2].min()
        y_2 = np.ones(50)*AGN[label_2].max()
        X, Y = np.meshgrid(x_0,y_0)
        ax.plot_surface(X, Y, -6*np.ones((len(X),len(Y))), edgecolor = "orange",
                        linewidth=0.5,
                        rstride=8, cstride=8,
                        alpha = 0.1)
        ax.plot_surface(X, Y, -11*np.ones((len(X),len(Y))), edgecolor = "orange",
                        linewidth=0.5,
                        rstride=8, cstride=8,
                        alpha = 0.1)
        #plot flux upper threshold
        ax.plot(x_0,y_1,zs=-6,c="orange",ls="--")
        ax.plot(x_0,y_2,zs=-6,c="orange",ls="--")
        ax.plot(x_1,y_0,zs=-6,c="orange",ls="--")
        ax.plot(x_2,y_0,zs=-6,c="orange",ls="--")
        #plot flux lower threshold
        ax.plot(x_0,y_1,zs=-11,c="orange",ls="--")
        ax.plot(x_0,y_2,zs=-11,c="orange",ls="--")
        ax.plot(x_1,y_0,zs=-11,c="orange",ls="--")
        ax.plot(x_2,y_0,zs=-11,c="orange",ls="--")
        """
        ax.view_init(elev=elev,azim=angle)
        fig.colorbar(p, label="flux in log(erg/cm^2/s)")
        plt.title("Flux as a function of height, inner radius and photon index")
        fig.tight_layout()
        plt.savefig(f"data/flux/frames/frame_{angle}_{elev}.png",
                    transparent = False)
        plt.close()
    
    angles = [0,10,20,30,40,50,60,70,80,90]
    elevs = [0,10,20,30,40,50,60,70,80,90]
    for angle in angles:
        for elev in elevs:
            create_frame(angle,elev,label_1,label_2,label_3)
    
    print("All frames generated")
    angles = [0,10,20,30,40,50,60,70,80,90]
    elevs = [0,10,20,30,40,50,60,70,80,90,80,70,60,50,40,30,20,10,0]
    frames = [[] for i in range(len(angles))]
    for i, angle in enumerate(angles):
        for elev in elevs:
            image = imageio.v2.imread(f'./data/flux/frames/frame_{angle}_{elev}.png')
            frames[i].append(image)
    
    for i, angle in enumerate(angles):
        imageio.mimsave(f'./data/flux/gifs/{label_1}_{label_2}_{label_3}_{angle}.gif', # output gif
                    frames[i],                      # array of input frames
                    duration = 500,                 # optional: duration of frame
                    loop = 1)        
        
    for label in labels:
        plt.scatter(AGN[label],AGN["flux"])
        plt.axhline(-15, ls="--", c ="orange")
        plt.axhline(-6, ls="--", c ="orange")
        plt.xlabel(label)
        plt.ylabel("Flux in log(erg/s/cm^2)")
        plt.title(f"How flux trends with {label} for AGN")
        plt.savefig(f"data/flux/pngs/{label}_{AGN_name}.png")
        plt.close()
    
    flux_AGN = AGN["flux"][np.isnan(AGN["flux"])==False]
    flux_AGN = flux_AGN[(flux_AGN>-18)]
    
    print(len(flux_AGN[(flux_AGN > -15)& (flux_AGN < -6)]))

def plot_flux_ranges_corner():
    labels = ["h","a","inc","rin","rout","z","Gamma","Dkpc","Afe","logNe",
              "kTe","nH","boost","Mass","honr","b1","b2","phiAB","g","Anorm"]
    
    AGN_name = "restricted_AGN"
    generator.generate_flux_dists(AGN_name)
    AGN = pd.read_csv(f"data/flux/{AGN_name}_range.csv")
    
    pars_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,21,22,23]
    negatives = [3]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    
    AGN.iloc[:,negatives] = -AGN.iloc[:,negatives]
    AGN.iloc[:,logged] = np.log10(AGN.iloc[:,logged]) 
    
    max_photons = []
    for spec in AGN["Location"]:
        spectra = np.loadtxt(spec)
        max_photons.append(spectra.max())
    
    max_photons = np.log10(max_photons)
    AGN["max"] = max_photons
    
    fig, axs = plt.subplots(len(labels),len(labels), figsize=(25,25))
    for i, label_i in enumerate(labels):
        for j, label_j in enumerate(labels):
            p = axs[i,j].scatter(AGN[label_j],AGN[label_i],c = max_photons, 
                             s = 2, cmap = "plasma")
    
    for i in range(len(labels)):
        plt.setp(axs[-1, i], xlabel=labels[i])
        plt.setp(axs[i, 0], ylabel=labels[i])
    
    for i in range(len(labels)):
        for j in range(len(labels)):
            if j != 0 and i != len(labels)-1:
                axs[i,j].xaxis.set_tick_params(labelbottom=False)
                axs[i,j].yaxis.set_tick_params(labelleft=False)
                axs[i,j].set_xticks([])
                axs[i,j].set_yticks([])
            elif j == 0 and i != len(labels)-1:
                axs[i,j].xaxis.set_tick_params(labelbottom=False)
                axs[i,j].set_xticks([])
            elif j != 0 and i == len(labels)-1:
                axs[i,j].yaxis.set_tick_params(labelleft=False)
                axs[i,j].set_yticks([])
    for i in range(len(labels)):
        for j in range(len(labels)):
            if j>=i:
                fig.delaxes(axs[i,j])
    plt.suptitle("Corner plot of parameters colored by max photons")
    fig.subplots_adjust(right=0.8)
    cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
    fig.colorbar(p, cax=cbar_ax, label="maximum photons/cm/s/keV")
    matplotlib.rcParams.update({'font.size': 36})
    plt.savefig("data/flux/pngs/corner_ranges.png")
        

def model_load(model_loc, egrid, lags = None):
    """
    Loads neural network model states from the disk. Can load both the flux and
    lag neural network model types.

    Parameters
    ----------
    model_loc : string
        location of the file with neural network parameters.
    egrid : ndarray
        energy grid values.
    lags : any, optional
        If this is not None, assumes loading a time lags model. The default is 
        None.

    Returns
    -------
    model : pytorch model
        the desired pytorch neural network model.

    """
    if lags == None:
        model = network.HeavyFluxNetwork(5, len(egrid))
    else:
        model = network.HeavyLagsNetwork(5, len(egrid))
    model.load_state_dict(torch.load(model_loc))
    model.eval()
    return model
    
def residual_sorting(df,indexing):
    """
    Sorts residual dataframe by the given index and returns the 0.01, 0.25, 
    0.5, 0.75 percentile values as tick labels

    Parameters
    ----------
    df : pandas dataframe
        dataframe containing residuals and their corresponding parameters.
    indexing : string
        name of the column to sort dataframe by.

    Returns
    -------
    tick : list
        list of tick values index.
    ticklabel : list
        list of tick values.

    """
    df.sort_values(by=indexing,inplace=True,ignore_index=True)
    percents = [0,0.25,0.5,0.75]
    tick = []
    ticklabel = []
    for p in percents:
        tick.append(int(len(df)*p))
        ticklabel.append(f"{df[indexing][int(len(df)*p)]:.2f}")
    return tick,ticklabel

def residual_computation(dataloader, model, scaler, mode):
    """
    Computes and records residual differences between neural network outputs
    and rtdist outputs. Records them with the parameters. For data and model
    outputs below a threshold, we consider the residual difference to be 0.

    Parameters
    ----------
    dataloader : pytorch dataloader
        contains test data and parameters.
    model : pytorch model
        neural network model to compare results to.
    scaler : scikitlearn MinMaxScaler
        scaler to change network output back to real output.
    mode : string
        signifies if using a time lags or flux model.

    Returns
    -------
    dataframe : pandas dataframe
        contains residuals and parameters.
    ticks : list
        list of lists of tick indexes for each parameter.
    ticklabels : list
        list of lists of tick values for each parameter.

    """
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    logged = [1,2,3,4]
    pars_list = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    pars_list = ["a","inc","rin","rout","mass"]
    pars = [[] for i in range(len(pars_list))]
    residuals = []
    for batch, (D,P) in enumerate(tqdm(dataloader)):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-10] = 1e-10
            D = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-5)] = -1e-5
            D[(D>=0)&(np.abs(D)<1e-5)] = 1e-5
            D = np.squeeze(D)
        for i in range(len(pars)):
            if i in logged:
                pars[i].append(10**P[0][i].item())
            else:
                pars[i].append(P[0][i].item())
        if mode == "flux":
            pred = model(P).detach().numpy()
            pred = 10**(inverse(scaler,pred))
        else:
            pred, I_pred = model(P)
            pred = 10**(inverse(scaler,pred.detach().numpy()))
        if mode != "flux":
            pred = pred*np.where(I_pred.detach().numpy() > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.numpy()
        if mode == "flux":
            resid = np.where((np.abs(D)<=1e-10)&(np.abs(pred)<=1e-10),0,resid)
            resid = np.where((np.abs(D)==0),0,resid)
        else:
            resid = np.where((np.abs(D)<=1e-5)&(np.abs(pred)<=1e-5),0,resid)
        resid = np.absolute(np.asarray(resid))
        residuals.append(resid)
        
    residuals = np.squeeze(np.asarray(residuals))
    obj_residuals = []
    for res in residuals:
        obj_residuals.append(Residual(res))
    
    data = {}
    for i,label in enumerate(pars_list):
        data[label] = pars[i]
    data["residuals"] = obj_residuals
    
    dataframe = pd.DataFrame.from_dict(data)
    ticks = []
    ticklabels = []
    for label in pars_list:
        tick, ticklabel = residual_sorting(dataframe, label)
        ticks.append(tick)
        ticklabels.append(ticklabel)
    
    return (dataframe, ticks, ticklabels)

def calculate_loss(testing_dataloader, model, scaler, mode = "flux"):
    """
    

    Parameters
    ----------
    testing_dataloader : TYPE
        DESCRIPTION.
    model : TYPE
        DESCRIPTION.
    scaler : TYPE
        DESCRIPTION.
    mode : TYPE, optional
        DESCRIPTION. The default is "flux".

    Returns
    -------
    residuals : TYPE
        DESCRIPTION.

    """
    residuals = []
    for batch, (D,P) in enumerate(tqdm(testing_dataloader)):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-11] = 1e-11
            D = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-6)] = -1e-6
            D[(D>=0)&(np.abs(D)<1e-6)] = 1e-6
            D = np.squeeze(D)
        if mode == "flux":
            pred = model(P)
        else:
            pred, I_pred = model(P)
            I_pred = I_pred.detach().numpy()
        pred = pred.detach().numpy()
        pred = 10**(inverse(scaler,pred))
        if mode != "flux":
            pred = pred*np.where(I_pred > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.detach().numpy()
        if mode == "flux":
            resid = np.where((np.abs(D)<=1e-10)&(np.abs(pred)<=1e-10),
                             0,resid)
        else:
            resid = np.where((np.abs(D)<=1e-5)&(np.abs(pred)<=1e-5),
                             0,resid)
        residuals.append(np.absolute(np.asarray(resid)))
    residuals = np.asarray(residuals)
    return residuals

def residuals_dataframe(residuals,names):
    d = {"Residuals":[],"Sample Size":[]}
    for i,name in enumerate(names):
        print(name)
        for point in residuals[i].flatten():
            d["Residuals"].append(point)
            d["Sample Size"].append(name) 
    print("# of residuals:"+str(len(d["Residuals"])))
    print("# of labels:"+str(len(d["Sample Size"])))
    df = pd.DataFrame(data = d)
    return df

def model_samples(testing_dataloader,scaler,model,egrid,mname,mode,no_brk=5):
    for batch, (D,P) in enumerate(testing_dataloader):
        D = np.squeeze(D)
        if mode == "flux":
            D[D<=1e-11] = 1e-11
            da = np.squeeze(D)
        else:
            D[(D<=0)&(np.abs(D)<1e-6)] = -1e-6
            D[(D>=0)&(np.abs(D)<1e-6)] = 1e-6
            da = np.squeeze(D)
        
        da_log = np.log10(np.abs(da))
        da_log_scal = scaler.transform(da_log.reshape(1, -1)).flatten()
        if mode == "flux":
            pred = model(P)
        else:
            pred, I_pred = model(P)
        log_pred = inverse(scaler,pred.detach().numpy())
        pred = pred.detach().numpy()
        sca_pred = np.squeeze(10**(log_pred))
        #generate neural network prediction and rescale to linear space
        if mode == "flux":
            sca_pred[sca_pred<=1e-11] = 1e-11
        else:
            sca_pred[sca_pred<1e-6] = 1e-6
            sca_pred = np.squeeze(sca_pred*np.where(I_pred > 0.5, 1, -1))
        
        fname = f"{batch}"
        title = "Direct comparison"
        
        residual_plots(egrid, sca_pred, da, fname, title, mname, norm = True, mode = mode)
        
        fname = f"{batch}_log"
        title = "Log scaled output"
        residual_plots(egrid, log_pred, da_log, fname, title, mname, 
                       mode = mode)
        fname = f"{batch}_scal"
        title = "Neural network normalised output"
        residual_plots(egrid, pred, da_log_scal, fname, title, mname, 
                       mode = mode)
            
        if batch > no_brk:
            break

def heatmap(df, index, ticks, ticklabels, fname, mode):
    zlabel = "Fractional difference between NN model and rtdist"
    Z_center = -2.5
    #colormap
    top = cm.get_cmap('autumn', 128)
    bottom = cm.get_cmap('winter', 128)
    middle = cm.get_cmap('summer',128)

    newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                           middle(np.linspace(0, 1/2, 128)),
                        top(np.linspace(2/3, 1, 128))))
    newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
    
    residuals = df["residuals"].apply(returnContinuous)
    resids = []
    for item in residuals:
        resids.append(item)
    resids = np.asarray(resids)
    
    fig = plt.figure(figsize=(10,10))
    norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
    ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
    c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
    cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm)
    plt.yticks(ticks,labels=ticklabels)
    if mode == "flux":
        plt.xticks(np.arange(0,4096,4096/4), labels=np.arange(0,20,5))
    else:
        egrid = np.logspace(np.log10(0.5),np.log10(11),num=26)[:-1]
        tick_index = np.arange(0,25,24/4).astype(int)
        plt.xticks(tick_index, labels=np.round(egrid[tick_index],2))
    plt.xlabel("Energy in keV")
    plt.ylabel(index)
    
    cbar.set_label(zlabel, rotation=270, labelpad=15)
    fig.tight_layout()
    matplotlib.rcParams.update({'font.size': 16})
    plt.savefig(f"heatmaps/{fname}_{index}.png")
    plt.close()
    return

def plot_loss_vs_sample_size(grid_sample_nums=[], grid=[], 
                             active_sample_nums=[], active=[],
                             mode="flux",single=False):
    if single == False:
        fig , axs = plt.subplots(1,2,sharey=True, sharex=True, figsize=(12,9))
        
        for (x,y,z) in zip(grid_sample_nums,grid.low,grid.high):
            axs[0].scatter([x]*len(y),y, s=1, color="orange", zorder = 1, marker = "x",
                           alpha = 0.5)
            axs[0].scatter([x]*len(z),z, s=1, color="orange", zorder = 1, marker = "x",
                           alpha = 0.5)
            
        axs[0].fill_between(grid_sample_nums, grid.q_95, 
                         grid.q_5, alpha = 0.25,color = "orange",
                         zorder=3)
        axs[0].fill_between(grid_sample_nums, grid.q_75, 
                         grid.q_25, alpha = 0.5,color = "orange",
                         zorder=4)
        axs[0].fill_between(grid_sample_nums, grid.q_99, 
                         grid.q_1, alpha = 0.5,color = "orange",
                         zorder=2)
        axs[0].plot(grid_sample_nums,grid.median,label="Grid",color = "orange",
                 zorder=5)
        
        for (x,y,z) in zip(active_sample_nums,active.low,active.high):
            axs[1].scatter([x]*len(y),y, s=1, color="blue", zorder = 2, marker = "x",
                           alpha = 0.5)
            axs[1].scatter([x]*len(z),z, s=1, color="blue", zorder = 2, marker = "x",
                           alpha = 0.5)
            
        axs[1].fill_between(active_sample_nums, active.q_95, 
                         active.q_5, alpha = 0.25,color = "blue",
                         zorder=3)
        axs[1].fill_between(active_sample_nums, active.q_75, 
                         active.q_25, alpha = 0.5,color = "blue",
                         zorder=4)
        axs[1].fill_between(active_sample_nums, active.q_99, 
                         active.q_1, alpha = 0.5,color = "blue",
                         zorder=2)
        axs[1].plot(active_sample_nums,active.median,label="Active learning",
                 color = "blue",zorder=5)
        
        axs[0].axhline(y=1e-2, ls = "--",label="1% error",zorder=6,color="green")
        axs[1].axhline(y=1e-2, ls = "--",zorder=6,color="green")
        axs[0].axhline(y=1e-3, ls = "dashdot",label="0.1% error",zorder=7,color="red")
        axs[1].axhline(y=1e-3, ls = "dashdot",zorder=7,color="red")
        
        plt.yscale("log")
        
        plt.yticks([1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1e0,1e1])
        fig.suptitle(f"Loss by sample size for {mode}")
        
        fig.supxlabel("Number of samples used in training")
        fig.supylabel("Residuals")
        lines = []
        labels = []
          
        for ax in fig.axes:
            Line, Label = ax.get_legend_handles_labels()
            # print(Label)
            lines.extend(Line)
            labels.extend(Label)
            
        fig.legend(lines, labels, loc='upper right')
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"loss/loss_size_{mode}.png")
        plt.close()
    else:
        if grid_sample_nums != []:
            pass
        elif active_sample_nums != []:
            for (x,y,z) in zip(active_sample_nums,active.low,active.high):
                plt.scatter([x]*len(y),y, s=1, color="blue", zorder = 2, marker = "x",
                               alpha = 0.5)
                plt.scatter([x]*len(z),z, s=1, color="blue", zorder = 2, marker = "x",
                               alpha = 0.5)
                
            plt.fill_between(active_sample_nums, active.q_95, 
                             active.q_5, alpha = 0.25,color = "blue",
                             zorder=3)
            plt.fill_between(active_sample_nums, active.q_75, 
                             active.q_25, alpha = 0.5,color = "blue",
                             zorder=4)
            plt.fill_between(active_sample_nums, active.q_99, 
                             active.q_1, alpha = 0.5,color = "blue",
                             zorder=2)
            plt.plot(active_sample_nums,active.median,label="Active learning",
                     color = "blue",zorder=5)
            
            plt.axhline(y=1e-2, ls = "--",label="1% error",zorder=6,color="green")
            plt.axhline(y=1e-3, ls = "dashdot",label="0.1% error",zorder=7,color="red")
            
            plt.yscale("log")
            
            plt.yticks([1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1e0,1e1])
            plt.title(f"Loss by sample size for {mode}")
            
            plt.xlabel("Number of samples used in training")
            plt.ylabel("Residuals")
            lines = []
            labels = []
                
            plt.legend(lines, labels, loc='upper right')
            plt.savefig(f"loss/loss_size_{mode}.png")
            plt.close()

def loss_epochs_plot(loss_base_loc,mode):
    
    train_names = [loss_base_loc+f"grid_{i}_{mode}_tr_loss.txt" for i in range(5,11)]
    test_names = [loss_base_loc+f"grid_{i}_{mode}_te_loss.txt" for i in range(5,11)]
    
    active_loss = np.loadtxt(loss_base_loc+f"36_{mode}_tr_loss.txt")
    active_test = np.loadtxt(loss_base_loc+f"36_{mode}_te_loss.txt")
    
    plt.plot(np.loadtxt(train_names[-1]), label="Training loss: 10x10 grid", 
             c = "red", ls = "-")
    plt.plot(np.loadtxt(test_names[-1]), label = "Validation loss: 10x10 grid", 
             c = "red", ls = "--")
    
    plt.plot(active_loss,label = "Training loss: active learning", c = "blue",
             ls = "-")
    plt.plot(active_test,label = "Validation loss: active learning", c = "blue",
             ls = "--")
    
    plt.yscale("log")
    plt.xlabel("Training epochs")
    plt.ylabel("Loss")
    plt.title(f"Comparison of loss by strategy for {mode}")
    plt.legend()
    plt.savefig(f"loss/loss_time_{mode}.png")
    plt.close()

def plot_spec_dist(egrid,flux,pars):
    labels = ["height","a","inc","rin","rout","z","Gamma","Dkpc","Afe",
              "logNe","kte","nH","boost","mass","honr","b1","b2","fmin","fmax",
              "ReIM","phiA","phiAB","g","Anorm","RESP","Xnorm"]
    
    labels = ["a","inc","rin","distance","mass"]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    
    pars[:,3] = -pars[:,3]
    
    e_mid = (egrid[1:] + egrid[:-1])/2
    e_mid = e_mid * 1.60218e-9 #convert to erg
    hist_F = []
    bad_pars = []
    for i,fl in enumerate(flux):
        fl_int = fl[:-1]*e_mid
        fl_int = fl_int.sum()
        if fl_int < 0:
            pars_print = pars[i]
            pars_print[3] = -pars_print[3]
            print(pars_print)
            print(fl)
            print(fl[:-1]*e_mid)
            bad_pars.append(pars[i])
        hist_F.append(fl_int)
    
    bad_pars = np.asarray(bad_pars)
    for i in range(bad_pars.shape[1]):
        if i in logged:
            hist, bins, _ = plt.hist(bad_pars[:,i],bins=20)
            plt.close()
            logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
            plt.hist(bad_pars[:,i], bins=logbins)
            plt.xlabel(f"log({labels[i]})")
            plt.xscale("log")
        else:
            plt.hist(bad_pars[:,i])
            plt.xlabel(f"{labels[i]}")
        plt.ylabel("Occurences")
        plt.title(f"Parameters yielding negative fluxs for {labels[i]}")
        plt.savefig(f"verify/bad_{labels[i]}.png")
        plt.close()
    
    hist_F = np.asarray(hist_F)
    hist_F = hist_F[hist_F > 0]
    hist, bins, _ = plt.hist(hist_F,bins=100)
    plt.close()
    logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
    plt.hist(hist_F, bins=logbins)
    plt.xlabel("Flux (erg/cm^2/s)")
    plt.ylabel("Occurences")
    plt.xscale("log")
    plt.title("Histogram of total fluxes generated in test set")
    plt.savefig("verify/hist.png")
    plt.close()
    
    segs = [np.column_stack([egrid[:-1], fl[:-1]*e_mid]) for fl in flux]
    
    for par in range(pars.shape[1]):
        fig, ax = plt.subplots()
        lc = matplotlib.collections.LineCollection(segs, array = pars[:,par],
                                                   alpha = 0.3)
        ax.add_collection(lc)
        axcb = fig.colorbar(lc)
        axcb.set_label(f"{labels[par]}")
        ax.set_title(f"Colored by {labels[par]}")
        ax.set_ylabel("erg/cm^2/s")
        ax.set_xlabel("Energy (keV)")
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlim(5e-2)
        ax.set_ylim(1e-20)
        plt.savefig(f"verify/specs_{labels[par]}.png")
        plt.close()
    
def check_uniques(array1,array2):
    combo = pd.concat([array1,array2])
    combo.drop_duplicates(keep=False)
    return combo

def aggregate_dists(files):
    nbins = 100
    
    labels = ["0th loop", "10th loop", "20th loop", "30th loop", "40th loop"]
    pars_list = ["h","a","inc","rin","rout","z","Gamma","Dkpc","Afe","logNe",
                    "kTe","nH","boost","Mass","honr","b1","b2","phiAB","g",
                    "Anorm"]
    
    pars_list = ["a","inc","rin","rout","mass"]
    
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    negatives = [3]
    
    full_pars = [[] for i in range(len(pars_list))]
    
    last_pars = pd.DataFrame()
    for file in files:
        print(file)
        df = pd.read_csv(file)
        pars = df.loc[:, df.columns!="Location"]
        new_pars = check_uniques(pars,last_pars)
        last_pars = pars
        for item in range(len(pars_list)):
            new_pars_list = new_pars.loc[:,pars_list[item]]
            if item in negatives:
                new_pars_list = -1*new_pars_list
            if item in logged:
                new_pars_list = np.log10(new_pars_list)
            full_pars[item].append(new_pars_list)
    cmap = cm.get_cmap("Wistia")(np.linspace(0, 1, len(labels)))
    
    pars_bins = []
    
    for i, item in enumerate(pars_list):
        hist, bins, _ = plt.hist(full_pars[i], nbins, histtype="bar", 
                                 stacked=True)
        logbins = np.logspace(np.log10(bins[0]),np.log10(bins[-1]),len(bins))
        pars_bins.append(logbins)
        plt.close()
    
    fig, axs = plt.subplots(4,5,sharey=True,figsize=(12,9))
    matplotlib.rcParams.update({'font.size': 16})
    
    for i, item in enumerate(pars_list):
        x = np.floor(i/5)
        y = i%5
        axs[x,y].hist(full_pars[i], pars_bins[i], 
                      histtype="bar", stacked=True, color = cmap, label=labels)
        if i in logged:
            axs[x,y].set_xscale("log")
        axs[x,y].set_xlabel(pars_list[i])
    plt.yscale("log")
    plt.savefig("dists/stacked.png")
    plt.close()
    

def analysis(names, locs, nums, scaler_names, egrid, lags = None):
    if lags != None:
        mode = "lags"
    else:
        mode = "flux"
    scaler_base_loc = os.getcwd()+"/scalers/"
    indexes = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    
    indexes = ["a","inc","rin","rout","mass"]
    median_loss = []
    loss_01_q = []
    loss_05_q = []
    loss_25_q = []
    loss_75_q = []
    loss_95_q = []
    loss_99_q = []
    loss_low_out = []
    loss_high_out = []
    
    resid_list = []
    
    pars_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,21,22,23]
    negatives = [3]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    
    pars_list = [1,2,3,4,13]
    negatives = [2]
    logged = [1,2,3,4]
    
    if type(scaler_names) != list:
        tmp = [scaler_names for i in range(len(names))]
        scaler_names = tmp
        
    for (model_loc,fname,scaler_name) in zip(locs, names, scaler_names):
        scaler = load(scaler_base_loc+scaler_name)
        #put test set into dataloader format
        batch_size = 1
        if lags == None:
            test_data = LoadFluxData("data/locations/loc_flux_AGN_test.csv",scaler,
                                      scaler_name, pars_list, negatives = negatives, 
                                      logged = logged) #scaler unused but must be parsed
            model = model_load(model_loc, egrid, lags = lags)
        else:
            test_data = LoadLagsData("data/locations/loc_lags_AGN_test.csv",scaler,
                                       scaler_name, pars_list, negatives = negatives, 
                                       logged = logged) #scaler unused but must be parsed
            model = model_load(model_loc, egrid[:-1], lags = lags)
        
        testing_dataloader = DataLoader(test_data,batch_size = batch_size,
                                        num_workers=1,shuffle=True)
        #folname = str(fname)
        fname = f"{fname}_{mode}"
        print(fname)
        residuals = calculate_loss(testing_dataloader, model, scaler, mode)
        resid_list.append(residuals)
        median = np.median(residuals)
        q_01,q_05, q_25, q_75, q_95, q_99 = np.quantile(residuals,
                                                        [0.01,0.05,0.25,0.75,
                                                         0.95,0.99])
        median_loss.append(median)
        loss_05_q.append(q_05)
        loss_25_q.append(q_25)
        loss_75_q.append(q_75)
        loss_95_q.append(q_95)
        loss_99_q.append(q_99)
        loss_01_q.append(q_01)
        if mode == "flux":
            filt = 1000
        else:
            filt = 1
        high_outliers = residuals[residuals >= np.percentile(residuals, 99)][::filt]
        low_outliers = residuals[residuals <= np.percentile(residuals, 1)][::filt]
        loss_low_out.append(low_outliers)
        loss_high_out.append(high_outliers)
        if lags == None:
            model_samples(testing_dataloader, scaler, model, egrid, fname, 
                          mode)
        else:
            model_samples(testing_dataloader, scaler, model, egrid[:-1], fname, 
                          mode)
        df, ticks, ticklabels = residual_computation(testing_dataloader, 
                                                     model, scaler, mode)
        heatmap_plots(df, indexes, ticks, ticklabels, fname, mode)
        del df, ticks, ticklabels
        
    resid_list = np.asarray(resid_list)
    df = residuals_dataframe(resid_list, nums)
    large_resid = df[df["Sample Size"] == df["Sample Size"].max()].max()[0]
    print(f"The largest residual was {large_resid}")
    over = len(df[(df["Sample Size"] == df["Sample Size"].max())&(df["Residuals"] >= 0.01)])
    print(f"There were {over} residuals over 1%")
    overall = len(df[df["Sample Size"] == df["Sample Size"].max()])
    print(f"There were {overall} residuals overall")
    print(f"The ratio of residuals over 1% was {over/overall}")
    
    quantiles = [loss_01_q, loss_05_q, loss_25_q,
                 loss_75_q, loss_95_q, loss_99_q,
                 loss_high_out, loss_low_out, median_loss]
    quantile_names = ["q_1", "q_5", "q_25", "q_75", "q_95", "q_99", "high", 
                      "low", "median"]
    quants = Losses()
    for quant_arr, quant_name in zip(quantiles,quantile_names):
        quants.set_loss(quant_arr,quant_name)
    
    return quants

def active_v_grid(wrk_dir, egrid, lags_egrid):
    model_base_loc = wrk_dir+"/models/"
    loss_base_loc = wrk_dir+"/loss/"
    
    active_name = [0,10,20,30,40]
    active_name = np.array(active_name)
    active_sample_flux_nums = []
    active_sample_lags_nums = []
    for name in active_name:
        active_sample_flux_nums.append(len(pd.read_csv(f"data/locations/loc_flux_{name}.csv")))
        active_sample_lags_nums.append(len(pd.read_csv(f"data/locations/loc_lags_{name}.csv")))
    print(active_sample_flux_nums)
    active_flux_names = [f"{model_base_loc}{i}_flux_model.pth" for i in active_name]
    active_lags_names = [f"{model_base_loc}{i}_lags_model.pth" for i in active_name]
    active_flux_names[-1] = f"{model_base_loc}short_active_flux_final.pth"
    active_lags_names[-1] = f"{model_base_loc}short_active_lags_final.pth"
    grid_flux_name = [f"grid_{i}" for i in range(5,11)]
    grid_lags_name = [f"grid_{i}" for i in range(5,11)]
    grid_flux_scaler = [f"grid_{i}_flux_scaler.bin" for i in range(5,11)]
    grid_lags_scaler = [f"grid_{i}_lags_scaler.bin" for i in range(5,11)]
    active_flux_scaler = "short_active_scaler_flux.bin"
    active_lags_scaler = "short_active_scaler_lags.bin"
    grid_model_names = np.array([5,6,7,8,9,10])
    grid_sample_nums = grid_model_names**5
    grid_model_flux_names = [model_base_loc+f"grid_{i}_flux.pth" for i in grid_model_names]
    grid_model_lag_names = [model_base_loc+f"grid_{i}_lags.pth" for i in grid_model_names]
    
    loss_epochs_plot(loss_base_loc,"flux")
    loss_epochs_plot(loss_base_loc,"lags")

    active_flux = analysis(active_name, active_flux_names, active_sample_flux_nums, 
                           active_flux_scaler, egrid)
    
    active_lags = analysis(active_name, active_lags_names, active_sample_lags_nums, 
                           active_lags_scaler, lags_egrid, lags=True)
    
    grid_flux = analysis(grid_flux_name, grid_model_flux_names, grid_sample_nums,
                            grid_flux_scaler, egrid)
    
    grid_lags = analysis(grid_lags_name, grid_model_lag_names, grid_sample_nums,
                            grid_lags_scaler, lags_egrid, lags=True)
    
    print("Plotting loss by sample size")
    print("Plotting fluxes")
    plot_loss_vs_sample_size(grid_sample_nums, grid_flux,
                             active_sample_flux_nums, active_flux, mode="flux")
    print("Plotting lags")
    plot_loss_vs_sample_size(grid_sample_nums, grid_lags,
                             active_sample_lags_nums, active_lags, mode="lags")
    
    loss_epochs_plot("loss/", "flux")
    loss_epochs_plot("loss/", "lags")
    
def PCA_plotting(wrk_dir):
    """
    Function dedicated to plotting PCA neural network model outputs. Only plots
    things necessary for PCA model diagnosis

    Parameters
    ----------
    wrk_dir : string
        current working directory location.

    Returns
    -------
    None.

    """
    #plotting of training and validation loss over time
    PCA_train_loss = np.loadtxt("loss/PCA_flux_tr_loss.txt")
    PCA_val_loss = np.loadtxt("loss/PCA_flux_te_loss.txt")
    
    plt.plot(PCA_train_loss,label = "Training loss", c = "blue",
             ls = "-")
    plt.plot(PCA_val_loss,label = "Validation loss", c = "blue",
             ls = "--")
    
    plt.yscale("log")
    plt.xlabel("Training epochs")
    plt.ylabel("Loss")
    plt.title(f"Loss by epoch")
    plt.legend()
    plt.savefig(f"loss/loss_PCA.png")
    plt.close()
    
    #plotting of emulator vs test data performance
    pars_list = [1,2,3,4,13]
    negatives = [3]
    logged = [2,3,4,13]
    labels = ["a","inc","rin","rout","mass"]
    test_data = PCADataset("data/locations/loc_flux_test.csv",
                               pars_list,negatives,logged,scale_bool = False)
    
    model = network.PCAFluxNetwork(len(pars_list), test_data.pca.components_.shape[0])
    
    model.load_state_dict(torch.load("models/PCA_flux.pth"))
    model.eval()
    
    loss = loss_calc(test_data.data, model(test_data.pars).detach().numpy())
    
    for j in range(test_data.pars.shape[1]):
        plt.scatter(test_data.pars[:,j],loss)
        plt.xlabel(labels[j])
        plt.ylabel("Loss")
        plt.savefig(f"loss/loss_by_{labels[j]}.png")
        plt.close()
    
    data = []
    for file in test_data.locations:
        data.append(np.loadtxt(file).reshape(1, -1))
    D = np.concatenate(data,axis=0)
    D[D<1e-11] = 1e-11
    
    test_pred, test_spec = reconstruct_emulator(test_data, model)
    
    recon_resid = np.abs((D-test_spec))
    recon_perc = np.abs((D-test_spec)/test_spec)
    plt.plot(np.mean(recon_resid,axis=0))
    plt.xlabel("Energy channel")
    plt.ylabel("Mean absolute error")
    plt.savefig("samples/PCA_mean_error.png")
    plt.close()
    plt.plot(np.mean(recon_perc,axis=0))
    plt.xlabel("Energy channel")
    plt.ylabel("Mean fractional error")
    plt.savefig("samples/PCA_mean_perc.png")
    plt.close()
    print(f"average percentage error: {recon_perc.mean()}")
    
    resid_list = ["Absolute","Percentage"]
    for resid,label in zip([recon_resid,recon_perc],resid_list):
        sort_ind = np.argsort(test_data.pars[:,0])
        sort_par = test_data.pars[sort_ind,0]
        percents = np.array([0,0.25,0.5,0.75,0.99])
        ticks = (len(sort_par)*percents).astype(int)
        tick_labels = sort_par[(len(sort_par)*percents).astype(int)]
        resids = resid[sort_ind]
        zlabel = "Difference between PCA reconstruction and rtdist"
        """
        Z_center = -2.5
        #colormap
        top = cm.get_cmap('autumn', 128)
        bottom = cm.get_cmap('winter', 128)
        middle = cm.get_cmap('summer',128)
    
        newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                               middle(np.linspace(0, 1/2, 128)),
                            top(np.linspace(2/3, 1, 128))))
        newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
        """
        fig = plt.figure(figsize=(10,10))
        ax = plt.pcolormesh(resids)
        cbar = plt.colorbar(format='%.0e')
        plt.yticks(ticks,labels=tick_labels)
        plt.xticks(np.arange(0,4096,4096/4), labels=np.arange(0,20,5))
        plt.xlabel("Energy in keV")
        plt.ylabel("Spin")
        
        cbar.set_label(zlabel, rotation=270, labelpad=15)
        fig.tight_layout()
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"heatmaps/{label}.png")
        plt.close()
    
    residuals = np.abs((test_pred-test_spec)/test_spec)
    print(f"Maximum residual is {residuals.max()}")
    print(f"Average residual is {residuals.mean()}")
    print(f"{residuals[residuals<0.01].size/residuals.size}% of residuals are below 1%")
    
    plt.plot(np.mean(residuals,axis=0))
    plt.xlabel("Energy channel")
    plt.ylabel("Mean percentage residual")
    plt.savefig("samples/mean_errors.png")
    plt.close()
    
    for i in range(len(pars_list)):
        sort_ind = np.argsort(test_data.pars[:,i])
        sort_par = test_data.pars[sort_ind,i]
        percents = np.array([0,0.25,0.5,0.75,0.99])
        ticks = (len(sort_par)*percents).astype(int)
        tick_labels = sort_par[(len(sort_par)*percents).astype(int)]
        resids = residuals[sort_ind]
        zlabel = "Fractional difference between NN model and rtdist"
        Z_center = -2.5
        #colormap
        top = cm.get_cmap('autumn', 128)
        bottom = cm.get_cmap('winter', 128)
        middle = cm.get_cmap('summer',128)

        newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                               middle(np.linspace(0, 1/2, 128)),
                            top(np.linspace(2/3, 1, 128))))
        newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
        
        fig = plt.figure(figsize=(10,10))
        norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
        ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
        c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                    10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
        cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm)
        plt.yticks(ticks,labels=tick_labels)
        plt.xticks(np.arange(0,4096,4096/4), labels=np.arange(0,20,5))
        plt.xlabel("Energy in keV")
        plt.ylabel(labels[i])
        
        cbar.set_label(zlabel, rotation=270, labelpad=15)
        fig.tight_layout()
        matplotlib.rcParams.update({'font.size': 16})
        plt.savefig(f"heatmaps/{labels[i]}.png")
        plt.close()
    
    print("Plotting samples")
    i = 0
    for pred, D in zip(test_pred, test_spec):
        fig, axs = plt.subplots(2)
        axs[0].plot(pred,label="Emulator")
        axs[0].plot(D,label="Rtdist", ls = "--")
        axs[0].set_ylabel("Flux (photons/cm^2/s/channel)")
        axs[0].legend()
        axs[1].plot((pred-D)/D)
        axs[1].set_ylabel("Percentage residuals")
        fig.supxlabel("Energy channel")
        fig.suptitle("Comparison of PCA emulator output vs expected")
        plt.tight_layout()
        plt.savefig(f"samples/PCA_compare_{i}.png")
        plt.close()
        i += 1
        if i > 6:
            break
    
    nn_comps = model(test_data.pars).detach().numpy()
    train_comps = test_data.data
    pars_comps = test_data.pars
    
    for j in range(pars_comps.shape[1]):
        for i in range(nn_comps.shape[1]):
            plt.scatter(pars_comps[:,i],train_comps[:,i],label="Training set")
            plt.scatter(pars_comps[:,i],nn_comps[:,i],label="Emulator")
            plt.legend()
            plt.xlabel(labels[j])
            plt.ylabel(f"PCA component {i+1}")
            plt.savefig(f"samples/PCA{i+1}_{labels[j]}.png")
            plt.close()

def reconstruct_emulator(dataset,model):
    pred = model(dataset.pars).detach().numpy()
    pred = dataset.PCA_scaler.inverse_transform(np.squeeze(pred))
    data = dataset.PCA_scaler.inverse_transform(dataset.data)
    pred = dataset.pca.inverse_transform(pred)
    data = dataset.pca.inverse_transform(data)
    pred, data = 10**pred, 10**data
    return pred, data

def loss_calc(data,model):
    loss = np.mean((model-np.asarray(data))**2,axis=1)
    return loss

def main():
    wrk_dir = os.getcwd()
    """
    egrid = retrieve_egrid(wrk_dir)
    lags_egrid = np.logspace(np.log10(0.5),np.log10(11),num=26)
    range_AGN = np.asarray(generator.lhc_trimmed_gen())
    num_pars = range_AGN.shape[0]
    
    theta_lhc = generator.lhc_generation(int(1e3), range_AGN, limited=True)
    pars_list = [1,2,3,4,13]
    negatives = [3]
    logged = [2,3,4,13]
    theta_flux = generator.nn_pars_to_rtdist(theta_lhc, 0, pars_list, negatives, logged)
    theta_lags = generator.nn_pars_to_rtdist(theta_lhc, 0, pars_list, negatives, logged)
    print("Parallelized model generation")

    print("Generating flux models")
    flux =  Parallel(n_jobs=20,verbose=5)(delayed(generator.rtdist_flux)(pars, egrid)
                                    for pars in theta_flux)
    flux = np.asarray(flux)
    print("Checking for spectra below threshold")
    flux, theta_flux, theta_lags = spectraChecker(flux,theta_flux,theta_lags,
                                                  1e-11)
    print("Saving flux data")
    saveData(flux, theta_flux, 
             "data/locations/","loc_flux_test.csv")
    """
    set_envir_vars(wrk_dir)
    PCA_plotting(wrk_dir)
    
    
if __name__ == "__main__":
    main()