"""
This program serves to visualise a neural network's outputs vs the true values.
"""
from sherpa.astro.ui import unpack_rmf
import torch
import os

import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap
import matplotlib.colors as colors
import matplotlib

import numpy as np
from torch.utils.data import DataLoader
from joblib import load
from joblib import Parallel, delayed

import pandas as pd
from tqdm import tqdm

import network
from dataStructures import LoadFluxData, LoadLagsData, Losses, Residual
from generator import generate_test_set, readAndRemoveNans, rtdist_erg_flux
import generator
from processing import saveData, nanChecker
            
def inverse(scaler,data):
    """
    Transforms normalized data back to original form

    Parameters
    ----------
    scaler : scipy scaler
        scaler object that has been previously fitted on data.
    data : ndarray or other list-like object
        normalized data to transform.

    Returns
    -------
    scaled_data : ndarray
        rescaled data.

    """
    scaled_data = scaler.inverse_transform(data)
    return scaled_data

def returnContinuous(df):
    return df.data

def variances(query_samples, active_loop_num):
    #Plot distribution of variances
    plt.hist(query_samples,bins=100)
    plt.savefig(f"dists/loop_{active_loop_num}_variances.png")
    plt.close()

def distributions(data,labels,fname):
    """
    Plots distributions of parameters generated by active learning

    Parameters
    ----------
    data : ndarray or list-like object
        parameter set distribution.
    labels : ndarray or list-like object
        list of label for given parameters.
    fname : string
        save location.

    """
    for i,column in enumerate(data.T):
        plt.hist(column, bins=100, density = True)
        plt.xlabel(labels[i])
        plt.savefig(f"{fname}{labels[i]}.png")
        plt.close()

def residual_plots(egrid, pred, da, fname, title, mname, log = False, 
                   norm = False, mode = "flux"):
    """
    Plots comparison between NN model output and rtdist output with a 
    percentage residual subplot underneath.

    Parameters
    ----------
    egrid : ndarray
        energy grid to plot points on (x-axis).
    pred : ndarray
        NN model output to be plotted.
    da : ndarray
        rtdist model output to be plotted.
    fname : string
        file save location.
    title : string
        title of plot.
    mname : string
        model name.
    log : bool, optional
        If True, change y-label to be log(mode). The default is False.
    norm : bool, optional
        If True, enforce maximum range on residuals. The default is False.
    mode : string, optional
        the type of model output to be compared. Is placed as the x-label.
        The default is "flux".

    """
    fig, axs = plt.subplots(2,1,sharex=True)
    axs[0].plot(egrid,pred,c="blue",label="NN model")
    axs[0].plot(egrid,da,c="r",label="Truth",lw=1.)
    axs[0].legend()
    axs[0].set_title(title)
    if log == True:
        axs[0].set_ylabel(f"Log({mode})")
        axs[0].set_yscale("log")
    else:
        axs[0].set_ylabel(f"{mode}")
    axs[1].scatter(egrid,(da-pred)/da,s=0.5)
    axs[1].set_ylabel("Residuals")
    axs[1].set_xlabel("Energy in keV")
    axs[1].axhline(y=0.01,ls="--",color="orange")
    axs[1].axhline(y=-0.01,ls="--",color="orange")
    max_res = np.absolute((da-pred)/da).max()
    if max_res > 1 and norm == True:
        axs[1].set_ylim(-1,1)
    plt.tight_layout()
    plt.savefig(f"samples/{mname}_{fname}.png")
    plt.close()
    
def heatmap_plots(df, indexes, ticks, ticklabels, fname, mode):
    """
    Iterates through parameters and plots heatmaps for each parameter.

    Parameters
    ----------
    df : pandas dataframe
        residuals dataframe.
    indexes : ndarray or list-like object
        list of names of parameters.
    ticks : ndarray or list-like object
        y-tick locations to use.
    ticklabels : ndarray or list-like object
        y-tick labels for y-ticks. Must be the same length as ticks.
    fname : string
        filename to save to.
    mode : string
        signifies type of output being used.

    """
    for i,index in enumerate(indexes):
        print(index)
        df.sort_values(by=index,inplace=True,ignore_index=True)
        heatmap(df, index, ticks[i], ticklabels[i], fname, mode)

def set_envir_vars(wrk_dir):
    """
    Sets environment variables for rtdist plotting

    Parameters
    ----------
    wrk_dir : string
        location of working directory.
    """
    #set envionmental variables required in xspec with simrtdist
    environ_vars = {"REV_VERB":"0","MU_ZONES":"1","ION_ZONES":"1","A_DENSITY":"1",
                    "EMIN_REF":"0.5","EMAX_REF":"10","EMIN_REF2":"0.5",
                    "EMAX_REF2":"10", "SEED_SIM":"-2851043",
                    "RMF_SET":wrk_dir+"/ResponseFiles/PN.rmf",
                    "ARF_SET":wrk_dir+"/ResponseFiles/PN.arf",
                    "BKG_SET":wrk_dir+"/ResponseFiles/PNbackground_spectrum.fits",
                    "BACKSCL":"1.0"}

    for key in environ_vars:
        os.environ[key] = environ_vars[key]
    
    print("Environmental variables successfully set")

def retrieve_egrid(wrk_dir):
    """
    Find the energy grid for plotting of spectra

    Parameters
    ----------
    wrk_dir : string
        location of working directory.

    Returns
    -------
    egrid : ndarray
        energy grid values.

    """
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min
    
    return egrid

def plot_flux_dists():
    wrk_dir = os.getcwd()
    rmf_name = wrk_dir+"/ResponseFiles/PN.rmf"
    rmf = unpack_rmf(rmf_name)
    egrid = rmf.e_min #energy grid used to evaluate the xspec model
    labels = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    
    range_BH = np.asarray(generator.lhs_BH())
    range_AGN = np.asarray(generator.lhs_AGN())
    
    theta_bh = generator.lhs_generation(5000, range_BH)
    theta_agn = generator.lhs_generation(5000, range_AGN)
    with Parallel(n_jobs=10,verbose=5) as parallel:
        #generate rtdist models for the correlated grid
        flux_BH = parallel(delayed(generator.rtdist_erg_flux)(pars, egrid)
                                        for pars in theta_bh)
        flux_AGN = parallel(delayed(generator.rtdist_erg_flux)(pars, egrid)
                                        for pars in theta_agn)
    flux_BH = np.array(flux_BH)
    flux_AGN = np.array(flux_AGN)
    
    BHs = pd.Dataframe(data=theta_bh,columns=labels)
    BHs["flux"] = flux_BH
    AGN = pd.Dataframe(data=theta_agn,columns=labels)
    AGN["flux"] = flux_AGN
    
    for label in labels:
        plt.scatter(BHs[label],BHs["flux"])
        plt.xlabel(label)
        plt.ylabel("Flux in erg/s/cm^2")
        plt.title(f"How flux trends with {label}")
        plt.savefig(f"data/flux/{label}.png")
        plt.close()
    
    flux_BH = flux_BH[np.isnan(flux_BH)==False]
    flux_BH = flux_BH[(flux_BH>1e-18)]
    flux_AGN = flux_AGN[np.isnan(flux_AGN)==False]
    flux_AGN = flux_AGN[(flux_AGN>1e-18)]
    
    print(len(flux_BH[(flux_BH > 1e-15)& (flux_BH < 2.4e-6)]))
    print(len(flux_AGN[(flux_AGN > 1e-15)& (flux_AGN < 2.4e-6)]))
    
    bh_bins = np.logspace(np.log10(np.min(flux_BH)),np.log10(np.max(flux_BH)),
                          100, endpoint=True)
    agn_bins = np.logspace(np.log10(np.min(flux_AGN)),np.log10(np.max(flux_AGN)),
                           100, endpoint=True)
    
    plt.hist(flux_BH, bins=bh_bins)
    plt.axvline(2.4e-6, ls = "--", c="orange")
    plt.axvline(1e-15, ls = "--", c="orange")
    plt.title("Black hole flux distributions")
    plt.xlabel("Total flux in ergs/s/cm^2")
    plt.xscale("log")
    plt.savefig("bh_dists.png")
    plt.close()
    
    plt.hist(flux_AGN, bins=agn_bins)
    plt.axvline(2.4e-6,ls = "--",c="orange")
    plt.axvline(1e-15,ls = "--",c="orange")
    plt.xlabel("Total flux in ergs/s/cm^2")
    plt.title("AGN flux distributions")
    plt.xscale("log")
    plt.savefig("agn_dists.png")
    plt.close()

def model_load(model_loc, egrid, lags = None):
    """
    Loads neural network model states from the disk. Can load both the flux and
    lag neural network model types.

    Parameters
    ----------
    model_loc : string
        location of the file with neural network parameters.
    egrid : ndarray
        energy grid values.
    lags : any, optional
        If this is not None, assumes loading a time lags model. The default is 
        None.

    Returns
    -------
    model : pytorch model
        the desired pytorch neural network model.

    """
    if lags == None:
        model = network.MagFluxNetwork(5, len(egrid))
    else:
        model = network.MagLagsNetwork(5, len(egrid))
    model.load_state_dict(torch.load(model_loc))
    model.eval()
    return model
    
def residual_sorting(df,indexing):
    """
    Sorts residual dataframe by the given index and returns the 0.01, 0.25, 
    0.5, 0.75 percentile values as tick labels

    Parameters
    ----------
    df : pandas dataframe
        dataframe containing residuals and their corresponding parameters.
    indexing : string
        name of the column to sort dataframe by.

    Returns
    -------
    tick : list
        list of tick values index.
    ticklabel : list
        list of tick values.

    """
    df.sort_values(by=indexing,inplace=True,ignore_index=True)
    percents = [0,0.25,0.5,0.75]
    tick = []
    ticklabel = []
    for p in percents:
        tick.append(int(len(df)*p))
        ticklabel.append(f"{df[indexing][int(len(df)*p)]:.2f}")
    return tick,ticklabel

def residual_computation(dataloader, model, scaler, mode, dec_mag=False):
    """
    Computes and records residual differences between neural network outputs
    and rtdist outputs. Records them with the parameters. For data and model
    outputs below a threshold, we consider the residual difference to be 0.

    Parameters
    ----------
    dataloader : pytorch dataloader
        contains test data and parameters.
    model : pytorch model
        neural network model to compare results to.
    scaler : scikitlearn MinMaxScaler
        scaler to change network output back to real output.
    mode : string
        signifies if using a time lags or flux model.

    Returns
    -------
    dataframe : pandas dataframe
        contains residuals and parameters.
    ticks : list
        list of lists of tick indexes for each parameter.
    ticklabels : list
        list of lists of tick values for each parameter.

    """
    pars = [[] for i in range(5)]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    logged = [1,2,3,4]
    pars_list = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    pars_list = ["a","inc","rin","rout","distance"]
    residuals = []
    for batch, (D,P) in enumerate(tqdm(dataloader)):
        for i in range(len(pars)):
            if i in logged:
                pars[i].append(10**P[0][i].item())
            else:
                pars[i].append(P[0][i].item())
        if mode == "flux":
            if dec_mag == False:
                pred = model(P).detach().numpy()
                pred = 10**(inverse(scaler,pred))
            else:
                mag_pred, dec_pred = model(P)
                dec_pred = (dec_pred*9) + 1
                pred = dec_pred.detach().numpy() * (10**np.floor(inverse(scaler,
                                                        mag_pred.detach().numpy())))
        else:
            if dec_mag == False:
                pred, I_pred = model(P)
                pred = 10**(inverse(scaler,pred.detach().numpy()))
            else:
                mag_pred, dec_pred, I_pred = model(P)
                dec_pred = (dec_pred*9) + 1
                pred = (dec_pred.detach().numpy() * 
                        (10**np.round(inverse(scaler,
                                              mag_pred.detach().numpy()))))
        if mode != "flux":
            pred = pred*np.where(I_pred.detach().numpy() > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.numpy()
        try:
            if mode == "flux":
                resid = np.where((np.abs(D)<=1e-38)&(np.abs(pred)<=1e-38),0,resid)
            else:
                resid = np.where((np.abs(D)<=1e-6)&(np.abs(pred)<=1e-6),0,resid)
        except:
            pass
        resid = np.absolute(np.asarray(resid))
        residuals.append(resid)
        
    residuals = np.squeeze(np.asarray(residuals))
    obj_residuals = []
    for res in residuals:
        obj_residuals.append(Residual(res))
    
    data = {}
    for i,label in enumerate(pars_list):
        data[label] = pars[i]
    data["residuals"] = obj_residuals
    
    dataframe = pd.DataFrame.from_dict(data)
    ticks = []
    ticklabels = []
    for label in pars_list:
        tick, ticklabel = residual_sorting(dataframe, label)
        ticks.append(tick)
        ticklabels.append(ticklabel)
    
    return (dataframe, ticks, ticklabels)

def calculate_loss(testing_dataloader, model, scaler, mode = "flux", 
                   dec_mag = False):
    """
    

    Parameters
    ----------
    testing_dataloader : TYPE
        DESCRIPTION.
    model : TYPE
        DESCRIPTION.
    scaler : TYPE
        DESCRIPTION.
    mode : TYPE, optional
        DESCRIPTION. The default is "flux".

    Returns
    -------
    residuals : TYPE
        DESCRIPTION.

    """
    residuals = []
    for batch, (D,P) in enumerate(tqdm(testing_dataloader)):
        if dec_mag == False:
            if mode == "flux":
                pred = model(P)
            else:
                pred, I_pred = model(P)
        else:
            if mode == "flux":
                mag_pred, dec_pred = model(P)
            else:
                mag_pred, dec_pred, I_pred = model(P)
            
            dec_pred = (dec_pred.detach().numpy()*9) + 1
            pred = dec_pred * (10**np.round(inverse(scaler,mag_pred.detach().numpy())))
        
        if mode != "flux":
            pred = pred*np.where(I_pred.detach().numpy() > 0.5, 1, -1)
        resid = (D-pred)/D
        resid = resid.numpy()
        
        try:
            if mode == "flux":
                resid = np.where((np.abs(D)<=1e-38)&(np.abs(pred)<=1e-38),
                                 0,resid)
            else:
                resid = np.where((np.abs(D)<=1e-6)&(np.abs(pred)<=1e-6),
                                 0,resid)
        except:
            print("Thresholds failed")
            pass
        residuals.append(np.absolute(np.asarray(resid)))
    residuals = np.asarray(residuals)
    return residuals

def residuals_dataframe(residuals,names):
    d = {"Residuals":[],"Sample Size":[]}
    for i,name in enumerate(names):
        print(name)
        for point in residuals[i].flatten():
            d["Residuals"].append(point)
            d["Sample Size"].append(name) 
    print("# of residuals:"+str(len(d["Residuals"])))
    print("# of labels:"+str(len(d["Sample Size"])))
    df = pd.DataFrame(data = d)
    return df

def model_samples(testing_dataloader,scaler,model,egrid,mname,mode,no_brk=5,
                  dec_mag=False):
    for batch, (D,P) in enumerate(testing_dataloader):
        print(batch)
        D = np.squeeze(D)
        print(D)
        if mode == "flux":
            D[D<=1e-38] = 1e-38
            da = np.squeeze(D)
        else:
            D[(D<0)&(np.abs(D)<1e-6)] = -1e-6
            D[(D>0)&(np.abs(D)<1e-6)] = 1e-6
            da = np.squeeze(D)
        
        if dec_mag == False:
            da_log = np.log10(np.abs(da))
            da_log_scal = scaler.transform(da_log.reshape(1, -1)).flatten()
            if mode == "flux":
                pred = model(P)
            else:
                pred, I_pred = model(P)
            log_pred = inverse(scaler,pred.detach().numpy())
            sca_pred = np.squeeze(10**(log_pred))
        else:
            da_mag = np.floor(np.log10(da))
            da_dec = da/10**da_mag
            if mode == "flux":
                mag_pred, dec_pred = model(P)
            else:
                mag_pred, dec_pred, I_pred = model(P)
            sca_dec_pred = (dec_pred*9) + 1
            sca_mag_pred = inverse(scaler, mag_pred.detach().numpy())
            sca_pred = np.squeeze((sca_dec_pred.detach().numpy() * 
                    (10**np.round(sca_mag_pred))))
        #generate neural network prediction and rescale to linear space
        if mode == "flux":
            sca_pred[sca_pred<=1e-38] = 1e-38
        else:
            sca_pred[sca_pred<1e-6] = 1e-6
            sca_pred = np.squeeze(sca_pred*np.where(I_pred > 0.5, 1, -1))
        
        fname = f"{batch}"
        title = "Direct comparison"
        
        residual_plots(egrid, sca_pred, da, fname, title, mname, norm = True, mode = mode)
        
        if dec_mag == False:
            fname = f"{batch}_log"
            title = "Log scaled output"
            residual_plots(egrid, log_pred, da_log, fname, title, mname, 
                           mode = mode)
            fname = f"{batch}_scal"
            title = "Neural network normalised output"
            residual_plots(egrid, pred, da_log_scal, fname, title, mname, 
                           mode = mode)
        else:
            fname = f"{batch}_mag"
            title = "NN mag output"
            residual_plots(egrid, np.squeeze(sca_mag_pred), da_mag, 
                           fname, title, mname, mode = mode)
            fname = f"{batch}_dec"
            title = "NN dec output"
            residual_plots(egrid, np.squeeze(sca_dec_pred.detach().numpy()), da_dec, 
                           fname, title, mname, mode = mode)
            
        if batch > no_brk:
            break

def heatmap(df, index, ticks, ticklabels, fname, mode):
    zlabel = "Fractional difference between NN model and rtdist"
    Z_center = -2.5
    #colormap
    top = cm.get_cmap('autumn', 128)
    bottom = cm.get_cmap('winter', 128)
    middle = cm.get_cmap('summer',128)

    newcolors = np.vstack((bottom(np.linspace(0, 1/2, 128)),
                           middle(np.linspace(0, 1/2, 128)),
                        top(np.linspace(2/3, 1, 128))))
    newcmp = ListedColormap(newcolors, name='summer_winter_autumn')
    
    residuals = df["residuals"].apply(returnContinuous)
    resids = []
    for item in residuals:
        resids.append(item)
    resids = np.asarray(resids)
    
    fig = plt.figure(figsize=(10,10))
    norm = colors.LogNorm(vmin = 10**(Z_center-1.5), vmax = 10**(Z_center+1.5))
    ax = plt.pcolormesh(resids, cmap=newcmp, norm=norm)
    c_ticks = [10**(Z_center-1.5), 10**(Z_center-1), 10**(Z_center-0.5), 10**(Z_center),
                10**(Z_center+0.5),10**(Z_center+1),10**(Z_center+1.5)]
    cbar = plt.colorbar(ticks=c_ticks, format='%.0e', norm=norm)
    plt.yticks(ticks,labels=ticklabels)
    if mode == "flux":
        plt.xticks(np.arange(0,4096,4096/4), labels=np.arange(0,20,5))
    else:
        egrid = np.logspace(np.log10(0.5),np.log10(11),num=26)[:-1]
        tick_index = np.arange(0,25,24/4).astype(int)
        plt.xticks(tick_index, labels=np.round(egrid[tick_index],2))
    plt.xlabel("Energy in keV")
    plt.ylabel(index)
    
    cbar.set_label(zlabel, rotation=270, labelpad=15)
    fig.tight_layout()
    matplotlib.rcParams.update({'font.size': 16})
    plt.savefig(f"heatmaps/{fname}_{index}.png")
    plt.close()
    return

def plot_loss_vs_sample_size(grid_sample_nums, grid, active_sample_nums, active,
                             mode):
    fig , axs = plt.subplots(1,2,sharey=True, sharex=True, figsize=(12,9))
    
    for (x,y,z) in zip(grid_sample_nums,grid.low,grid.high):
        axs[0].scatter([x]*len(y),y, s=1, color="orange", zorder = 1, marker = "x",
                       alpha = 0.5)
        axs[0].scatter([x]*len(z),z, s=1, color="orange", zorder = 1, marker = "x",
                       alpha = 0.5)
        
    axs[0].fill_between(grid_sample_nums, grid.q_95, 
                     grid.q_5, alpha = 0.25,color = "orange",
                     zorder=3)
    axs[0].fill_between(grid_sample_nums, grid.q_75, 
                     grid.q_25, alpha = 0.5,color = "orange",
                     zorder=4)
    axs[0].fill_between(grid_sample_nums, grid.q_99, 
                     grid.q_1, alpha = 0.5,color = "orange",
                     zorder=2)
    axs[0].plot(grid_sample_nums,grid.median,label="Grid",color = "orange",
             zorder=5)
    
    for (x,y,z) in zip(active_sample_nums,active.low,active.high):
        axs[1].scatter([x]*len(y),y, s=1, color="blue", zorder = 2, marker = "x",
                       alpha = 0.5)
        axs[1].scatter([x]*len(z),z, s=1, color="blue", zorder = 2, marker = "x",
                       alpha = 0.5)
        
    axs[1].fill_between(active_sample_nums, active.q_95, 
                     active.q_5, alpha = 0.25,color = "blue",
                     zorder=3)
    axs[1].fill_between(active_sample_nums, active.q_75, 
                     active.q_25, alpha = 0.5,color = "blue",
                     zorder=4)
    axs[1].fill_between(active_sample_nums, active.q_99, 
                     active.q_1, alpha = 0.5,color = "blue",
                     zorder=2)
    axs[1].plot(active_sample_nums,active.median,label="Active learning",
             color = "blue",zorder=5)
    
    axs[0].axhline(y=1e-2, ls = "--",label="1% error",zorder=6,color="green")
    axs[1].axhline(y=1e-2, ls = "--",zorder=6,color="green")
    axs[0].axhline(y=1e-3, ls = "dashdot",label="0.1% error",zorder=7,color="red")
    axs[1].axhline(y=1e-3, ls = "dashdot",zorder=7,color="red")
    
    plt.yscale("symlog")
    plt.xscale("symlog")
    
    plt.yticks([1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2,1e-1,1e0,1e1])
    fig.suptitle(f"Loss by sample size for {mode}")
    
    fig.supxlabel("Number of samples used in training")
    fig.supylabel("Residuals")
    lines = []
    labels = []
      
    for ax in fig.axes:
        Line, Label = ax.get_legend_handles_labels()
        # print(Label)
        lines.extend(Line)
        labels.extend(Label)
        
    fig.legend(lines, labels, loc='upper right')
    matplotlib.rcParams.update({'font.size': 16})
    plt.savefig(f"loss/loss_size_{mode}.png")
    plt.close()

def loss_epochs_plot(loss_base_loc,mode):
    
    train_names = [loss_base_loc+f"grid_{i}_{mode}_tr_loss.txt" for i in range(5,11)]
    test_names = [loss_base_loc+f"grid_{i}_{mode}_te_loss.txt" for i in range(5,11)]
    
    active_loss = np.loadtxt(loss_base_loc+f"40_{mode}_tr_loss.txt")
    active_test = np.loadtxt(loss_base_loc+f"40_{mode}_te_loss.txt")
    
    plt.plot(np.loadtxt(train_names[-1]), label="Training loss: 10x10 grid", 
             c = "red", ls = "-")
    plt.plot(np.loadtxt(test_names[-1]), label = "Validation loss: 10x10 grid", 
             c = "red", ls = "--")
    
    plt.plot(active_loss,label = "Training loss: active learning", c = "blue",
             ls = "-")
    plt.plot(active_test,label = "Validation loss: active learning", c = "blue",
             ls = "--")
    
    plt.yscale("log")
    plt.xlabel("Training epochs")
    plt.ylabel("Loss")
    plt.title(f"Comparison of loss by strategy for {mode}")
    plt.legend()
    plt.savefig(f"loss/loss_time_{mode}.png")
    plt.close()

def check_uniques(array1,array2):
    combo = pd.concat([array1,array2])
    combo.drop_duplicates(keep=False)
    return combo

def aggregate_dists(files):
    nbins = 100
    
    labels = ["0th loop", "10th loop", "20th loop", "30th loop", "40th loop"]
    
    rins = []
    routs = []
    distances = []
    spins = []
    
    last_pars = pd.DataFrame()
    for file in files:
        print(file)
        df = pd.read_csv(file)
        pars = df.loc[:, df.columns!="Location"]
        new_pars = check_uniques(pars,last_pars)
        last_pars = pars
        rins.append(-1*new_pars.loc[:,"rin"])
        routs.append(new_pars.loc[:,"rout"])
        distances.append(new_pars.loc[:,"distance"])
        spins.append(new_pars.loc[:,"a"])
    
    cmap = cm.get_cmap("Wistia")(np.linspace(0, 1, 5))
    
    hist, bins_rins, _ = plt.hist(rins, nbins, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    logbins_rins = np.logspace(np.log10(bins_rins[0]),np.log10(bins_rins[-1]),len(bins_rins))
    
    hist, bins_routs, _ = plt.hist(routs, nbins, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    logbins_routs = np.logspace(np.log10(bins_routs[0]),np.log10(bins_routs[-1]),len(bins_routs))
    
    hist, bins_distances, _ = plt.hist(distances, nbins, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    logbins_distances = np.logspace(np.log10(bins_distances[0]),np.log10(bins_distances[-1]),len(bins_distances))
    plt.close()
    
    fig, axs = plt.subplots(2,2,sharey=True,figsize=(12,9))
    matplotlib.rcParams.update({'font.size': 16})
    
    axs[0,0].hist(rins, logbins_rins, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    axs[0,0].set_xscale("log")
    axs[0,0].set_xlabel("Inner radius / ISCO")
    
    axs[0,1].hist(routs, logbins_routs, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    axs[0,1].set_xscale("log")
    axs[0,1].set_xlabel("Outer radius / Rg")
    axs[0,1].legend()
    
    axs[1,0].hist(distances, logbins_distances, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    axs[1,0].set_xscale("log")
    axs[1,0].set_xlabel("Distances / Kpc")
    
    axs[1,1].hist(spins, nbins, histtype="bar", stacked=True, 
                             color = cmap, label=labels)
    axs[1,1].set_xlabel("Spin")
    plt.yscale("log")
    plt.tight_layout()
    plt.savefig("dists/stacked.png")
    plt.close()
    

def analysis(names, locs, nums, scaler_names, egrid, lags = None, dec_mag = False):
    if lags != None:
        mode = "lags"
    else:
        mode = "flux"
    scaler_base_loc = os.getcwd()+"/scalers/"
    indexes = ["height","a","inc","rin","rout","z","Gamma","distance","Afe","logNe","kte",
              "nH","boost","mass","honr","b1","b2","phiAB","g","Anorm"]
    indexes = ["a","inc","rin","rout","distance"]
    
    median_loss = []
    loss_01_q = []
    loss_05_q = []
    loss_25_q = []
    loss_75_q = []
    loss_95_q = []
    loss_99_q = []
    loss_low_out = []
    loss_high_out = []
    
    resid_list = []
    
    pars_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,21,22,23]
    negatives = [0,3]
    logged = [0,2,3,4,7,8,10,11,12,13,19]
    
    pars_list = [1,2,3,4,7]
    negatives = [2]
    logged = [1,2,3,4]
    
    if type(scaler_names) != list:
        tmp = [scaler_names for i in range(len(names))]
        scaler_names = tmp
        
    for (model_loc,fname,scaler_name) in zip(locs, names, scaler_names):
        scaler = load(scaler_base_loc+scaler_name)
        #put test set into dataloader format
        batch_size = 1
        if lags == None:
            test_data = LoadFluxData("data/locations/loc_flux_test.csv",scaler,
                                      scaler_name, pars_list, negatives = negatives, 
                                      logged = logged) #scaler unused but must be parsed
            model = model_load(model_loc, egrid, lags = lags)
        else:
            test_data = LoadLagsData("data/locations/loc_lags_test.csv",scaler,
                                       scaler_name, pars_list, negatives = negatives, 
                                       logged = logged) #scaler unused but must be parsed
            model = model_load(model_loc, egrid[:-1], lags = lags)
        
        testing_dataloader = DataLoader(test_data,batch_size = batch_size,
                                        num_workers=1,shuffle=True)
        #folname = str(fname)
        fname = f"{fname}_{mode}"
        print(fname)
        residuals = calculate_loss(testing_dataloader, model, scaler, mode,
                                   dec_mag)
        resid_list.append(residuals)
        median = np.median(residuals)
        q_01,q_05, q_25, q_75, q_95, q_99 = np.quantile(residuals,
                                                        [0.01,0.05,0.25,0.75,
                                                         0.95,0.99])
        median_loss.append(median)
        loss_05_q.append(q_05)
        loss_25_q.append(q_25)
        loss_75_q.append(q_75)
        loss_95_q.append(q_95)
        loss_99_q.append(q_99)
        loss_01_q.append(q_01)
        if mode == "flux":
            filt = 1000
        else:
            filt = 1
        high_outliers = residuals[residuals >= np.percentile(residuals, 99)][::filt]
        low_outliers = residuals[residuals <= np.percentile(residuals, 1)][::filt]
        loss_low_out.append(low_outliers)
        loss_high_out.append(high_outliers)
        if lags == None:
            model_samples(testing_dataloader, scaler, model, egrid, fname, 
                          mode, dec_mag=dec_mag)
        else:
            model_samples(testing_dataloader, scaler, model, egrid[:-1], fname, 
                          mode, dec_mag=dec_mag)
        df, ticks, ticklabels = residual_computation(testing_dataloader, 
                                                     model, scaler, mode,
                                                     dec_mag=dec_mag)
        heatmap_plots(df, indexes, ticks, ticklabels, fname, mode)
        del df, ticks, ticklabels
        
    resid_list = np.asarray(resid_list)
    df = residuals_dataframe(resid_list, nums)
    large_resid = df[df["Sample Size"] == df["Sample Size"].max()].max()[0]
    print(f"The largest residual was {large_resid}")
    over = len(df[(df["Sample Size"] == df["Sample Size"].max())&(df["Residuals"] >= 0.01)])
    print(f"There were {over} residuals over 1%")
    overall = len(df[df["Sample Size"] == df["Sample Size"].max()])
    print(f"There were {overall} residuals overall")
    print(f"The ratio of residuals over 1% was {over/overall}")
    
    quantiles = [loss_01_q, loss_05_q, loss_25_q,
                 loss_75_q, loss_95_q, loss_99_q,
                 loss_high_out, loss_low_out, median_loss]
    quantile_names = ["q_1", "q_5", "q_25", "q_75", "q_95", "q_99", "high", 
                      "low", "median"]
    quants = Losses()
    for quant_arr, quant_name in zip(quantiles,quantile_names):
        quants.set_loss(quant_arr,quant_name)
    
    return quants

def active_v_grid(wrk_dir, egrid, lags_egrid):
    model_base_loc = wrk_dir+"/models/"
    loss_base_loc = wrk_dir+"/loss/"
    
    active_name = [0,5,10,15,20]
    active_name = np.array(active_name)
    active_sample_flux_nums = []
    active_sample_lags_nums = []
    for name in active_name:
        active_sample_flux_nums.append(len(pd.read_csv(f"data/locations/loc_flux_{name}.csv")))
        active_sample_lags_nums.append(len(pd.read_csv(f"data/locations/loc_lags_{name}.csv")))
    active_flux_names = [f"{model_base_loc}{i}_flux_model.pth" for i in active_name]
    active_lags_names = [f"{model_base_loc}{i}_lags_model.pth" for i in active_name]
    grid_flux_name = [f"grid_{i}" for i in range(5,11)]
    grid_lags_name = [f"grid_{i}" for i in range(5,11)]
    grid_flux_scaler = [f"mag_grid_{i}_flux_scaler.bin" for i in range(5,11)]
    grid_lags_scaler = [f"mag_grid_{i}_lags_scaler.bin" for i in range(5,11)]
    active_flux_scaler = "active_scaler_flux.bin"
    active_lags_scaler = "active_scaler_lags.bin"
    grid_model_names = np.array([5,6,7,8,9,10])
    grid_sample_nums = grid_model_names**5
    grid_model_flux_names = [model_base_loc+f"grid_{i}_flux.pth" for i in grid_model_names]
    grid_model_lag_names = [model_base_loc+f"grid_{i}_lags.pth" for i in grid_model_names]
    
    loss_epochs_plot(loss_base_loc,"flux")
    loss_epochs_plot(loss_base_loc,"lags")
    grid_flux = analysis(grid_flux_name, grid_model_flux_names, grid_sample_nums,
                            grid_flux_scaler, egrid,
                            dec_mag = True)
    
    grid_lags = analysis(grid_lags_name, grid_model_lag_names, grid_sample_nums,
                            grid_lags_scaler, lags_egrid, lags=True,
                            dec_mag = True)
    
    active_flux = analysis(active_name, active_flux_names, active_sample_flux_nums, 
                      active_flux_scaler, egrid, dec_mag = True)
    
    active_lags = analysis(active_name, active_lags_names, active_sample_lags_nums, 
                      active_lags_scaler, lags_egrid, lags=True, dec_mag = True)
    
    
    
    print("Plotting loss by sample size")
    print("Plotting fluxes")
    plot_loss_vs_sample_size(grid_sample_nums, grid_flux,
                             active_sample_flux_nums, active_flux, mode="flux")
    print("Plotting lags")
    plot_loss_vs_sample_size(grid_sample_nums, grid_lags,
                             active_sample_lags_nums, active_lags, mode="lags")
    
def main():
    wrk_dir = os.getcwd()
    
    """
    nums = [0,10,20,30,40]
    files = [f"data/locations/loc_flux_{loop}.csv" for loop in nums]
    aggregate_dists(files)
    """
    
    plot_flux_dists()
    quit()
    
    egrid = retrieve_egrid(wrk_dir)
    lags_egrid = np.logspace(np.log10(0.5),np.log10(11),num=26)
    
    flux, lags, theta_flux, theta_lags = generate_test_set(1000, egrid, lags_egrid)
    
    saveData(flux, theta_flux, "data/locations/", "loc_flux_test.csv")
    saveData(lags, theta_lags, "data/locations/", "loc_lags_test.csv")
    
    readAndRemoveNans("data/locations/loc_flux_test.csv",
                      "data/locations/loc_lags_test.csv")
    
    set_envir_vars(wrk_dir)
    active_v_grid(wrk_dir, egrid, lags_egrid)
    
if __name__ == "__main__":
    main()